### ISSUE TITLE
AttributeError in Upcoming Events

### ISSUE THREAD

**Issue by indico-bot** [indico/indico#1028]
```yaml
# Ticket imported from Trac
# Reported by: makub
```

On a fresh installation of Indico 0.98.1 with empty database, the admins page in Server admin - Homepage - Upcoming Events is not displayed due to the following exception:

```
2012-05-10 13:26:57,467 indico.requestHandler - ERROR base.py:363 -- Request 140624552881808 failed: "'int' object has no attribute 'seconds'"
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/indico-0.98.1-py2.6.egg/MaKaC/webinterface/rh/base.py", line 565, in process
    res = self._process()
  File "/usr/local/lib/python2.6/dist-packages/indico-0.98.1-py2.6.egg/MaKaC/webinterface/rh/admins.py", line 98, in _process
    return p.display()
  File "/usr/local/lib/python2.6/dist-packages/indico-0.98.1-py2.6.egg/MaKaC/webinterface/pages/base.py", line 189, in display
    self._display( params ), \
  File "/usr/local/lib/python2.6/dist-packages/indico-0.98.1-py2.6.egg/MaKaC/webinterface/pages/main.py", line 159, in _display
    body = WMainBase(self._getBody( params ), self._timezone, self._getNavigationDrawer(),
  File "/usr/local/lib/python2.6/dist-packages/indico-0.98.1-py2.6.egg/MaKaC/webinterface/pages/admins.py", line 134, in _getBody
    p = { "body": self._getPageContent( params ),
  File "/usr/local/lib/python2.6/dist-packages/indico-0.98.1-py2.6.egg/MaKaC/webinterface/pages/admins.py", line 280, in _getPageContent
    return wcomponents.WTabControl( self._tabCtrl, self._getAW() ).getHTML( self._getTabContent( params ) )
  File "/usr/local/lib/python2.6/dist-packages/indico-0.98.1-py2.6.egg/MaKaC/webinterface/pages/admins.py", line 318, in _getTabContent
    return wc.getHTML( pars )
  File "/usr/local/lib/python2.6/dist-packages/indico-0.98.1-py2.6.egg/MaKaC/webinterface/wcomponents.py", line 212, in getHTML
    vars = self.getVars()
  File "/usr/local/lib/python2.6/dist-packages/indico-0.98.1-py2.6.egg/MaKaC/webinterface/pages/admins.py", line 325, in getVars
    vars["cacheTTL"] = module.getCacheTTL().seconds/60
AttributeError: 'int' object has no attribute 'seconds'
```

A fix is to remove the ".seconds" from line 325 in admins.py

**Comment by pferreir** [comment]
Completely rewritten in 1.9.x
