### ISSUE TITLE
Error with migration from 0.97 to 1.2 

### ISSUE THREAD

**Issue by miguelzea** [indico/indico#1820]
Hi
I´am traying to migrate my indico 0.97 to 1.2 , but when try with the migrate.py I get the following:

 python /opt/indico/bin/migration/migrate.py --prev-version=0.97 --with-rb                                                                           /usr/lib/python2.6/site-packages/cds_indico-0.97.1-py2.6.egg/MaKaC/common/indexes.py:31: DeprecationWarning: the sets module is deprecated
  import sets
Traceback (most recent call last):
  File "/opt/indico/bin/migration/migrate.py", line 35, in <module>
    from MaKaC.common.indexes import IndexesHolder, CategoryDayIndex, CalendarDayIndex
ImportError: cannot import name CategoryDayIndex

Thanks in advance

**Comment by ThiefMaster** [comment]
Are you sure you installed 1.2? According to the error you are still using code from 0.97...

**Comment by miguelzea** [comment]
Thanks my friend

I´m trying this:

easy_install -U indico
indico_initial_setup --existing-config=/opt/indico/etc/indico.conf
python /path/to/indico/bin/migration/migrate.py --prev-version=0.97

**Comment by miguelzea** [comment]
Thanks again 

I´m just remove my old 0.97 egg folder from python root and works, but I´m getting this now:

 python /opt/indico/bin/migration/migrate.py --prev-version=0.97 --with-rb
/usr/lib/python2.6/site-packages/indico-1.2-py2.6.egg/MaKaC/common/__init__.py:30: DeprecationWarning: MaKaC.common.Configuration is deprecated; use indico.core.config instead
  from .Configuration import Config
Traceback (most recent call last):
  File "/opt/indico/bin/migration/migrate.py", line 35, in <module>
    from MaKaC.common.indexes import IndexesHolder, CategoryDayIndex, CalendarDayIndex
  File "/usr/lib/python2.6/site-packages/indico-1.2-py2.6.egg/MaKaC/common/indexes.py", line 31, in <module>
    from MaKaC.common.logger import Logger
  File "/usr/lib/python2.6/site-packages/indico-1.2-py2.6.egg/MaKaC/common/logger.py", line 266, in <module>
    Logger.initialize()
  File "/usr/lib/python2.6/site-packages/indico-1.2-py2.6.egg/MaKaC/common/logger.py", line 228, in initialize
    cls.handlers = LoggerUtils.configFromFile(logConfFilepath, defaultArgs, filters)
  File "/usr/lib/python2.6/site-packages/indico-1.2-py2.6.egg/MaKaC/common/logger.py", line 133, in configFromFile
    handlers = cls._install_handlers(cp, defaultArgs, formatters, filters)
  File "/usr/lib/python2.6/site-packages/indico-1.2-py2.6.egg/MaKaC/common/logger.py", line 173, in _install_handlers
    args = eval(args, vars(logging))
  File "<string>", line 1, in <module>
NameError: name 'localhost' is not defined

**Comment by ThiefMaster** [comment]
Wrong logging.conf? Missing quotes around `localhost` for the smtp config?

**Comment by miguelzea** [comment]
Everyting looks fine in logging.conf and inthe indico.conf file localhost is with quotes

---- loggin.conf

keys=indico,other,smtp

[formatters]
keys=defaultFormatter,mailFormatter

# For deactivating a handler, remove its entry from
# the list below.
[logger_root]
level=WARNING
handlers=indico,other,smtp


# By default, the args are taken from the indico.conf file.
# For setting your custom arguments, uncomment the args entry below.
[handler_indico]
class=FileHandler
level=NOTSET
formatter=defaultFormatter
#args=('',)

# By default, the args are taken from the indico.conf file.
# For setting your custom arguments, uncomment the args entry below.
[handler_other]
class=FileHandler
level=WARNING
formatter=defaultFormatter
#args=('',)

# By default, the args are taken from the indico.conf file.
# For setting your custom arguments, uncomment args the entry below.
[handler_smtp]
class=handlers.SMTPHandler
level=ERROR
formatter=mailFormatter
#args=('','',[],'')

[formatter_mailFormatter]
format=%(asctime)s %(name)s - %(levelname)s %(filename)s:%(lineno)d -- %(message)s
datefmt=

[formatter_defaultFormatter]
format=%(asctime)s %(name)-16s: %(levelname)-8s - %(message)s
datefmt=

**Comment by pferreir** [comment]
BTW, `level=NOTSET` will not do a thing. You should change it to `level=INFO` at least.

**Comment by pferreir** [comment]
Can we see `indico.conf` nonetheless?

**Comment by miguelzea** [comment]
Thanks again,

I already find the issue in my logging.conf.

but now, when a run the script:
python /opt/indico/bin/migration/migrate.py --prev-version=0.97 --with-rb


shows me the following:

"
/usr/lib/python2.6/site-packages/indico-1.2-py2.6.egg/MaKaC/common/__init__.py:30: DeprecationWarning: MaKaC.common.Configuration is deprecated; use indico.core.config instead
  from .Configuration import Config
/usr/lib/python2.6/site-packages/indico-1.2-py2.6.egg/MaKaC/common/timerExec.py:30: DeprecationWarning: the MaKaC.common.db module is deprecated; use indico.core.db instead
  import MaKaC.common.db as db

This script will migrate your Indico DB to a new version. We recommend that
this operation be executed while the web server is down, in order to avoid
concurrency problems and DB conflicts.


Are you sure you want to execute the migration now? [y/N]

"

when a say "Yes",  shows me:

"Executing migration...

Probing DB connection... DONE!

# Adding new plugins and adapting existing ones to new name policies (0.98b2)
"

But the process never ends, I have waiting for a long time, but stay in the same place.

**Comment by pferreir** [comment]
It looks like your room booking database is not up? Or are you using a single DB setup?

**Comment by pferreir** [comment]
Closing due to inactivity.
