### ISSUE TITLE
Exporting ICS for non-scheduled contribution fails

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1866]
Since there are no dates...

```
Traceback (most recent call last):
 File "/mnt/indico/indico/lib/python2.7/site-packages/Flask-0.10-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
   rv = self.dispatch_request()
 File "/mnt/indico/indico/lib/python2.7/site-packages/Flask-0.10-py2.7.egg/flask/app.py", line 1461, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/mnt/indico/indico/lib/python2.7/site-packages/indico-1.2-py2.7.egg/indico/web/http_api/handlers.py", line 309, in handler
   data = serializer(result)
 File "/mnt/indico/indico/lib/python2.7/site-packages/indico-1.2-py2.7.egg/indico/web/http_api/metadata/serializer.py", line 63, in __call__
   self._data = self._execute(obj, *args, **kwargs)
 File "/mnt/indico/indico/lib/python2.7/site-packages/indico-1.2-py2.7.egg/indico/web/http_api/metadata/ical.py", line 179, in _execute
   mapper(cal, fossil, now)
 File "/mnt/indico/indico/lib/python2.7/site-packages/indico-1.2-py2.7.egg/indico/web/http_api/metadata/ical.py", line 130, in serialize_contrib
   serialize_event(cal, fossil, now, id_prefix="indico-contribution")
 File "/mnt/indico/indico/lib/python2.7/site-packages/indico-1.2-py2.7.egg/indico/web/http_api/metadata/ical.py", line 58, in serialize_event
   event.set('dtstart', getAdjustedDate(fossil['startDate'], None, "UTC"))
 File "/mnt/indico/indico/lib/python2.7/site-packages/indico-1.2-py2.7.egg/MaKaC/common/timezoneUtils.py", line 101, in getAdjustedDate
   return date.astimezone(tz)
AttributeError: 'NoneType' object has no attribute 'astimezone'
```

This should be handled gracefully (404?)

**Comment by mic4ael** [comment]
It should be already fixed thanks to the check we perform inside RH.

```python
class RHContributionExportToICAL(RHContributionDisplayBase):
    """Export contribution to ICS"""

    def _process(self):
        if not self.contrib.is_scheduled:
            raise NotFound('This contribution is not scheduled')
        return send_file('contribution.ics', get_contribution_ical_file(self.contrib), 'text/calendar')
```
