### ISSUE TITLE
DetachedInstanceError: OAuthToken is not bound to a Session

### ISSUE THREAD

**Issue by nop33** [indico/indico#1911]
Having an `access_token`, and requesting the resource `/api/events/<event-id>/registrants/<registrant-id>?access_token=<access-token>` leads to this stack-trace.

Probably caused through the implicit flow.

**sess.query(OAuthToken).filter_by(id=token.id).update({OAuthToken.last_used_dt: now_utc()})**
```
137.138.37.23 - - [03/Jun/2015 13:38:57] "GET /api/events/384535/registrants/1?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxx HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/me/.virtualenvs/indico/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/me/.virtualenvs/indico/lib/python2.7/site-packages/Werkzeug-0.10.4-py2.7.egg/werkzeug/wsgi.py", line 591, in __call__
    return self.app(environ, start_response)
  File "/Users/me/.virtualenvs/indico/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/me/.virtualenvs/indico/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/me/.virtualenvs/indico/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/me/.virtualenvs/indico/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/Users/me/.virtualenvs/indico/lib/python2.7/site-packages/flask/app.py", line 1691, in process_response
    response = handler(response)
  File "/Users/me/dev/indico/src/indico/modules/oauth/provider.py", line 81, in _update_last_use
    sess.query(OAuthToken).filter_by(id=token.id).update({OAuthToken.last_used_dt: now_utc()})
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/orm/attributes.py", line 573, in get
    value = state._load_expired(state, passive)
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/orm/state.py", line 480, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "build/bdist.macosx-10.10-x86_64/egg/sqlalchemy/orm/loading.py", line 608, in load_scalar_attributes
    (state_str(state)))
DetachedInstanceError: Instance <OAuthToken at 0x10b9afd10> is not bound to a Session; attribute refresh operation cannot proceed
```

**Comment by nop33** [comment]
@ThiefMaster you introduced this right?
This happens because of `@after_this_request` in `load_token`.

**Comment by ThiefMaster** [comment]
Can you post the full traceback?

**Comment by ThiefMaster** [comment]
Nevermind.

**Comment by ThiefMaster** [comment]
Ah.. performing a commit expires all objects in the session which triggers a SQL query to refresh them. And zope.sqlalchemy closes the session on commit so refreshing it won't work.

There's an easy fix though - simply save the token id in a variable to avoid accessing the `id` attribute later:

```python
    token_id = token.id

    @after_this_request
    def _update_last_use(response):
        with db.tmp_session() as sess:
            # do not access `token.*`, it's attached to a different session and may be expired!
            sess.query(OAuthToken).filter_by(id=token_id).update({OAuthToken.last_used_dt: now_utc()})
            sess.commit()
        return response
```

Obviously untested, but it should work.
