### ISSUE TITLE
Can't add a new reminder to a meeting

### ISSUE THREAD

**Issue by mic4ael** [indico/indico#1937]
Error occurs in a case whem a user which tries to add a reminder to a meeting has non-latin characters in the name or email.

**Comment by ThiefMaster** [comment]
Where's the traceback? ;x

**Comment by mic4ael** [comment]
I have already fixed that. However, here is an example traceback:

2015-06-16 14:18:37,146 indico.wsgi - ERROR app.py:290 -- WSGI Exception
Traceback (most recent call last):
  File "/home/mic4ael/PythonEnvs/indico/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mic4ael/PythonEnvs/indico/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mic4ael/Desktop/indico/indico/web/flask/util.py", line 122, in wrapper
    return obj().process(params)
  File "/home/mic4ael/Desktop/indico/MaKaC/webinterface/rh/base.py", line 612, in process
    res = self._getMethodByExceptionName(e)(e)
  File "/home/mic4ael/Desktop/indico/indico/util/decorators.py", line 113, in wrapper
    return f(*args, **kw)
  File "/home/mic4ael/Desktop/indico/MaKaC/webinterface/rh/base.py", line 592, in process
    profile_name, res = self._process_retry(params, i, profile, forced_conflicts)
  File "/home/mic4ael/Desktop/indico/MaKaC/webinterface/rh/base.py", line 541, in _process_retry
    return self._process_retry_do(profile)
  File "/home/mic4ael/Desktop/indico/MaKaC/webinterface/rh/base.py", line 534, in _process_retry_do
    res = self._process()
  File "/home/mic4ael/Desktop/indico/indico/modules/events/reminders/controllers.py", line 129, in _process
    form = ReminderForm(event=self.event, schedule_type='relative')
  File "/home/mic4ael/PythonEnvs/indico/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/mic4ael/Desktop/indico/indico/modules/events/reminders/forms.py", line 71, in __init__
    self._set_email_choices()
  File "/home/mic4ael/Desktop/indico/indico/modules/events/reminders/forms.py", line 89, in _set_email_choices
    for email, name in emails.iteritems()
  File "/home/mic4ael/Desktop/indico/indico/modules/events/reminders/forms.py", line 90, in <dictcomp>
    if email and email.strip()}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 5: ordinal not in range(128)

**Comment by ThiefMaster** [comment]
ah.. no need to open an issue if you already fixed something - just send a PR directly next time
