### ISSUE TITLE
Cannot remove upcoming events entries when category is already deleted

### ISSUE THREAD

**Issue by mvala** [indico/indico#1965]
I removed one category and i wanted to remove it from upcomming events and i cannot delete it because category doesn't exists

```
2015-07-07 11:08:33,140 indico.rpc - ERROR json.py:134 -- Service request failed. Request text:
{"version":"1.1","origin":"https://indico.saske.sk/admin/upcoming-events","method":"upcomingEvents.admin.removeObservedObject","params":{"type":"category","id":"4"}}

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/indico-1.2-py2.7.egg/MaKaC/services/interface/rpc/json.py", line 111, in process
    result = ServiceRunner().invokeMethod(str(requestBody["method"]), requestBody.get("params", []))
  File "/usr/lib/python2.7/site-packages/indico-1.2-py2.7.egg/MaKaC/services/interface/rpc/process.py", line 123, in invokeMethod
    result = processRequest(method, copy.deepcopy(params))
  File "/usr/lib/python2.7/site-packages/indico-1.2-py2.7.egg/MaKaC/services/interface/rpc/process.py", line 81, in processRequest
    result = handler(params).process()
  File "/usr/lib/python2.7/site-packages/indico-1.2-py2.7.egg/MaKaC/services/implementation/base.py", line 222, in process
    self._checkParams()
  File "/usr/lib/python2.7/site-packages/indico-1.2-py2.7.egg/MaKaC/services/implementation/upcoming.py", line 90, in _checkParams
    raise ServiceError("ERR-O1", "Category '%s' does not exist" % self._objId)
ServiceError: ERR-O1 : Category '4' does not exist (no inner exception)

Additional information:
Request: 7f4ff5a6fb10
URL: https://indico.saske.sk/services/json-rpc
Endpoint: api.jsonrpc
Method: POST
Params: {'type': 'category', 'id': '4'}
User: <Avatar(1, VALA, Martin)>
IP: 147.213.192.236
User Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0
Referer: https://indico.saske.sk/admin/upcoming-events
```

**Comment by ThiefMaster** [comment]
fixed in 2.x
