### ISSUE TITLE
Can't upload files with non-ascii names (like Chinese filename)

### ISSUE THREAD

**Issue by xfuren** [indico/indico#1968]
At least I can't upload in material management page

ASCII file name -> successfully uploaded
UTF8 file name -> nothing happened

**Comment by ThiefMaster** [comment]
Please provide some more information...

- Which version of Indico are you using?
- Are you getting any errors? (indico.log, browser console)

**Comment by xfuren** [comment]
1. I encountered this issue both on your demo site (indico-sandbox.cern.ch)
and my own 1.2 setup.
2. I saw nothing on my setup, but the following error in the browser
console on tour demo site.

POST
https://indico-sandbox.cern.ch/event/102/manage/material/add?conference=102&parentProtected=false
500 (INTERNAL SERVER ERROR)doSubmit @ jquery_code_67c9365f.min.js:2053

**Comment by ThiefMaster** [comment]
I think the issue is gone in our development version (1.9.x) - can you check in the test category on http://indico.cern.ch if that works fine for you?

**Comment by pferreir** [comment]
Or rather http://indico-sandbox.cern.ch.

**Comment by ThiefMaster** [comment]
sandbox is still running 1.9.. we should probably update it at some point

**Comment by pferreir** [comment]
Yeah, but the issue shouldn't exist there. Should it?

**Comment by ThiefMaster** [comment]
This is the exception that caused it to fail:

```
2015-07-13 08:26:44,558  ERROR    7f69cc6a5ed0  indico                    Request <IndicoRequest 'https://indico-sandbox.cern.ch/event/102/manage/material/add?conference=102&parentProtected=false' [POST]> finished with UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/indico/env/lib/python2.7/site-packages/indico-1.9-py2.7.egg/MaKaC/webinterface/rh/base.py", line 581, in process
    profile_name, res = self._process_retry(params, i, profile, forced_conflicts)
  File "/opt/indico/env/lib/python2.7/site-packages/indico-1.9-py2.7.egg/MaKaC/webinterface/rh/base.py", line 530, in _process_retry
    return self._process_retry_do(profile)
  File "/opt/indico/env/lib/python2.7/site-packages/indico-1.9-py2.7.egg/MaKaC/webinterface/rh/base.py", line 500, in _process_retry_do
    self._checkParams(self._reqParams)
  File "/opt/indico/env/lib/python2.7/site-packages/indico-1.9-py2.7.egg/MaKaC/webinterface/rh/conferenceModif.py", line 3935, in _checkParams
    RHSubmitMaterialBase._checkParams(self, params)
  File "/opt/indico/env/lib/python2.7/site-packages/indico-1.9-py2.7.egg/MaKaC/webinterface/rh/conferenceBase.py", line 257, in _checkParams
    fDict["fileName"] = fileUpload.filename.encode("utf-8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)
```

**Comment by ThiefMaster** [comment]
fixed in 2.x
