### ISSUE TITLE
Some bugs for python 2.6 on indico1.2.1rc2

### ISSUE THREAD

**Issue by geonmo** [indico/indico#2093]
Hello, experts!

I am trying to install indico for our site for 1 week.

Maybe, I found some bugs on my python 2.6 machine.

Could you check this?

1. LDAPAuthetication.py
```bash
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18] Traceback (most recent call last):
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]   File "/opt/indico/htdocs/indico.wsgi", line 20, in <module>
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]     from indico.web.flask.app import make_app
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/indico/web/flask/app.py", line 35, in <module>
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]     from MaKaC.webinterface.pages.error import WErrorWSGI
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/MaKaC/webinterface/pages/error.py", line 20, in <module>
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]     from MaKaC.webinterface.pages.base import WPDecorated
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/MaKaC/webinterface/pages/base.py", line 26, in <module>
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]     import MaKaC.webinterface.wcomponents as wcomponents
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/MaKaC/webinterface/wcomponents.py", line 43, in <module>
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]     from MaKaC import conference
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/MaKaC/conference.py", line 82, in <module>
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]     from MaKaC.evaluation import Evaluation
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/MaKaC/evaluation.py", line 32, in <module>
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]     from indico.modules.scheduler import Client
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/indico/modules/scheduler/__init__.py", line 30, in <module>
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]     from indico.modules.scheduler.server import Scheduler
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/indico/modules/scheduler/server.py", line 30, in <module>
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]     from indico.modules.scheduler.tasks.periodic import PeriodicTask, TaskOccurrence
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/indico/modules/scheduler/tasks/__init__.py", line 28, in <module>
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]     from MaKaC.authentication.LDAPAuthentication import LDAPConnector
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/MaKaC/authentication/LDAPAuthentication.py", line 729
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]      for email in emails
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]        ^
[Tue Oct 13 00:10:35 2015] [error] [client 210.219.52.18]  SyntaxError: invalid syntax
```
2. MaKaC/services/implementation/user.py
```bash
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18] mod_wsgi (pid=3844): Target WSGI script '/opt/indico/htdocs/indico.wsgi' cannot be loaded as Python module.
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18] mod_wsgi (pid=3844): Exception occurred processing WSGI script '/opt/indico/htdocs/indico.wsgi'.
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18] Traceback (most recent call last):
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18]   File "/opt/indico/htdocs/indico.wsgi", line 20, in <module>
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18]     from indico.web.flask.app import make_app
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/indico/web/flask/app.py", line 40, in <module>
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18]     from indico.web.flask.blueprints.rooms import rooms
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/indico/web/flask/blueprints/rooms.py", line 20, in <module>
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18]     from MaKaC.webinterface.rh import roomBooking
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/MaKaC/webinterface/rh/roomBooking.py", line 40, in <module>
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18]     import MaKaC.webinterface.pages.admins as admins
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/MaKaC/webinterface/pages/admins.py", line 60, in <module>
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18]     from MaKaC.services.implementation.user import UserComparator
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18]   File "/usr/lib/python2.6/site-packages/indico-1.2.1rc2-py2.6.egg/MaKaC/services/implementation/user.py", line 383
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18]      if self._dataType in {"surName", "name", "organisation", "email", "secondaryEmails"}:
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18]                                     ^
[Tue Oct 13 00:18:22 2015] [error] [client 210.219.52.18]  SyntaxError: invalid syntax
```
In addition, 

Why this warning occured?

```bash
[Tue Oct 13 00:18:21 2015] [error] /usr/lib/python2.6/site-packages/pkg_resources/__init__.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
```

**Comment by ThiefMaster** [comment]
Since all developers use Python 2.7 (and all future versions of Indico will require Python 2.7) we accidentally merged 2.7-only code into 1.2 (even though that version still supports 2.6).

Of course we'll fix this - but if you have the possibility to use Python 2.7, it'd be a good idea to do so (you *will* need it in the future).

**Comment by geonmo** [comment]
I installed the python2.7 and compile mod_wsgi using new python. 
The Indico is working now. 
Thanks, @ThiefMaster .
However, I want to left this issue for other people who use python2.6.
Can I keep the this issue?

**Comment by ThiefMaster** [comment]
Yes sure, please keep it open.
