### ISSUE TITLE
easy_install ubuntu 16

### ISSUE THREAD

**Issue by vgvassilev** [indico/indico#2416]
Hi,
  I was following the setup instructions here http://indico.readthedocs.io/en/latest/installation/ and I got:
```
easy_install -v indico
Searching for indico
Best match: indico 1.2.1rc5
Processing indico-1.2.1rc5-py2.7.egg
indico 1.2.1rc5 is already the active version in easy-install.pth
[...not interesting...]
Validating md5 checksum for /tmp/easy_install-YbkQBd/cssmin-0.1.4.tar.gz
Processing cssmin-0.1.4.tar.gz
Unpacking cssmin-0.1.4 to /tmp/easy_install-YbkQBd/cssmin-0.1.4
Unpacking cssmin-0.1.4/distribute_setup.py to /tmp/easy_install-YbkQBd/cssmin-0.1.4/distribute_setup.py
Unpacking cssmin-0.1.4/MANIFEST.in to /tmp/easy_install-YbkQBd/cssmin-0.1.4/MANIFEST.in
Unpacking cssmin-0.1.4/PKG-INFO to /tmp/easy_install-YbkQBd/cssmin-0.1.4/PKG-INFO
Unpacking cssmin-0.1.4/setup.cfg to /tmp/easy_install-YbkQBd/cssmin-0.1.4/setup.cfg
Unpacking cssmin-0.1.4/setup.py to /tmp/easy_install-YbkQBd/cssmin-0.1.4/setup.py
Unpacking cssmin-0.1.4/src to /tmp/easy_install-YbkQBd/cssmin-0.1.4/src
Unpacking cssmin-0.1.4/src/cssmin.egg-info to /tmp/easy_install-YbkQBd/cssmin-0.1.4/src/cssmin.egg-info
Unpacking cssmin-0.1.4/src/._cssmin.py to /tmp/easy_install-YbkQBd/cssmin-0.1.4/src/._cssmin.py
Unpacking cssmin-0.1.4/src/cssmin.py to /tmp/easy_install-YbkQBd/cssmin-0.1.4/src/cssmin.py
Unpacking cssmin-0.1.4/src/cssmin.egg-info/dependency_links.txt to /tmp/easy_install-YbkQBd/cssmin-0.1.4/src/cssmin.egg-info/dependency_links.txt
Unpacking cssmin-0.1.4/src/cssmin.egg-info/entry_points.txt to /tmp/easy_install-YbkQBd/cssmin-0.1.4/src/cssmin.egg-info/entry_points.txt
Unpacking cssmin-0.1.4/src/cssmin.egg-info/PKG-INFO to /tmp/easy_install-YbkQBd/cssmin-0.1.4/src/cssmin.egg-info/PKG-INFO
Unpacking cssmin-0.1.4/src/cssmin.egg-info/SOURCES.txt to /tmp/easy_install-YbkQBd/cssmin-0.1.4/src/cssmin.egg-info/SOURCES.txt
Unpacking cssmin-0.1.4/src/cssmin.egg-info/top_level.txt to /tmp/easy_install-YbkQBd/cssmin-0.1.4/src/cssmin.egg-info/top_level.txt
Reading configuration from /tmp/easy_install-YbkQBd/cssmin-0.1.4/setup.cfg
Adding new section [easy_install] to /tmp/easy_install-YbkQBd/cssmin-0.1.4/setup.cfg
Writing /tmp/easy_install-YbkQBd/cssmin-0.1.4/setup.cfg
Running cssmin-0.1.4/setup.py bdist_egg --dist-dir /tmp/easy_install-YbkQBd/cssmin-0.1.4/egg-dist-tmp-wN2imL
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.10.tar.gz
Extracting in /tmp/easy_install-YbkQBd/cssmin-0.1.4/temp/tmp5CpjPm
Now working in /tmp/easy_install-YbkQBd/cssmin-0.1.4/temp/tmp5CpjPm/distribute-0.6.10
Building a Distribute egg in /tmp/easy_install-YbkQBd/cssmin-0.1.4
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    exec(open(init_path).read(), d)
  File "<string>", line 8, in <module>
  File "/tmp/easy_install-YbkQBd/cssmin-0.1.4/temp/tmp5CpjPm/distribute-0.6.10/setuptools/__init__.py", line 2, in <module>
    from setuptools.extension import Extension, Library
  File "/tmp/easy_install-YbkQBd/cssmin-0.1.4/temp/tmp5CpjPm/distribute-0.6.10/setuptools/extension.py", line 2, in <module>
    from setuptools.dist import _get_unpatched
  File "/tmp/easy_install-YbkQBd/cssmin-0.1.4/temp/tmp5CpjPm/distribute-0.6.10/setuptools/dist.py", line 6, in <module>
    from setuptools.command.install import install
  File "/tmp/easy_install-YbkQBd/cssmin-0.1.4/temp/tmp5CpjPm/distribute-0.6.10/setuptools/command/__init__.py", line 8, in <module>
    from setuptools.command import install_scripts
  File "/tmp/easy_install-YbkQBd/cssmin-0.1.4/temp/tmp5CpjPm/distribute-0.6.10/setuptools/command/install_scripts.py", line 3, in <module>
    from pkg_resources import Distribution, PathMetadata, ensure_directory
  File "/tmp/easy_install-YbkQBd/cssmin-0.1.4/temp/tmp5CpjPm/distribute-0.6.10/pkg_resources.py", line 2675, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/tmp/easy_install-YbkQBd/cssmin-0.1.4/temp/tmp5CpjPm/distribute-0.6.10/pkg_resources.py", line 662, in subscribe
    callback(dist)
  File "/tmp/easy_install-YbkQBd/cssmin-0.1.4/temp/tmp5CpjPm/distribute-0.6.10/pkg_resources.py", line 2675, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/tmp/easy_install-YbkQBd/cssmin-0.1.4/temp/tmp5CpjPm/distribute-0.6.10/pkg_resources.py", line 2177, in activate
    self.insert_on(path)
  File "/tmp/easy_install-YbkQBd/cssmin-0.1.4/temp/tmp5CpjPm/distribute-0.6.10/pkg_resources.py", line 2278, in insert_on
    "with distribute. Found one at %s" % str(self.location))
ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/lib/python2.7/dist-packages
/tmp/easy_install-YbkQBd/cssmin-0.1.4/distribute-0.6.10-py2.7.egg
error: Could not build the egg.
```

Trying `pip install indico` ended up in similar situation:
```
[... not interesting...]
Collecting cssmin==0.1.4 (from indico)
  Downloading cssmin-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.10.tar.gz
    Extracting in /tmp/tmpLCDH7s
    Now working in /tmp/tmpLCDH7s/distribute-0.6.10
    Building a Distribute egg in /tmp/pip-build-Odgybl/cssmin
    Traceback (most recent call last):
      File "setup.py", line 37, in <module>
        exec(open(init_path).read(), d)
      File "<string>", line 8, in <module>
      File "/tmp/tmpLCDH7s/distribute-0.6.10/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/tmpLCDH7s/distribute-0.6.10/setuptools/extension.py", line 2, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/tmpLCDH7s/distribute-0.6.10/setuptools/dist.py", line 6, in <module>
        from setuptools.command.install import install
      File "/tmp/tmpLCDH7s/distribute-0.6.10/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/tmp/tmpLCDH7s/distribute-0.6.10/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/tmp/tmpLCDH7s/distribute-0.6.10/pkg_resources.py", line 2675, in <module>
        add_activation_listener(lambda dist: dist.activate())
      File "/tmp/tmpLCDH7s/distribute-0.6.10/pkg_resources.py", line 662, in subscribe
        callback(dist)
      File "/tmp/tmpLCDH7s/distribute-0.6.10/pkg_resources.py", line 2675, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/tmp/tmpLCDH7s/distribute-0.6.10/pkg_resources.py", line 2177, in activate
        self.insert_on(path)
      File "/tmp/tmpLCDH7s/distribute-0.6.10/pkg_resources.py", line 2278, in insert_on
        "with distribute. Found one at %s" % str(self.location))
    ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/lib/python2.7/dist-packages
    /tmp/pip-build-Odgybl/cssmin/distribute-0.6.10-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Odgybl/cssmin/setup.py", line 7, in <module>
        from distribute_setup import use_setuptools; use_setuptools()
      File "distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "distribute_setup.py", line 116, in _build_egg
        raise IOError('Could not build the egg.')
    IOError: Could not build the egg.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Odgybl/cssmin/
```
Some IRC folks suggested `pip install -U setuptools` and afterwards the `pip install indico` succeeded.

It is not clear whether the bug is not in some other package but it definitely affects indico installation. Maybe you could update the installation page.

--Vassil

**Comment by pferreir** [comment]
Seems related to https://github.com/pypa/setuptools/issues/543.

**Comment by kav2k** [comment]
For the record, for `pip install -U setuptools` workaround to work one needs to also remove the distribution-provided version by `apt remove python-setuptools`.

**Comment by ThiefMaster** [comment]
that sounds like a very good way to break the system.. it's best to create a virtualenv, and then inside the virtualenv run `pip install -U pip` and `pip install -U setuptools`

**Comment by kav2k** [comment]
It is a good way to break the system in general. However, here's the whole workaround:

    pip install -U setuptools
    apt remove python-setuptools
    pip install cssmin==0.1.4
    apt install python-setuptools

The problem, at its core, is that 0.1.4 of `cssmin` has a brain-dead `distribute` bundled, that bails out as soon as it finds *.7* version of `setuptools` anywhere, thinking it's 0.7 - when, for Ubuntu 16.04, the first version is detects is 20.7.0 - even if that's not the one that's going to be used, it just happens to be the first scanned.

As soon as that particular check in installation is passed, it's okay to revert the change.

Of course, it would be better if indico pulled a newer version of `cssmin` that doesn't have this bug..

**Comment by Mrlk** [comment]
Thanks a lot.  I use "pip2 install --upgrade setuptools" Fix it.
