### ISSUE TITLE
easy_install indico fails, while pip install indico succeeds

### ISSUE THREAD

**Issue by knightsamar** [indico/indico#2558]
Amazon Linux AMI release 2016.03 with linux kernel 3.14.35-28.38.amzn1.x86_64
easy_install (setuptools v 12.2)
pip version 8.1.2 (which demanded that setuptools be upgraded to 25.1.6)

```
Searching for indico
Best match: indico 1.2.1rc7
Processing indico-1.2.1rc7-py2.7.egg
indico 1.2.1rc7 is already the active version in easy-install.pth
Installing indico_ctl script to /usr/local/bin
Installing indico_admin script to /usr/local/bin
Installing indico_shell script to /usr/local/bin
Installing indico_livesync script to /usr/local/bin
Installing indico_initial_setup script to /usr/local/bin
Installing indico_scheduler script to /usr/local/bin

Using /usr/local/lib/python2.7/site-packages/indico-1.2.1rc7-py2.7.egg
Processing dependencies for indico
Searching for pyScss==1.1.5
Reading https://github.com/indico/indico-fonts/releases/
/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py:2512: PEP440Warning: 'indico (fonts-1.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py:2512: PEP440Warning: 'indico (fonts-1.0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
Reading https://pypi.python.org/simple/pyScss/
Best match: pyScss 1.1.5
Downloading https://pypi.python.org/packages/da/73/ffbbf473c213cf967d148f60a91a1038dcd48082bfff83fd1599a0bc0f76/pyScss-1.1.5.tar.gz#md5=b4100333e89ff704e037ebfecc7da94c
Processing pyScss-1.1.5.tar.gz
Writing /tmp/easy_install-VJgitE/pyScss-1.1.5/setup.cfg
Running pyScss-1.1.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-VJgitE/pyScss-1.1.5/egg-dist-tmp-GeWbzI
Scanning acceleration disabled (_speedups not found)!





Traceback (most recent call last):
  File "/usr/bin/easy_install", line 9, in <module>
    load_entry_point('setuptools==12.2', 'console_scripts', 'easy_install-2.7')()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 2297, in main
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 393, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 642, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 677, in install_item
    self.process_distribution(spec, dists[0], deps, "Using")
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 722, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 799, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1049, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1061, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 642, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 672, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 857, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1085, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1071, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 240, in run_setup
    raise
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 126, in __exit__
    self._saved = UnpickleableException.dump(type, exc)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))

(Last 2 lines repeated 28 times)

MemoryError
```

Shouldn't we be moving to `pip install` already ? :)

**Comment by ThiefMaster** [comment]
> Shouldn't we be moving to pip install already ? :)

Yes, and with 2.0 we will (and at the same time also get rid of all the other small things that make the installation process cumbersome).

**Comment by ThiefMaster** [comment]
`easy_install` is not supported anymore in 2.0
