### ISSUE TITLE
ImportError: No module named sanitizer

### ISSUE THREAD

**Issue by danmichaelo** [indico/indico#2564]
After installing indico using `easy_install` I got

```
mod_wsgi (pid=31701): Target WSGI script '/opt/indico/htdocs/indico.wsgi' cannot be loaded as Python module.
mod_wsgi (pid=31701): Exception occurred processing WSGI script '/opt/indico/htdocs/indico.wsgi'.
Traceback (most recent call last):
  File "/opt/indico/htdocs/indico.wsgi", line 20, in <module>
    from indico.web.flask.app import make_app
  File "/usr/lib/python2.7/site-packages/indico-1.2.1rc7-py2.7.egg/indico/web/flask/app.py", line 35, in <module>
    from MaKaC.webinterface.pages.error import WErrorWSGI
  File "/usr/lib/python2.7/site-packages/indico-1.2.1rc7-py2.7.egg/MaKaC/webinterface/pages/error.py", line 20, in <module>
    from MaKaC.webinterface.pages.base import WPDecorated
  File "/usr/lib/python2.7/site-packages/indico-1.2.1rc7-py2.7.egg/MaKaC/webinterface/pages/base.py", line 26, in <module>
    import MaKaC.webinterface.wcomponents as wcomponents
  File "/usr/lib/python2.7/site-packages/indico-1.2.1rc7-py2.7.egg/MaKaC/webinterface/wcomponents.py", line 43, in <module>
    from MaKaC import conference
  File "/usr/lib/python2.7/site-packages/indico-1.2.1rc7-py2.7.egg/MaKaC/conference.py", line 25, in <module>
    from MaKaC.common.utils import formatDateTime
  File "/usr/lib/python2.7/site-packages/indico-1.2.1rc7-py2.7.egg/MaKaC/common/utils.py", line 54, in <module>
    from indico.util.string import truncate
  File "/usr/lib/python2.7/site-packages/indico-1.2.1rc7-py2.7.egg/indico/util/string.py", line 29, in <module>
    import bleach
  File "/usr/lib/python2.7/site-packages/bleach/__init__.py", line 8, in <module>
    from html5lib.sanitizer import HTMLSanitizer
ImportError: No module named sanitizer
```

Seems like html5lib has been refactored quite a bit, and a workaround was introduced in bleach 1.4.3 (https://github.com/mozilla/bleach/commit/532463ef194be11f2b73af78a65b0016b68000c1), but `easy_install indico` installed bleach 1.4 for me, not 1.4.3.

A requirement for bleach 1.4.3 was actually already introduced in https://github.com/indico/indico/commit/f252ee11b54010f0ac51bb65337e8976ddcc7532, so then I guess installing indico from git master should work. Seems like a good idea to push a new rc soon then, this took me some time to figure out.

**Comment by pferreir** [comment]
That's actually a dependency problem. Installing the latest html5lib (?)
should fix it, IIRC. We'll release a fixed package next week.

**Comment by pferreir** [comment]
v1.2.1rc8 should fix this.
