### ISSUE TITLE
login page smtp error

### ISSUE THREAD

**Issue by anton-z-s** [indico/indico#2636]
I'm trying to use Indico 1.2rc10 inside docker, but run into some problems.
Here is my docker image https://github.com/anton-z-s/indico-docker (checkout master branch)

On login page i get error: Sorry, your request cannot be completed because of an unexpected error on the Indico server
without smtp configured:
cat /var/log/apache2/error.log
```
[Sun Oct 09 05:35:21.517473 2016] [wsgi:warn] [pid 17:tid 140360806754176] mod_wsgi: Compiled for Python/2.7.8.
[Sun Oct 09 05:35:21.517527 2016] [wsgi:warn] [pid 17:tid 140360806754176] mod_wsgi: Runtime using Python/2.7.9.
[Sun Oct 09 05:35:21.520435 2016] [mpm_event:notice] [pid 17:tid 140360806754176] AH00489: Apache/2.4.10 (Debian) mod_wsgi/4.3.0 Python/2.7.9 configured -- resuming normal operations
[Sun Oct 09 05:35:21.520457 2016] [core:notice] [pid 17:tid 140360806754176] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[Sun Oct 09 05:36:15.943837 2016] [wsgi:error] [pid 27:tid 140360708065024] /opt/indico/lib/python2.7/site-packages/setuptools-28.3.0-py2.7.egg/pkg_resources/__init__.py:190: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
[Sun Oct 09 05:36:18.583851 2016] [wsgi:error] [pid 27:tid 140360708065024] Scanning acceleration disabled (_speedups not found)!
[Sun Oct 09 05:36:20.567063 2016] [wsgi:error] [pid 27:tid 140360699672320] Traceback (most recent call last):
[Sun Oct 09 05:36:20.567089 2016] [wsgi:error] [pid 27:tid 140360699672320]   File "/usr/lib/python2.7/logging/handlers.py", line 929, in emit
[Sun Oct 09 05:36:20.567471 2016] [wsgi:error] [pid 27:tid 140360699672320]     smtp = smtplib.SMTP(self.mailhost, port, timeout=self._timeout)
[Sun Oct 09 05:36:20.567490 2016] [wsgi:error] [pid 27:tid 140360699672320]   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
[Sun Oct 09 05:36:20.567782 2016] [wsgi:error] [pid 27:tid 140360699672320]     (code, msg) = self.connect(host, port)
[Sun Oct 09 05:36:20.567793 2016] [wsgi:error] [pid 27:tid 140360699672320]   File "/usr/lib/python2.7/smtplib.py", line 316, in connect
[Sun Oct 09 05:36:20.567808 2016] [wsgi:error] [pid 27:tid 140360699672320]     self.sock = self._get_socket(host, port, self.timeout)
[Sun Oct 09 05:36:20.567815 2016] [wsgi:error] [pid 27:tid 140360699672320]   File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
[Sun Oct 09 05:36:20.567827 2016] [wsgi:error] [pid 27:tid 140360699672320]     return socket.create_connection((host, port), timeout)
[Sun Oct 09 05:36:20.567835 2016] [wsgi:error] [pid 27:tid 140360699672320]   File "/usr/lib/python2.7/socket.py", line 571, in create_connection
[Sun Oct 09 05:36:20.568078 2016] [wsgi:error] [pid 27:tid 140360699672320]     raise err
[Sun Oct 09 05:36:20.568096 2016] [wsgi:error] [pid 27:tid 140360699672320] error: [Errno 111] Connection refused
[Sun Oct 09 05:36:20.568103 2016] [wsgi:error] [pid 27:tid 140360699672320] Logged from file JSContent.py, line 70
[Sun Oct 09 05:36:20.590437 2016] [wsgi:error] [pid 27:tid 140360699672320] Traceback (most recent call last):
[Sun Oct 09 05:36:20.590458 2016] [wsgi:error] [pid 27:tid 140360699672320]   File "/usr/lib/python2.7/logging/handlers.py", line 929, in emit
[Sun Oct 09 05:36:20.590477 2016] [wsgi:error] [pid 27:tid 140360699672320]     smtp = smtplib.SMTP(self.mailhost, port, timeout=self._timeout)
[Sun Oct 09 05:36:20.590486 2016] [wsgi:error] [pid 27:tid 140360699672320]   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
[Sun Oct 09 05:36:20.590501 2016] [wsgi:error] [pid 27:tid 140360699672320]     (code, msg) = self.connect(host, port)
[Sun Oct 09 05:36:20.590509 2016] [wsgi:error] [pid 27:tid 140360699672320]   File "/usr/lib/python2.7/smtplib.py", line 316, in connect
[Sun Oct 09 05:36:20.590524 2016] [wsgi:error] [pid 27:tid 140360699672320]     self.sock = self._get_socket(host, port, self.timeout)
[Sun Oct 09 05:36:20.590532 2016] [wsgi:error] [pid 27:tid 140360699672320]   File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
[Sun Oct 09 05:36:20.590546 2016] [wsgi:error] [pid 27:tid 140360699672320]     return socket.create_connection((host, port), timeout)
[Sun Oct 09 05:36:20.590561 2016] [wsgi:error] [pid 27:tid 140360699672320]   File "/usr/lib/python2.7/socket.py", line 571, in create_connection
[Sun Oct 09 05:36:20.590576 2016] [wsgi:error] [pid 27:tid 140360699672320]     raise err
[Sun Oct 09 05:36:20.590589 2016] [wsgi:error] [pid 27:tid 140360699672320] error: [Errno 111] Connection refused
[Sun Oct 09 05:36:20.590596 2016] [wsgi:error] [pid 27:tid 140360699672320] Logged from file app.py, line 164
[Sun Oct 09 05:36:20.741629 2016] [wsgi:error] [pid 26:tid 140360708065024] /opt/indico/lib/python2.7/site-packages/setuptools-28.3.0-py2.7.egg/pkg_resources/__init__.py:190: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
```

with smtp configured:

```
[Sun Oct 09 03:03:26.797272 2016] [wsgi:warn] [pid 17:tid 139990692624256] mod_wsgi: Compiled for Python/2.7.8.
[Sun Oct 09 03:03:26.797323 2016] [wsgi:warn] [pid 17:tid 139990692624256] mod_wsgi: Runtime using Python/2.7.9.
[Sun Oct 09 03:03:26.800884 2016] [mpm_event:notice] [pid 17:tid 139990692624256] AH00489: Apache/2.4.10 (Debian) mod_wsgi/4.3.0 Python/2.7.9 configured -- resuming normal operations
[Sun Oct 09 03:03:26.800911 2016] [core:notice] [pid 17:tid 139990692624256] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[Sun Oct 09 03:03:41.829045 2016] [wsgi:error] [pid 27:tid 139990593898240] /opt/indico/lib/python2.7/site-packages/setuptools-28.3.0-py2.7.egg/pkg_resources/__init__.py:190: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
[Sun Oct 09 03:03:42.599760 2016] [wsgi:error] [pid 26:tid 139990593898240] /opt/indico/lib/python2.7/site-packages/setuptools-28.3.0-py2.7.egg/pkg_resources/__init__.py:190: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
[Sun Oct 09 03:03:49.517113 2016] [wsgi:error] [pid 26:tid 139990593898240] Traceback (most recent call last):
[Sun Oct 09 03:03:49.517205 2016] [wsgi:error] [pid 26:tid 139990593898240]   File "/usr/lib/python2.7/logging/handlers.py", line 929, in emit
[Sun Oct 09 03:03:49.518267 2016] [wsgi:error] [pid 26:tid 139990593898240]     smtp = smtplib.SMTP(self.mailhost, port, timeout=self._timeout)
[Sun Oct 09 03:03:49.518299 2016] [wsgi:error] [pid 26:tid 139990593898240]   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
[Sun Oct 09 03:03:49.518988 2016] [wsgi:error] [pid 26:tid 139990593898240]     (code, msg) = self.connect(host, port)
[Sun Oct 09 03:03:49.519016 2016] [wsgi:error] [pid 26:tid 139990593898240]   File "/usr/lib/python2.7/smtplib.py", line 317, in connect
[Sun Oct 09 03:03:49.519059 2016] [wsgi:error] [pid 26:tid 139990593898240]     (code, msg) = self.getreply()
[Sun Oct 09 03:03:49.519081 2016] [wsgi:error] [pid 26:tid 139990593898240]   File "/usr/lib/python2.7/smtplib.py", line 365, in getreply
[Sun Oct 09 03:03:49.519115 2016] [wsgi:error] [pid 26:tid 139990593898240]     + str(e))
[Sun Oct 09 03:03:49.519155 2016] [wsgi:error] [pid 26:tid 139990593898240] SMTPServerDisconnected: Connection unexpectedly closed: timed out
[Sun Oct 09 03:03:49.519176 2016] [wsgi:error] [pid 26:tid 139990593898240] Logged from file indexes.py, line 1267
[Sun Oct 09 03:03:50.103524 2016] [wsgi:error] [pid 26:tid 139990593898240] Scanning acceleration disabled (_speedups not found)!
[Sun Oct 09 03:03:57.672562 2016] [wsgi:error] [pid 26:tid 139990585505536] Traceback (most recent call last):
[Sun Oct 09 03:03:57.672649 2016] [wsgi:error] [pid 26:tid 139990585505536]   File "/usr/lib/python2.7/logging/handlers.py", line 929, in emit
[Sun Oct 09 03:03:57.672718 2016] [wsgi:error] [pid 26:tid 139990585505536]     smtp = smtplib.SMTP(self.mailhost, port, timeout=self._timeout)
[Sun Oct 09 03:03:57.672744 2016] [wsgi:error] [pid 26:tid 139990585505536]   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
[Sun Oct 09 03:03:57.672788 2016] [wsgi:error] [pid 26:tid 139990585505536]     (code, msg) = self.connect(host, port)
[Sun Oct 09 03:03:57.672811 2016] [wsgi:error] [pid 26:tid 139990585505536]   File "/usr/lib/python2.7/smtplib.py", line 317, in connect
[Sun Oct 09 03:03:57.672848 2016] [wsgi:error] [pid 26:tid 139990585505536]     (code, msg) = self.getreply()
[Sun Oct 09 03:03:57.672888 2016] [wsgi:error] [pid 26:tid 139990585505536]   File "/usr/lib/python2.7/smtplib.py", line 365, in getreply
[Sun Oct 09 03:03:57.672918 2016] [wsgi:error] [pid 26:tid 139990585505536]     + str(e))
[Sun Oct 09 03:03:57.672959 2016] [wsgi:error] [pid 26:tid 139990585505536] SMTPServerDisconnected: Connection unexpectedly closed: timed out
[Sun Oct 09 03:03:57.672979 2016] [wsgi:error] [pid 26:tid 139990585505536] Logged from file JSContent.py, line 70
[Sun Oct 09 03:04:02.856872 2016] [wsgi:error] [pid 26:tid 139990585505536] Traceback (most recent call last):
[Sun Oct 09 03:04:02.856975 2016] [wsgi:error] [pid 26:tid 139990585505536]   File "/usr/lib/python2.7/logging/handlers.py", line 929, in emit
[Sun Oct 09 03:04:02.857050 2016] [wsgi:error] [pid 26:tid 139990585505536]     smtp = smtplib.SMTP(self.mailhost, port, timeout=self._timeout)
[Sun Oct 09 03:04:02.857073 2016] [wsgi:error] [pid 26:tid 139990585505536]   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
[Sun Oct 09 03:04:02.857108 2016] [wsgi:error] [pid 26:tid 139990585505536]     (code, msg) = self.connect(host, port)
[Sun Oct 09 03:04:02.857129 2016] [wsgi:error] [pid 26:tid 139990585505536]   File "/usr/lib/python2.7/smtplib.py", line 317, in connect
[Sun Oct 09 03:04:02.857161 2016] [wsgi:error] [pid 26:tid 139990585505536]     (code, msg) = self.getreply()
[Sun Oct 09 03:04:02.857181 2016] [wsgi:error] [pid 26:tid 139990585505536]   File "/usr/lib/python2.7/smtplib.py", line 365, in getreply
[Sun Oct 09 03:04:02.857213 2016] [wsgi:error] [pid 26:tid 139990585505536]     + str(e))
[Sun Oct 09 03:04:02.857250 2016] [wsgi:error] [pid 26:tid 139990585505536] SMTPServerDisconnected: Connection unexpectedly closed: timed out
[Sun Oct 09 03:04:02.857268 2016] [wsgi:error] [pid 26:tid 139990585505536] Logged from file app.py, line 164
[Sun Oct 09 03:04:10.746180 2016] [wsgi:error] [pid 27:tid 139990348519168] Traceback (most recent call last):
[Sun Oct 09 03:04:10.746263 2016] [wsgi:error] [pid 27:tid 139990348519168]   File "/usr/lib/python2.7/logging/handlers.py", line 929, in emit
[Sun Oct 09 03:04:10.747070 2016] [wsgi:error] [pid 27:tid 139990348519168]     smtp = smtplib.SMTP(self.mailhost, port, timeout=self._timeout)
[Sun Oct 09 03:04:10.747095 2016] [wsgi:error] [pid 27:tid 139990348519168]   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
[Sun Oct 09 03:04:10.747634 2016] [wsgi:error] [pid 27:tid 139990348519168]     (code, msg) = self.connect(host, port)
[Sun Oct 09 03:04:10.747658 2016] [wsgi:error] [pid 27:tid 139990348519168]   File "/usr/lib/python2.7/smtplib.py", line 317, in connect
[Sun Oct 09 03:04:10.747698 2016] [wsgi:error] [pid 27:tid 139990348519168]     (code, msg) = self.getreply()
[Sun Oct 09 03:04:10.747718 2016] [wsgi:error] [pid 27:tid 139990348519168]   File "/usr/lib/python2.7/smtplib.py", line 365, in getreply
[Sun Oct 09 03:04:10.747757 2016] [wsgi:error] [pid 27:tid 139990348519168]     + str(e))
[Sun Oct 09 03:04:10.747793 2016] [wsgi:error] [pid 27:tid 139990348519168] SMTPServerDisconnected: Connection unexpectedly closed: timed out
[Sun Oct 09 03:04:10.747811 2016] [wsgi:error] [pid 27:tid 139990348519168] Logged from file JSContent.py, line 70
[Sun Oct 09 03:04:15.929909 2016] [wsgi:error] [pid 27:tid 139990348519168] Traceback (most recent call last):
[Sun Oct 09 03:04:15.929992 2016] [wsgi:error] [pid 27:tid 139990348519168]   File "/usr/lib/python2.7/logging/handlers.py", line 929, in emit
[Sun Oct 09 03:04:15.930055 2016] [wsgi:error] [pid 27:tid 139990348519168]     smtp = smtplib.SMTP(self.mailhost, port, timeout=self._timeout)
[Sun Oct 09 03:04:15.930078 2016] [wsgi:error] [pid 27:tid 139990348519168]   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
[Sun Oct 09 03:04:15.930114 2016] [wsgi:error] [pid 27:tid 139990348519168]     (code, msg) = self.connect(host, port)
[Sun Oct 09 03:04:15.930135 2016] [wsgi:error] [pid 27:tid 139990348519168]   File "/usr/lib/python2.7/smtplib.py", line 317, in connect
[Sun Oct 09 03:04:15.930190 2016] [wsgi:error] [pid 27:tid 139990348519168]     (code, msg) = self.getreply()
[Sun Oct 09 03:04:15.930211 2016] [wsgi:error] [pid 27:tid 139990348519168]   File "/usr/lib/python2.7/smtplib.py", line 365, in getreply
[Sun Oct 09 03:04:15.930243 2016] [wsgi:error] [pid 27:tid 139990348519168]     + str(e))
[Sun Oct 09 03:04:15.930279 2016] [wsgi:error] [pid 27:tid 139990348519168] SMTPServerDisconnected: Connection unexpectedly closed: timed out
[Sun Oct 09 03:04:15.930298 2016] [wsgi:error] [pid 27:tid 139990348519168] Logged from file app.py, line 164
```

**Comment by anton-z-s** [comment]
```
python -c “import bcrypt”
apache2ctl restart
```
solved the problem
