### ISSUE TITLE
 nodeenv: not found when compiling from source

### ISSUE THREAD

**Issue by anton-z-s** [indico/indico#2637]
I'm trying to compile Indico 1.9.8 from sources inside docker, but ran into some problems.
Here is my docker image https://github.com/anton-z-s/indico-docker (checkout **compile-from-source** branch)

On `fab setup_deps` i've got
```
Cloning into 'ext_modules/underscore'...
Submodule path 'ext_modules/underscore': checked out 'e4743ab712b8ab42ad4ccb48b155034d02394e4d'
/bin/sh: 1: nodeenv: not found

Warning: local() encountered an error (return code 127) while executing 'nodeenv -c -n 4.2.2 /opt/indico/ext_modules/node_env'

/bin/sh: 1: .: Can't open /opt/indico/ext_modules/node_env/bin/activate

Fatal error: local() encountered an error (return code 2) while executing 'npm install -g grunt-cli'

Aborting.

```

**Comment by OmeGak** [comment]
An obvious question here. Do you have `nodeenv` in the path?

**Comment by anton-z-s** [comment]
No, nodeenv is located in /opt/indico12/bin
Sorry for dumb question, but what should i do?

**Comment by ThiefMaster** [comment]
Did you forget to pip install from requirements.dev.txt? That should install nodeenv.

**Comment by anton-z-s** [comment]
Yes, i did. 
opt/indico12 is virtual env, opt/indico is where sources are stored.
```
RUN cd /opt/indico && /opt/indico12/bin/pip install -r requirements.dev.txt
...
RUN cd /opt/indico && /opt/indico12/bin/fab setup_deps
```

**Comment by ThiefMaster** [comment]
Hm, probably fab setup_deps expects it to be in the PATH.

Try this:

    RUN sh -c 'cd /opt/indico && source /opt/indico12/bin/activate && /opt/indico12/bin/fab setup_deps'

PS: Isn't it usually recommended to *not* use virtualenv when using Docker since you already have a separated environment with the Docker container?

**Comment by anton-z-s** [comment]
thanks for your help, i've managed to compile it, but on first run i got:
```
[Tue Oct 11 01:18:11.113685 2016] [wsgi:warn] [pid 17:tid 140708065896320] mod_wsgi: Compiled for Python/2.7.8.
[Tue Oct 11 01:18:11.113764 2016] [wsgi:warn] [pid 17:tid 140708065896320] mod_wsgi: Runtime using Python/2.7.9.
[Tue Oct 11 01:18:11.117481 2016] [mpm_event:notice] [pid 17:tid 140708065896320] AH00489: Apache/2.4.10 (Debian) mod_wsgi/4.3.0 Python/2.7.9 configured -- resuming normal operations
[Tue Oct 11 01:18:11.117511 2016] [core:notice] [pid 17:tid 140708065896320] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[Tue Oct 11 01:18:59.455736 2016] [wsgi:error] [pid 26:tid 140707876558592] [client 172.17.0.1:49198] mod_wsgi (pid=26): Target WSGI script '/opt/indico/htdocs/indico.wsgi' cannot be loaded as Python module.
[Tue Oct 11 01:18:59.455763 2016] [wsgi:error] [pid 26:tid 140707876558592] [client 172.17.0.1:49198] mod_wsgi (pid=26): Exception occurred processing WSGI script '/opt/indico/htdocs/indico.wsgi'.
[Tue Oct 11 01:18:59.455784 2016] [wsgi:error] [pid 26:tid 140707876558592] [client 172.17.0.1:49198] Traceback (most recent call last):
[Tue Oct 11 01:18:59.455801 2016] [wsgi:error] [pid 26:tid 140707876558592] [client 172.17.0.1:49198]   File "/opt/indico/htdocs/indico.wsgi", line 17, in <module>
[Tue Oct 11 01:18:59.455864 2016] [wsgi:error] [pid 26:tid 140707876558592] [client 172.17.0.1:49198]     from indico.web.flask.app import make_app
[Tue Oct 11 01:18:59.455874 2016] [wsgi:error] [pid 26:tid 140707876558592] [client 172.17.0.1:49198]   File "/opt/indico_venv/lib/python2.7/site-packages/indico-1.9.8-py2.7.egg/indico/web/flask/app.py", line 26, in <module>
[Tue Oct 11 01:18:59.456880 2016] [wsgi:error] [pid 26:tid 140707876558592] [client 172.17.0.1:49198]     from flask_pluginengine import plugins_loaded
[Tue Oct 11 01:18:59.456903 2016] [wsgi:error] [pid 26:tid 140707876558592] [client 172.17.0.1:49198] ImportError: No module named flask_pluginengine

```
venv path specified in apache conf:
`WSGIPythonPath /opt/indico_venv/lib/python2.7/site-packages`
the same configuration worked for precompiled Indico.

**Comment by ThiefMaster** [comment]
flask-pluginengine and flask-multipass are not on PyPI yet so they need to be installed from their git repos. `pip install -r requirements.txt` *should* take care of it though...

https://github.com/indico/indico/blob/master/requirements.txt#L69-L70

**Comment by anton-z-s** [comment]
It compiled successfully, but on login i get error:
```
[Tue Oct 11 15:36:39.952027 2016] [wsgi:warn] [pid 17:tid 139638121748352] mod_wsgi: Compiled for Python/2.7.8.
[Tue Oct 11 15:36:39.952095 2016] [wsgi:warn] [pid 17:tid 139638121748352] mod_wsgi: Runtime using Python/2.7.9.
[Tue Oct 11 15:36:39.955344 2016] [mpm_event:notice] [pid 17:tid 139638121748352] AH00489: Apache/2.4.10 (Debian) mod_wsgi/4.3.0 Python/2.7.9 configured -- resuming normal operations
[Tue Oct 11 15:36:39.955372 2016] [core:notice] [pid 17:tid 139638121748352] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[Tue Oct 11 15:36:52.104170 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700] mod_wsgi (pid=26): Target WSGI script '/opt/indico/htdocs/indico.wsgi' cannot be loaded as Python module.
[Tue Oct 11 15:36:52.104199 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700] mod_wsgi (pid=26): Exception occurred processing WSGI script '/opt/indico/htdocs/indico.wsgi'.
[Tue Oct 11 15:36:52.104221 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700] Traceback (most recent call last):
[Tue Oct 11 15:36:52.104243 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico/htdocs/indico.wsgi", line 17, in <module>
[Tue Oct 11 15:36:52.104323 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from indico.web.flask.app import make_app
[Tue Oct 11 15:36:52.104335 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/indico-1.9.8-py2.7.egg/indico/web/flask/app.py", line 37, in <module>
[Tue Oct 11 15:36:52.104633 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from indico.core.celery import celery
[Tue Oct 11 15:36:52.104642 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/indico-1.9.8-py2.7.egg/indico/core/celery/__init__.py", line 22, in <module>
[Tue Oct 11 15:36:52.104727 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from indico.core.celery.core import IndicoCelery
[Tue Oct 11 15:36:52.104736 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/indico-1.9.8-py2.7.egg/indico/core/celery/core.py", line 35, in <module>
[Tue Oct 11 15:36:52.104864 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from indico.core.plugins import plugin_engine
[Tue Oct 11 15:36:52.104872 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/indico-1.9.8-py2.7.egg/indico/core/plugins/__init__.py", line 36, in <module>
[Tue Oct 11 15:36:52.105039 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from indico.modules.events.settings import EventSettingsProxy
[Tue Oct 11 15:36:52.105048 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/indico-1.9.8-py2.7.egg/indico/modules/events/__init__.py", line 30, in <module>
[Tue Oct 11 15:36:52.105206 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from indico.modules.events.util import notify_pending
[Tue Oct 11 15:36:52.105215 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/indico-1.9.8-py2.7.egg/indico/modules/events/util.py", line 41, in <module>
[Tue Oct 11 15:36:52.105425 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from indico.modules.events.contributions.models.contributions import Contribution
[Tue Oct 11 15:36:52.105435 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/indico-1.9.8-py2.7.egg/indico/modules/events/contributions/__init__.py", line 26, in <module>
[Tue Oct 11 15:36:52.105541 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from indico.modules.events.contributions.models.contributions import Contribution
[Tue Oct 11 15:36:52.105562 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/indico-1.9.8-py2.7.egg/indico/modules/events/contributions/models/contributions.py", line 38, in <module>
[Tue Oct 11 15:36:52.105723 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from indico.modules.events.sessions.util import session_coordinator_priv_enabled
[Tue Oct 11 15:36:52.105732 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/indico-1.9.8-py2.7.egg/indico/modules/events/sessions/__init__.py", line 25, in <module>
[Tue Oct 11 15:36:52.105832 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from indico.modules.events.sessions.util import get_sessions_for_user
[Tue Oct 11 15:36:52.105841 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/indico-1.9.8-py2.7.egg/indico/modules/events/sessions/util.py", line 36, in <module>
[Tue Oct 11 15:36:52.105949 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from MaKaC.PDFinterface.base import PDFBase, Paragraph
[Tue Oct 11 15:36:52.105958 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/indico-1.9.8-py2.7.egg/MaKaC/PDFinterface/base.py", line 41, in <module>
[Tue Oct 11 15:36:52.106247 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from MaKaC.common.TemplateExec import render as tpl_render
[Tue Oct 11 15:36:52.106256 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/indico-1.9.8-py2.7.egg/MaKaC/common/TemplateExec.py", line 32, in <module>
[Tue Oct 11 15:36:52.106433 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from indico.util.mdx_latex import latex_escape
[Tue Oct 11 15:36:52.106441 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/indico-1.9.8-py2.7.egg/indico/util/mdx_latex.py", line 72, in <module>
[Tue Oct 11 15:36:52.106677 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     import requests
[Tue Oct 11 15:36:52.106685 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
[Tue Oct 11 15:36:52.106793 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from .packages.urllib3.contrib import pyopenssl
[Tue Oct 11 15:36:52.106801 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
[Tue Oct 11 15:36:52.106946 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     import OpenSSL.SSL
[Tue Oct 11 15:36:52.106954 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
[Tue Oct 11 15:36:52.107207 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from OpenSSL import rand, crypto, SSL
[Tue Oct 11 15:36:52.107215 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
[Tue Oct 11 15:36:52.107606 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     from OpenSSL._util import (
[Tue Oct 11 15:36:52.107615 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 4, in <module>
[Tue Oct 11 15:36:52.107901 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     binding = Binding()
[Tue Oct 11 15:36:52.107914 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in __init__
[Tue Oct 11 15:36:52.108195 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     self._ensure_ffi_initialized()
[Tue Oct 11 15:36:52.108204 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 113, in _ensure_ffi_initialized
[Tue Oct 11 15:36:52.108220 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     libraries=libraries,
[Tue Oct 11 15:36:52.108227 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/utils.py", line 80, in build_ffi
[Tue Oct 11 15:36:52.108459 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     extra_link_args=extra_link_args,
[Tue Oct 11 15:36:52.108468 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/cffi/api.py", line 437, in verify
[Tue Oct 11 15:36:52.108751 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     lib = self.verifier.load_library()
[Tue Oct 11 15:36:52.108760 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/cffi/verifier.py", line 114, in load_library
[Tue Oct 11 15:36:52.108897 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     return self._load_library()
[Tue Oct 11 15:36:52.108905 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/cffi/verifier.py", line 225, in _load_library
[Tue Oct 11 15:36:52.108919 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     return self._vengine.load_library()
[Tue Oct 11 15:36:52.108926 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/cffi/vengine_cpy.py", line 174, in load_library
[Tue Oct 11 15:36:52.109219 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     lst = list(map(self.ffi._get_cached_btype, lst))
[Tue Oct 11 15:36:52.109228 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/cffi/api.py", line 409, in _get_cached_btype
[Tue Oct 11 15:36:52.109241 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     BType = type.get_cached_btype(self, finishlist)
[Tue Oct 11 15:36:52.109249 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/cffi/model.py", line 61, in get_cached_btype
[Tue Oct 11 15:36:52.109443 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     BType = self.build_backend_type(ffi, finishlist)
[Tue Oct 11 15:36:52.109452 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/cffi/model.py", line 507, in build_backend_type
[Tue Oct 11 15:36:52.109465 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     base_btype = self.build_baseinttype(ffi, finishlist)
[Tue Oct 11 15:36:52.109472 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]   File "/opt/indico_venv/lib/python2.7/site-packages/cffi/model.py", line 525, in build_baseinttype
[Tue Oct 11 15:36:52.109484 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700]     % self._get_c_name())
[Tue Oct 11 15:36:52.109507 2016] [wsgi:error] [pid 26:tid 139637990004480] [client 172.17.0.1:33700] CDefError: 'point_conversion_form_t' has no values explicitly defined: refusing to guess which integer type it is meant to be (unsigned/signed, int/long)

```
People managed to fix it by downgrading cffi, but it raises incompatibility error.

**Comment by anton-z-s** [comment]
fixed by `pip -U cryptography cffi`
