### ISSUE TITLE
While installing indico 1.2. getting error "MaKaCError: Could not generate JSVars"

### ISSUE THREAD

**Issue by pa1kumarv** [indico/indico#2647]
[Uploading indico-15102016.log…]()

016-10-15 19:51:47,393 indico.wsgi - ERROR app.py:164 -- WSGI Exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/indico-1.2-py2.7.egg/indico/web/flask/util.py", line 87, in wrapper
    return obj(None).process(params)
  File "/usr/local/lib/python2.7/dist-packages/indico-1.2-py2.7.egg/MaKaC/webinterface/rh/JSContent.py", line 54, in process
    raise MaKaCError('Could not generate JSVars')
MaKaCError: Could not generate JSVars

Additional information:
Request: 7fcf057be050
URL: https://indico.ino.tifr.res.in/indico/vars.js
Endpoint: misc.JSContent-getVars
Method: GET
Params: {}
User: None
IP: 111.119.238.82
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36
Referer: https://indico.ino.tifr.res.in/indico/

And

I issued the write permissions to "/usr/local/lib/python2.7/dist-packages/bcrypt-1.0.2-py2.7.egg/bcrypt/" but not working with this solution.

**Comment by pa1kumarv** [comment]
Problem Solved.
First we have to grant write permissions on /usr/local/lib/python2.7/dist-packages/bcrypt-1.0.2-py2.7.egg/bcrypt. Thanks to Sebastien Medard from the mailing list! 

Am using old indico.conf file and it contains "AuthenticatorList    = ['Local'] ", Now I used new indico.conf file supplied with indico1.2.

Which solved the issues.
