### ISSUE TITLE
Indico installation leads to a [Errno 13] Permission denied

### ISSUE THREAD

**Issue by pierre-girard-at-uga** [indico/indico#2763]
Hello everybody,

I've just started the installation of indico (indico-1.2.1rc11-py2.7) on a CentOS 7 VM by using easy_install. Once installed, I've got the error below in the httpd logs

`[Tue Dec 13 10:51:06.196619 2016] [:error] [pid 10922] [remote 192.168.56.1:68] mod_wsgi (pid=10922): Target WSGI script '/opt/indico/htdocs/indico.wsgi' cannot be loaded as Python module.
[Tue Dec 13 10:51:06.196644 2016] [:error] [pid 10922] [remote 192.168.56.1:68] mod_wsgi (pid=10922): Exception occurred processing WSGI script '/opt/indico/htdocs/indico.wsgi'.
[Tue Dec 13 10:51:06.196665 2016] [:error] [pid 10922] [remote 192.168.56.1:68] Traceback (most recent call last):
[Tue Dec 13 10:51:06.196668 2016] [:error] [pid 10922] [remote 192.168.56.1:68]   File "/opt/indico/htdocs/indico.wsgi", line 20, in <module>
[Tue Dec 13 10:51:06.196682 2016] [:error] [pid 10922] [remote 192.168.56.1:68]     from indico.web.flask.app import make_app
[Tue Dec 13 10:51:06.196714 2016] [:error] [pid 10922] [remote 192.168.56.1:68]   File "/usr/lib/python2.7/site-packages/indico-1.2.1rc11-py2.7.egg/indico/web/flask/app.py", line 32, in <module>
[Tue Dec 13 10:51:06.196787 2016] [:error] [pid 10922] [remote 192.168.56.1:68]     from MaKaC.common.logger import Logger
[Tue Dec 13 10:51:06.196797 2016] [:error] [pid 10922] [remote 192.168.56.1:68]   File "/usr/lib/python2.7/site-packages/indico-1.2.1rc11-py2.7.egg/MaKaC/common/logger.py", line 266, in <module>
[Tue Dec 13 10:51:06.196873 2016] [:error] [pid 10922] [remote 192.168.56.1:68]     Logger.initialize()
[Tue Dec 13 10:51:06.196884 2016] [:error] [pid 10922] [remote 192.168.56.1:68]   File "/usr/lib/python2.7/site-packages/indico-1.2.1rc11-py2.7.egg/MaKaC/common/logger.py", line 228, in initialize
[Tue Dec 13 10:51:06.196901 2016] [:error] [pid 10922] [remote 192.168.56.1:68]     cls.handlers = LoggerUtils.configFromFile(logConfFilepath, defaultArgs, filters)
[Tue Dec 13 10:51:06.196910 2016] [:error] [pid 10922] [remote 192.168.56.1:68]   File "/usr/lib/python2.7/site-packages/indico-1.2.1rc11-py2.7.egg/MaKaC/common/logger.py", line 133, in configFromFile
[Tue Dec 13 10:51:06.196924 2016] [:error] [pid 10922] [remote 192.168.56.1:68]     handlers = cls._install_handlers(cp, defaultArgs, formatters, filters)
[Tue Dec 13 10:51:06.196932 2016] [:error] [pid 10922] [remote 192.168.56.1:68]   File "/usr/lib/python2.7/site-packages/indico-1.2.1rc11-py2.7.egg/MaKaC/common/logger.py", line 174, in _install_handlers
[Tue Dec 13 10:51:06.196944 2016] [:error] [pid 10922] [remote 192.168.56.1:68]     h = apply(klass, args)
[Tue Dec 13 10:51:06.196952 2016] [:error] [pid 10922] [remote 192.168.56.1:68]   File "/usr/lib64/python2.7/logging/__init__.py", line 902, in __init__
[Tue Dec 13 10:51:06.197266 2016] [:error] [pid 10922] [remote 192.168.56.1:68]     StreamHandler.__init__(self, self._open())
[Tue Dec 13 10:51:06.197277 2016] [:error] [pid 10922] [remote 192.168.56.1:68]   File "/usr/lib64/python2.7/logging/__init__.py", line 925, in _open
[Tue Dec 13 10:51:06.197293 2016] [:error] [pid 10922] [remote 192.168.56.1:68]     stream = open(self.baseFilename, self.mode)
[Tue Dec 13 10:51:06.197310 2016] [:error] [pid 10922] [remote 192.168.56.1:68] IOError: [Errno 13] Permission denied: '/usr/share/httpd/.indico.log'`

AFAIU, it sounds like an attempt to write the logs in the apache's home.
`# getent passwd apache
apache:x:48:48:Apache:/usr/share/httpd:/sbin/nologin`

And then ignoring the configuration files provided in /opt/indico/etc, even if the read rights are ok for apache user:
`# namei -l /opt/indico/etc/*.conf
f: /opt/indico/etc/indico.conf
dr-xr-xr-x root root /
drwxr-xr-x root root opt
drwxr-xr-x root root indico
drwxr-xr-x root root etc
-rw-r--r-- root root indico.conf
f: /opt/indico/etc/logging.conf
dr-xr-xr-x root root /
drwxr-xr-x root root opt
drwxr-xr-x root root indico
drwxr-xr-x root root etc
-rw-r--r-- root root logging.conf
f: /opt/indico/etc/zdctl.conf
dr-xr-xr-x root root /
drwxr-xr-x root root opt
drwxr-xr-x root root indico
drwxr-xr-x root root etc
-rw-r--r-- root root zdctl.conf
f: /opt/indico/etc/zodb.conf
dr-xr-xr-x root root /
drwxr-xr-x root root opt
drwxr-xr-x root root indico
drwxr-xr-x root root etc
-rw-r--r-- root root zodb.conf
`
Any idea ?

Thanks

Pierre

**Comment by pierre-girard-at-uga** [comment]
It seems the problem came from SELINUX. I deactivated it and the problem disappeared.
