### ISSUE TITLE
Error on a fresh installation

### ISSUE THREAD

**Issue by mtorrisi** [indico/indico#2843]
Hello,

I've just completed an indico installation, but I cannot acces it. In the log file inidico.log i can see:
```
2017-02-21 20:56:32,521  ERROR    7f01ad101d10  indico.vars_js            Problem generating vars.js
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1-py2.7.egg/MaKaC/webinterface/rh/JSContent.py", line 65, in _process
    data = templateEngine.render(self._tplFile, self._dict).strip()
  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1-py2.7.egg/MaKaC/common/TemplateExec.py", line 136, in render
    return template.render(**params)
  File "/usr/local/lib/python2.7/dist-packages/Mako-0.9.1-py2.7.egg/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/lib/python2.7/dist-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 807, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/lib/python2.7/dist-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 839, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 865, in _exec_template
    callable_(context, *args, **kwargs)
  File "/opt/indico/tmp/mako_modules/js/vars.js.tpl.py", line 84, in render_body
    authenticators = filter(lambda x: x.id != 'Local', AuthenticatorMgr().getList())
  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1-py2.7.egg/MaKaC/authentication/AuthenticationMgr.py", line 35, in __init__
    raise MaKaCError("Impossible to load %s" % auth)
MaKaCError: Impossible to load Local
2017-02-21 20:56:32,787  ERROR    7f01ad101d10  indico.wsgi               WSGI Exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1-py2.7.egg/indico/web/flask/util.py", line 87, in wrapper
    return obj(None).process(params)
  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1-py2.7.egg/MaKaC/webinterface/rh/JSContent.py", line 54, in process
    raise MaKaCError('Could not generate JSVars')
MaKaCError: Could not generate JSVars
```

I installed indico on a Debian 8 server, python Python 2.7.9

Thanks in advance

**Comment by pferreir** [comment]
Seems like an error in the configuration of your temporary directory (`UploadedFilesTempDir` file). Maybe it doesn't exist or the Apache user can't write in it?

**Comment by ThiefMaster** [comment]
IIRC. "Could not load Local" is usually caused by bcrypt no being importable. Try running `python -c 'import bcrypt'` as root; bcrypt compiles some C code the first  time it's imported which doesn't work when it's installed as root but run as a different user since that user won't be able to write in the package folder.

**Comment by mtorrisi** [comment]
Solved, there was a permission permission problem in folder.
