### ISSUE TITLE
Error running indico_initial_setup

### ISSUE THREAD

**Issue by sfermigier** [indico/indico#2849]
On a Mac, and on Unbuntu 16.04:

```
(indico) fermigier@cell:~$ git clone https://github.com/indico/indico.git indico-git
[OK]
(indico) fermigier@cell:~$ cd indico-git/
(indico) fermigier@cell:~/indico-git$ pip install -e .
[...]
Successfully installed indico
(indico) fermigier@cell:~/indico-git$ indico_
indico_ctl            indico_initial_setup
(indico) fermigier@cell:~/indico-git$ indico_initial_setup
* EGG found at /home/fermigier/indico-git... unconfigured
No previous installation of Indico was found.
Please specify a directory prefix:
[/opt/indico]: /home/fermigier/indico

You now need to configure Indico, by editing indico.conf or letting us do it for you.
At this point you can:

    [c]opy the default values in etc/indico.conf.sample to a new etc/indico.conf
    and continue the installation

    [A]bort the installation in order to inspect etc/indico.conf.sample
    and / or to make your own etc/indico.conf

What do you want to do [c/a]? c
Copying Indico tree...
/home/fermigier/indico-git/MaKaC/consoleScripts/../../bin -> /home/fermigier/indico/bin
/home/fermigier/indico-git/MaKaC/consoleScripts/../../doc -> /home/fermigier/indico/doc
/home/fermigier/indico-git/MaKaC/consoleScripts/../../etc -> /home/fermigier/indico/etc
/home/fermigier/indico-git/MaKaC/consoleScripts/../../htdocs -> /home/fermigier/indico/htdocs
Creating wsgi symlink... /home/fermigier/indico/htdocs/indico.wsgi
Traceback (most recent call last):
  File "/home/fermigier/.virtualenvs/indico/bin/indico_initial_setup", line 11, in <module>
    load_entry_point('indico', 'console_scripts', 'indico_initial_setup')()
  File "/home/fermigier/indico-git/MaKaC/consoleScripts/indicoInitialSetup.py", line 99, in main
    os.symlink(os.path.join(eggDir, 'indico/web/indico.wsgi'), wsgi_file)
OSError: [Errno 2] No such file or directory
```

**Comment by cederom** [comment]
Got the same problem on FreeBSD Python2.7 Virtualenv Indico installed with PIP.

**Comment by ThiefMaster** [comment]
this script does not exist anymore in 2.x
