### ISSUE TITLE
indico db prepare - Type "jsonb" doesn't exist

### ISSUE THREAD

**Issue by SysAd-WI** [indico/indico#2860]
Master-Branch:

indico db prepare

```
Setting the alembic version to HEAD
INFO  [alembic.migration] Context impl PostgresqlImpl.
INFO  [alembic.migration] Will assume transactional DDL.
Creating tables
Traceback (most recent call last):
  File "/var/www/indicoenv/bin/indico", line 11, in <module>
    load_entry_point('indico==1.9.9', 'console_scripts', 'indico')()
  File "/var/www/indicoenv/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/cli/manage.py", line 52, in main
    manager.run()
  File "/var/www/indicoenv/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/var/www/indicoenv/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/var/www/indicoenv/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/var/www/indicoenv/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/cli/database.py", line 80, in prepare
    db.create_all()
  File "/var/www/indicoenv/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 972, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/var/www/indicoenv/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 964, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3848, in create_all
    tables=tables)
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1920, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1529, in _run_visitor
    **kwargs).traverse_single(element)
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 733, in visit_metadata
    _is_metadata_operation=True)
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 767, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
    compiled
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/var/www/indicoenv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 469, in do_execute
    cursor.execute(statement, parameters)
**sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) FEHLER:  Typ »jsonb« existiert nicht
LINE 11:  data JSONB NOT NULL,**
               ^
 [SQL: '\nCREATE TABLE events.vc_room_events (\n\tid SERIAL NOT NULL, \n\tevent_id INTEGER NOT NULL, \n\tvc_room_id INTEGER NOT NULL, \n\tlink_type SMALLINT NOT NULL, \n\tlinked_event_id INTEGER, \n\tsession_block_id INTEGER, \n\tcontribution_id INTEGER, \n\tshow BOOLEAN NOT NULL, \n\tdata JSONB NOT NULL, \n\tCONSTRAINT pk_vc_room_events PRIMARY KEY (id), \n\tCONSTRAINT ck_vc_room_events_valid_event_link CHECK (link_type != 1 OR (contribution_id IS NULL AND session_block_id IS NULL AND linked_event_id IS NOT NULL)), \n\tCONSTRAINT ck_vc_room_events_valid_contribution_link CHECK (link_type != 2 OR (linked_event_id IS NULL AND session_block_id IS NULL AND contribution_id IS NOT NULL)), \n\tCONSTRAINT ck_vc_room_events_valid_block_link CHECK (link_type != 3 OR (contribution_id IS NULL AND linked_event_id IS NULL AND session_block_id IS NOT NULL)), \n\tCONSTRAINT ck_vc_room_events_valid_enum_link_type CHECK (link_type IN (1, 2, 3))\n)\n\n']
```

Any suggestions or workarounds here?

**Comment by ThiefMaster** [comment]
You need at least PostgreSQL 9.4 (if you can use a newer version, even better - but we use 9.4 in production atm so it's guaranteed to work with 9.4).

**Comment by ThiefMaster** [comment]
Also, if you are working with bleeding-edge versions you might want to consider joining our IRC channel (#indico on freenode). For quick questions like this one asking on IRC is usually easier than going through the issue tracker.
