### ISSUE TITLE
LDAP authentification config in  indico.conf

### ISSUE THREAD

**Issue by hmissi** [indico/indico#2864]
Hello ,

First of all i'm very habby to use Indico  (1.9.9) and i love your code !!!!! 

and i still have some problems with LDAP
i have already installed flask-multipass https://gist.github.com/jacquesd/836e566c3b272fc55ac3
and tested my ldap connection with python example/example.py
but no i's not working  with indico

this is my conf

```
#------------------------------------------------------------------------------
# AUTHENTICATION
#------------------------------------------------------------------------------
# If you do not need integration with an existing authentication infrastructure
# such as LDAP, OAuth or a SSO system like Shibboleth, you do not have to set
# anything here. Having local identities enabled is sufficient:
#LocalIdentities = False

# If you do not want people to register Indico accounts on their own you can
# disable that here.  Administrators can still create new indico accounts.
#LocalRegistration = True

# If you want to allow people to register themselves, but approve them before
# their account is actually created, you can enable moderation.
#LocalModeration = False

# When `LocalIdentities` is set to False, a link to an external registration
# page can be configured here:
#ExternalRegistrationURL = ''

# For advanced authentication and user information retrieval, Indico uses the
# Flask-Multipass library, so you can use any registered multipass auth/identity
# provider in Indico.  Using such providers requires additional configuration.
# Please note that the name of an identity provider MUST NOT be changed once
# it has been used, as it is referenced internally. Changing the title is fine
# though.
#
# For documentation on the providers and their config options see the
# documentation of multipass on the following site:
# https://flask-multipass.readthedocs.org/en/latest/
#
# In addition to the settings handled by multipass, you may use the following
# settings:
#
# Auth providers:
# - `default`
#    This must be set to `True` for exactly one form-based authentication
#    provide in case you have more than one form-based provider.  If omitted,
#    the default login form will be for local indico accounts (if enabled).
#
# Identity providers:
# - `default_group_provider`
#   If you have any identity providers which provide groups, it is highly
#   recommended to enable this for exactly one of these providers.  This
#   is extremely important if you migrated an old database and have ACLs
#   which don't contain provider references yet.
# - `trusted_email`
#   If all emails received from the provider are trustworthy, i.e. it is
#   guaranteed that the emails actually belong to the user.  This should
#   be enabled e.g. for corporate SSO systems so people do not have to go
#   through an email verification step the first time they login/signup.
# - `moderated`
#   If set to True, account creation after logging in through this provider
#   requires approval by an Indico administrator.  This results in the same
#   workflow as the `LocalModeration` setting for local identities.
# - `synced_fields`
#   This may be set in no more than one identity provider and enables user
#   data synchronization. Its value should be a set of user attributes that
#   can be synchronized. The following attributes are supported:
#   'first_name', 'last_name', 'affiliation', 'phone', 'address'
#
# Indico uses the following identity info keys from multipass, so you need
# to configure the mappings in your identity providers accordingly:
# 'first_name', 'last_name', 'email', 'affiliation', 'phone', 'address'
# All keys are optional, so if a provider does not contain data for a field,
# you can override `identity_info_keys` and only specify the keys you want.
# However, if a provider does not have at least  'email', external users
# returned by this provider will never show up in search results. Likewise,
# an external user with no email will not appear in search results.
#
# Auth and identity providers with the same name are linked automatically
# unless ProviderMap is specified.  If specified it should be a dictionary
# suitable for the MULTIPASS_PROVIDER_MAP setting of multipass.


AuthProviders = {'my-ldap'}
IdentityProviders = {'my_ldap'}
ProviderMap = {'first_name', 'last_name', 'email', 'affiliation'}




_my_ldap_config = {
    'uri': 'ldap://XXXX:389',
    'bind_dn': 'UID=XXX,OU=XXXX,DC=XXX,DC=fr',
    'bind_password': 'XXX',
    'timeout': 30,
    'verify_cert': False,
    'starttls': False,
    'page_size': 1000,

    'uid': 'uid',
    'user_base': 'OU=people,DC=XXXX,DC=fr',
    'user_filter': '(statutCompte=valide)',

    'gid': 'cn',
    'group_base': 'OU=XXX,DC=XXX,DC=fr',
    'group_filter': '(objectClass=groupOfNames)',
    'member_of_attr': '',
    'ad_group_style': False,
}

MULTIPASS_AUTH_PROVIDERS = {
    'my-ldap': {
        'type': 'ldap',
        'title': 'My Organization LDAP',
        'ldap': _my_ldap_config,
    }
}

MULTIPASS_IDENTITY_PROVIDERS = {
    'my-ldap': {
        'type': 'ldap',
        'ldap': _my_ldap_config,
        'mapping': {
            'first_name': 'givenName',
            'last_name': 'sn',
            'email': 'mail',
            'affiliation': 'eduPersonPrimaryAffiliation'
        }
    }
}

MULTIPASS_PROVIDER_MAP = {
    'my-ldap': 'my-ldap'
}


MULTIPASS_IDENTITY_INFO_KEYS = ['first_name', 'last_name', 'email', 'affiliation']

CeleryBroker = 'redis://unused:password@localhost:6379/0'
DefaultTimezone = 'Europe/Paris'
DefaultLocale = 'fr_FR'
~
```

```

But it's calling the configure_multipass_local i gess the def configure_multipass_local(app) 

 indico celery worker -B
Traceback (most recent call last):
  File "/usr/bin/indico", line 11, in <module>
    load_entry_point('indico==1.9.9', 'console_scripts', 'indico')()
  File "/usr/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/cli/manage.py", line 38, in main
    app = make_app(set_path=True)
  File "/usr/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/web/flask/app.py", line 353, in make_app
    configure_app(app, set_path)
  File "/usr/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/web/flask/app.py", line 98, in configure_app
    configure_multipass(app)
  File "/usr/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/web/flask/app.py", line 131, in configure_multipass
    configure_multipass_local(app)
  File "/usr/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/web/flask/app.py", line 144, in configure_multipass_local
    'default': not any(p.get('default') for p in app.config['MULTIPASS_AUTH_PROVIDERS'].itervalues())
AttributeError: 'set' object has no attribute 'itervalues'

```

**Comment by ThiefMaster** [comment]
You don't (and can't) set the MULTIPASS_* options directly. Instead you put this data in the corresponding indico.conf options:

```python
_my_ldap_config = {
    'uri': 'ldap://XXXX:389',
    'bind_dn': 'UID=XXX,OU=XXXX,DC=XXX,DC=fr',
    'bind_password': 'XXX',
    'timeout': 30,
    'verify_cert': False,
    'starttls': False,
    'page_size': 1000,

    'uid': 'uid',
    'user_base': 'OU=people,DC=XXXX,DC=fr',
    'user_filter': '(statutCompte=valide)',

    'gid': 'cn',
    'group_base': 'OU=XXX,DC=XXX,DC=fr',
    'group_filter': '(objectClass=groupOfNames)',
    'member_of_attr': '',
    'ad_group_style': False,
    }


AuthProviders = {
    'my-ldap': {
        'type': 'ldap',
        'title': 'My Organization LDAP',
        'ldap': _my_ldap_config,
    }
}

IdentityProviders = {
    'my-ldap': {
        'type': 'ldap',
        'ldap': _my_ldap_config,
        'mapping': {
            'first_name': 'givenName',
            'last_name': 'sn',
            'email': 'mail',
            'affiliation': 'eduPersonPrimaryAffiliation'
        }
    }
}

# this could be omitted since it's the default:
ProviderMap = {'my-ldap': 'my-ldap'}
```

**Comment by hmissi** [comment]
now it's work !!!!  thank you :) 👍
