### ISSUE TITLE
Search plugin active but no search engine plugin loaded

### ISSUE THREAD

**Issue by hmissi** [indico/indico#2865]
Hello  :) !
i can't added plugins for indico 
-`git clone https://github.com/indico/indico-plugins.git`
-installed search plugin :` pip install -e .` under search directory
and the plugin tab still empty 
so i added `Plugins = {'search'}` in indico.conf

and now i have this message 

```
/usr/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/core/auth.py:75: UserWarning: There is no default group provider but you have providers with group support. This will break legacy ACLs referencing external groups and room ACLs will use local group IDs.
  warn('There is no default group provider but you have providers with group support. '
Traceback (most recent call last):
  File "/usr/bin/indico", line 11, in <module>
    load_entry_point('indico==1.9.9', 'console_scripts', 'indico')()
  File "/usr/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/cli/manage.py", line 38, in main
    app = make_app(set_path=True)
  File "/usr/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/web/flask/app.py", line 371, in make_app
    if not plugin_engine.load_plugins(app):
  File "/usr/lib/python2.7/site-packages/flask_pluginengine/engine.py", line 52, in load_plugins
    plugins_loaded.send(app)
  File "build/bdist.linux-x86_64/egg/blinker/base.py", line 267, in send
  File "/usr/lib/python2.7/site-packages/flask_pluginengine/util.py", line 194, in wrapped
    return func(*args, **kwargs)
  File "/opt/indico-plugins/search/indico_search/plugin.py", line 51, in _plugins_loaded
    raise RuntimeError('Search plugin active but no search engine plugin loaded')
```

Thank you

**Comment by ThiefMaster** [comment]
You cannot use the search plugin without using a search engine plugin (e.g. `search_invenio`). In this case you probably also want `livesync` and `livesync_invenio` so you can actually send data to the invenio instance (which you'll have to setup separately to use it - it's not part of Indico).

FWIW, in the future we hope to provide a search engine plugin that has tighter integration with Indico, e.g. based on Postgres features or something like ElasticSearch.

**Comment by hmissi** [comment]
i have installed `search `, `search_invenio `, `livesync `and `livesync_invenio` then added
`Plugins = {'livesync_invenio', 'livesync', 'search_invenio', 'search'}` in my indico.conf

```
indico celery worker -B
/usr/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/core/auth.py:75: UserWarning: There is no default group provider but you have providers with group support. This will break legacy ACLs referencing external groups and room ACLs will use local group IDs.
  warn('There is no default group provider but you have providers with group support. '
Running a worker with superuser privileges when the
worker accepts messages serialized with pickle is a very bad idea!

If you really want to continue then you have to set the C_FORCE_ROOT
environment variable (but please think about this before you do).

User information: uid=0 euid=0 gid=0 egid=0
```


but not working 


```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log
```.
and when comment this line
`#Plugins = {'livesync_invenio', 'livesync', 'search_invenio', 'search'}`
indico work but show no plugins 

help please !

**Comment by ThiefMaster** [comment]
Do not run any part of indico as root! The celery worker does not need to run as root.

If you get an Internal Server Error check your indico.log and apache error log for detailed errors.

**Comment by hmissi** [comment]
yes root just for my test server :( 

```
[Sun Mar 05 14:05:17.400404 2017] [:error] [pid 2529] /usr/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/core/auth.py:75: UserWarning: There is no default group provider but you have providers with group support. This will break legacy ACLs referencing external groups and room ACLs will use local group IDs.
[Sun Mar 05 14:05:17.400550 2017] [:error] [pid 2529]   warn('There is no default group provider but you have providers with group support. '
[Sun Mar 05 14:05:21.193739 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX] mod_wsgi (pid=2529): Target WSGI script '/opt/indico/htdocs/indico.wsgi' cannot be loaded as Python module.
[Sun Mar 05 14:05:21.193813 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX] mod_wsgi (pid=2529): Exception occurred processing WSGI script '/opt/indico/htdocs/indico.wsgi'.
[Sun Mar 05 14:05:21.193871 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX] Traceback (most recent call last):
[Sun Mar 05 14:05:21.193928 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/opt/indico/htdocs/indico.wsgi", line 18, in <module>
[Sun Mar 05 14:05:21.194037 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     application = make_app()
[Sun Mar 05 14:05:21.194084 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/usr/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/web/flask/app.py", line 371, in make_app
[Sun Mar 05 14:05:21.194318 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     if not plugin_engine.load_plugins(app):
[Sun Mar 05 14:05:21.194361 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/usr/lib/python2.7/site-packages/flask_pluginengine/engine.py", line 46, in load_plugins
[Sun Mar 05 14:05:21.194481 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     plugins = self._import_plugins(state.app)
[Sun Mar 05 14:05:21.194517 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/usr/lib/python2.7/site-packages/flask_pluginengine/engine.py", line 76, in _import_plugins
[Sun Mar 05 14:05:21.194552 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     plugin_class = entry_point.load()
[Sun Mar 05 14:05:21.194587 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2301, in load
[Sun Mar 05 14:05:21.195347 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     self.require(*args, **kwargs)
[Sun Mar 05 14:05:21.195390 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in require
[Sun Mar 05 14:05:21.195427 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     items = working_set.resolve(reqs, env, installer, extras=self.extras)
[Sun Mar 05 14:05:21.195462 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 862, in resolve
[Sun Mar 05 14:05:21.195511 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     new_requirements = dist.requires(req.extras)[::-1]
[Sun Mar 05 14:05:21.195554 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2568, in requires
[Sun Mar 05 14:05:21.195604 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     dm = self._dep_map
[Sun Mar 05 14:05:21.195638 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2553, in _dep_map
[Sun Mar 05 14:05:21.195691 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     for extra, reqs in split_sections(self._get_metadata(name)):
[Sun Mar 05 14:05:21.195729 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2984, in split_sections
[Sun Mar 05 14:05:21.195775 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     for line in yield_lines(s):
[Sun Mar 05 14:05:21.195814 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2246, in yield_lines
[Sun Mar 05 14:05:21.195858 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     for ss in strs:
[Sun Mar 05 14:05:21.195895 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2582, in _get_metadata
[Sun Mar 05 14:05:21.195937 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     for line in self.get_metadata_lines(name):
[Sun Mar 05 14:05:21.195975 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1472, in get_metadata_lines
[Sun Mar 05 14:05:21.196009 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     return yield_lines(self.get_metadata(name))
[Sun Mar 05 14:05:21.196060 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata
[Sun Mar 05 14:05:21.196111 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     value = self._get(self._fn(self.egg_info, name))
[Sun Mar 05 14:05:21.196157 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1577, in _get
[Sun Mar 05 14:05:21.196211 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX]     with open(path, 'rb') as stream:
[Sun Mar 05 14:05:21.196287 2017] [:error] [pid 2529] [remote XXX.XXX.XXX.XXX] IOError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/zc.queue-1.3-py2.7.egg/EGG-INFO/requires.txt'


```

**Comment by hmissi** [comment]
now it's work after 
`chmod o+r /usr/lib/python2.7/site-packages/zc.queue-1.3-py2.7.egg/EGG-INFO/requires.txt`
