### ISSUE TITLE
BuildError: Could not build url for endpoint 'assets.i18n_locale'. Did you forget to specify values ['locale_name']?

### ISSUE THREAD

**Issue by HostOnNet** [indico/indico#3001]
I am getting following error

```
2017-07-07 20:25:55,733 indico.requestHandler - ERROR decorators.py:121 -- Request finished: BuildError (Could not build url for endpoint 'assets.i18n_locale'. Did you forget to specify values ['locale_name']?)
Traceback (most recent call last):
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/rh/base.py", line 493, in process
    profile_name, res = self._do_process(profile)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/rh/base.py", line 464, in _do_process
    res = self._process()
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/categories/controllers/display.py", line 349, in _process
    upcoming_events=upcoming_events, **params)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/pages/base.py", line 66, in render_template
    return cls(g.rh, *wp_args, **context).display()
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/pages/base.py", line 188, in display
    body=body)
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/opt/indico/.venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/indico/.venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/web/templates/indico_base.html", line 21, in top-level template code
    <script type="text/javascript" src="{{ url_for('assets.i18n_locale', locale_name=session.lang) }}"></script>
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/web/flask/util.py", line 234, in url_for
    url = _url_for(endpoint, **values)
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/opt/indico/.venv/lib/python2.7/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'assets.i18n_locale'. Did you forget to specify values ['locale_name']?
```
Any idea how i fix this ? Where locale_name is set ?

**Comment by ThiefMaster** [comment]
Which indico version is this?

**Comment by HostOnNet** [comment]
@ThiefMaster  

It was installed by someone else, so not sure exact version.  I think latest version, can i find the version from SSH/command line ?

**Comment by ThiefMaster** [comment]
`pip freeze | grep indico` or `indico shell` (it shows the version on top)

**Comment by HostOnNet** [comment]
@ThiefMaster 

version is v1.9.11.dev10 

```
[indico@j314149 ~]$ /opt/indico/.venv/bin/indico shell
Indico v1.9.11.dev10 is ready for your commands
In [1]: 
```

I created a new user, how i make this user admin as i don't have access to first user. I try to check the postgresql DB, but i can't find the users table.

```
[indico@j314149 ~]$ psql
psql (9.6.3)
Type "help" for help.

indico=> \dt
               List of relations
 Schema |         Name         | Type  | Owner  
--------+----------------------+-------+--------
 indico | designer_image_files | table | indico
 indico | designer_templates   | table | indico
 indico | ip_network_groups    | table | indico
 indico | ip_networks          | table | indico
 indico | news                 | table | indico
 indico | reference_types      | table | indico
 indico | settings             | table | indico
 indico | settings_principals  | table | indico
 public | alembic_version      | table | indico
(9 rows)

indico=> select * from users;
ERROR:  relation "users" does not exist
LINE 1: select * from users;
                      ^
indico=> 
```
Is there any command i can run so i made the new user an admin ?

**Comment by ThiefMaster** [comment]
The table is in the `users` schema, i.e. `users.users` - but don't change things in the database directly.

The first user becomes an admin automatically when he's created through the boostrap wizard you get when accessing indico for the first time. But you can make a user an admin with `indico admin user_grant 1` (with 1 being your user id). By the way, this is kind of off-topic here. Better use our IRC channel (#indico on freenode).

**Comment by ThiefMaster** [comment]
And the error you get is weird.

Unless you have bad data stored in the session, `session.lang` comes from this function, which should never return `None` unless someone set `DefaultLocale` in the config file to None... https://github.com/indico/indico/blob/master/indico/util/i18n.py#L215-L247

**Comment by HostOnNet** [comment]
```
[indico@j314149 ~]$ cat .indico.conf | grep -i def
DefaultTimezone = 'Europe/Berlin'
DefaultLocale = 'en_GB'
StorageBackends = {'default': 'fs:/opt/indico/archive'}
AttachmentStorage = 'default'
[indico@j314149 ~]$ 
```

This value get stored in DB ? The problem is only with one user, i created a new user, that have no such problem.

**Comment by ThiefMaster** [comment]
How did you create the user that has the problem?

**Comment by ThiefMaster** [comment]
Check `User.get(1).settings.get('lang')` (replace 1 with the user's ID) in `indico shell`.

**Comment by HostOnNet** [comment]
> How did you create the user that has the problem?

It was created by someone, i am not sure what went wrong.

```
[indico@j314149 ~]$ /opt/indico/.venv/bin/indico shell
Indico v1.9.11.dev10 is ready for your commands
In [1]: User.get(4).settings.get('lang')

In [2]:
```

I just try to set lang  with command

```
[indico@j314149 ~]$ /opt/indico/.venv/bin/indico shell
Indico v1.9.11.dev10 is ready for your commands
In [1]: User.get(4).settings.set('lang', u'en_GB')

In [2]: User.get(4).settings.get('lang')
Out[2]: u'en_GB'

In [3]: 
```

Even after this, login product error

> Could not build url for endpoint 'assets.i18n_locale'. Did you forget to specify values ['locale_name']?

for this user.

Since this error is just for one user, and i am not sure if the guy who created this user done anything wrong, we can ignore this. Thanks for the help.

**Comment by ThiefMaster** [comment]
Well it would be good to know how it happened :) You need to `db.session.commit()` after setting it.

**Comment by HostOnNet** [comment]
> You need to db.session.commit() after setting it.

That fixed the error. Thank you very much, it was helpful, i learned some indico :)

I need help with some plugin install, i will check with IRC channel #indico
