### ISSUE TITLE
BuildError exception when accessing page layout menu (mgt area)

### ISSUE THREAD

**Issue by jouvin** [indico/indico#3009]
Comment
-------
Error that occured when trying to access the "page layout" menu in the management area. This seems to happen for every event.

Traceback
---------

```
Traceback (most recent call last):
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/rh/base.py", line 493, in process
    profile_name, res = self._do_process(profile)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/rh/base.py", line 464, in _do_process
    res = self._process()
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/events/layout/controllers/layout.py", line 53, in _process
    try:
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/events/layout/controllers/layout.py", line 66, in _process_lecture_meeting
    field = field_class(label, validators, description=description, **field_data.get('kwargs', {}))
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/pages/base.py", line 66, in render_template
    return cls(g.rh, *wp_args, **context).display()
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/pages/base.py", line 181, in display
    body = to_unicode(self._display(params))
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/pages/main.py", line 29, in _display
    body = WMainBase(self._getBody(params), self._timezone, self._getNavigationDrawer(),
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/pages/conferences.py", line 325, in _getBody
    body = to_unicode(self._getPageContent(params))
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/pages/base.py", line 93, in _getPageContent
    return self.render_template_func(template, **params)
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/opt/indico/.venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/indico/.venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/events/layout/templates/layout_meeting_lecture.html", line 2, in top-level template code
    {% from 'forms/_form.html' import simple_form, form_rows %}
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/web/templates/layout/base.html", line 1, in top-level template code
    {% block page %}
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/web/templates/layout/base.html", line 47, in block "page"
    {% block content %}{% endblock %}
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/events/layout/templates/layout_meeting_lecture.html", line 17, in block "content"
    formUrl: {{ url_for('.timetable_theme_form', event) | tojson }},
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/web/flask/util.py", line 234, in url_for
    url = _url_for(endpoint, **values)
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/opt/indico/.venv/lib/python2.7/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint u'event_layout.timetable_theme_form' with values [u'confId']. Did you mean u'event_layout.delete_logo' instead?


Request Data
------------
{u'data': {u'get': {},
           u'headers': {u'Accept': u'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
                        u'Accept-Encoding': u'gzip, deflate, br',
                        u'Accept-Language': u'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3',
                        u'Connection': u'keep-alive',
                        u'Cookie': u'indico_session=***',
                        u'Host': u'indico-vm1.lal.in2p3.fr',
                        u'Referer': u'https://indico-vm1.lal.in2p3.fr/event/3992/manage/timetable/',
                        u'Upgrade-Insecure-Requests': u'1',
                        u'User-Agent': u'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0'},
           u'json': None,
           u'post': {},
           u'url': {u'confId': u'3992'}},
 u'endpoint': u'event_layout.index',
 u'id': u'3bdbb5ed1ffc4943',
 u'ip': u'***',
 u'method': u'GET',
 u'referrer': u'https://indico-vm1.lal.in2p3.fr/event/3992/manage/timetable/',
 u'rh': u'RHLayoutEdit',
 u'url': u'https://indico-vm1.lal.in2p3.fr/event/3992/manage/layout/',
 u'user': u'<User(20, jouvin@lal.in2p3.fr): "Michel Jouvin">',
 u'user_agent': u'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0'}
```

**Comment by ThiefMaster** [comment]
> <Michel_> Bingo! I was not aware that uwsgi should be restarted after an Indico update, I just restarted indico-celery... After uwsgi restart, it works!
