### ISSUE TITLE
Error on adding a new Application 

### ISSUE THREAD

**Issue by bpedersen2** [indico/indico#3075]
version: 1.9.11.dev16

Trying to add another Applicationto the APi, I get this backtrace

Traceback
---------
```
Traceback (most recent call last):
  File "/usr/home/indicoadm/indicov2/.indicov2/lib/python2.7/site-packages/indico/legacy/webinterface/rh/base.py", line 493, in process
    profile_name, res = self._do_process(profile)
  File "/usr/home/indicoadm/indicov2/.indicov2/lib/python2.7/site-packages/indico/legacy/webinterface/rh/base.py", line 464, in _do_process
    res = self._process()
  File "/usr/home/indicoadm/indicov2/.indicov2/lib/python2.7/site-packages/indico/modules/oauth/controllers.py", line 132, in _process
    form = ApplicationForm(obj=FormDefaults(is_enabled=True))
  File "/usr/home/indicoadm/indicov2/.indicov2/lib/python2.7/site-packages/indico/web/forms/base.py", line 70, in __call__
    return super(IndicoFormMeta, cls).__call__(*args, **kwargs)
  File "/usr/home/indicoadm/indicov2/.indicov2/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/usr/home/indicoadm/indicov2/.indicov2/lib/python2.7/site-packages/indico/modules/oauth/forms.py", line 63, in __init__
    for field in self.application.system_app_type.enforced_data:
AttributeError: 'NoneType' object has no attribute 'system_app_type'

```

Request Data
```
------------
{u'data': {u'get': {},
           u'headers': {u'Accept': u'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
                        u'Accept-Encoding': u'gzip, deflate',
                        u'Accept-Language': u'en-US,de;q=0.8,de-DE;q=0.5,en;q=0.3',
                        u'Connection': u'keep-alive',
                        u'Content-Length': u'',
                        u'Content-Type': u'',
                        u'Host': u'indico.frm2.tum.de',
                        u'Referer': u'https://indico.frm2.tum.de/admin/apps/',
                        u'User-Agent': u'Mozilla/5.0 (X11; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0'},
           u'json': None,
           u'post': {},
           u'url': {}},
 u'endpoint': u'oauth.app_new',
 u'method': u'GET',
 u'referrer': u'https://indico.frm2.tum.de/admin/apps/',
 u'rh': u'RHOAuthAdminApplicationNew',
 u'url': u'https://indico.frm2.tum.de/admin/apps/new',
 u'user_agent': u'Mozilla/5.0 (X11; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0'}
```

**Comment by ThiefMaster** [comment]
Thanks for spotting this - luckily it's easy to fix.
