### ISSUE TITLE
Instructions for DB migration

### ISSUE THREAD

**Issue by sdspacecowboy** [indico/indico#3078]
Trying to move an indico 2.0 psql database to my production server. 
Used "\! /usr/pgsql-9.6/bin/pg_dump --clean indico -f /tmp/indicoDump.sql" in the dev server
Then "psql -U postgres indico -f /tmp/indicoDump.sql" in the production server

I get "Sorry, your request cannot be completed because of an unexpected error on the Indico server." when I navigate to indico. 

Logger sends me this:

```
2017-09-27 17:45:06,524 indico.requestHandler - ERROR decorators.py:121 -- Request finished: ProgrammingError ((psycopg2.ProgrammingError) column categories.default_ticket_template_id does not exist
LINE 1: ...anagers AS categories_categories_notify_managers, categories...
                                                             ^
 [SQL: 'SELECT categories.categories.event_message AS categories_categories_event_message, categories.categories.description AS categories_categories_description, categories.categories.no_access_contact AS categories_categories_no_access_contact, categories.categories.id AS categories_categories_id, categories.categories.parent_id AS categories_categories_parent_id, categories.categories.is_deleted AS categories_categories_is_deleted, categories.categories.position AS categories_categories_position, categories.categories.visibility AS categories_categories_visibility, categories.categories.icon_metadata AS categories_categories_icon_metadata, categories.categories.logo_metadata AS categories_categories_logo_metadata, categories.categories.timezone AS categories_categories_timezone, categories.categories.default_event_themes AS categories_categories_default_event_themes, categories.categories.event_creation_restricted AS categories_categories_event_creation_restricted, categor
 ies.cate
 gories.event_creation_notification_emails AS categories_categories_event_creation_notification_emails, categories.categories.event_message_mode AS categories_categories_event_message_mode, categories.categories.suggestions_disabled AS categories_categories_suggestions_disabled, categories.categories.notify_managers AS categories_categories_notify_managers, categories.categories.default_ticket_template_id AS categories_categories_default_ticket_template_id, categories.categories.title AS categories_categories_title, categories.categories.protection_mode AS categories_categories_protection_mode, (SELECT count(attachments.attachments.id) AS count_1 \nFROM attachments.attachments JOIN attachments.folders ON attachments.attachments.folder_id = attachments.folders.id \nWHERE NOT attachments.folders.is_deleted AND NOT attachments.attachments.is_deleted AND attachments.folders.category_id = categories.categories.id) AS anon_1, EXISTS (SELECT 1 \nFROM events.events \nWHERE events.eve
 nts.cate
 gory_id = categories.categories.id AND NOT events.events.is_deleted) AS anon_2, categories_1.id AS categories_1_id, categories_1.title AS categories_1_title, categories_1.protection_mode AS categories_1_protection_mode \nFROM categories.categories LEFT OUTER JOIN categories.categories AS categories_1 ON categories_1.parent_id = categories.categories.id AND NOT categories_1.is_deleted \nWHERE categories.categories.is_deleted = false AND categories.categories.id = %(id_1)s ORDER BY categories_1.position'] [parameters: {'id_1': 0}])
Traceback (most recent call last):
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/rh/base.py", line 507, in process
    handle_sqlalchemy_database_error()  # this will re-raise an exception
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/rh/base.py", line 493, in process
    profile_name, res = self._do_process(profile)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/rh/base.py", line 430, in _do_process
    cp_result = self._checkParams()
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/categories/controllers/display.py", line 250, in _checkParams
    RHDisplayCategoryBase._checkParams(self)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/categories/controllers/base.py", line 45, in _checkParams
    self.category = self._get_category(category_id)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/categories/controllers/base.py", line 38, in _get_category
    category = self._category_query.filter_by(id=category_id, is_deleted=False).one_or_none()
  File "/opt/indico/.venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)
  File "/opt/indico/.venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/opt/indico/.venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/indico/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/opt/indico/.venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/indico/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/indico/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/opt/indico/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/opt/indico/.venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/indico/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/opt/indico/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) column categories.default_ticket_template_id does not exist
LINE 1: ...anagers AS categories_categories_notify_managers, categories...
                                                             ^
 [SQL: 'SELECT categories.categories.event_message AS categories_categories_event_message, ...
```

**Comment by ThiefMaster** [comment]
It's impossible to know what went wrong without seeing the output from restoring your dump. However, we recommend this for creating a dump (`-Fc` uses a postgres-specific format that is more compact and efficient):

     pg_dump -Fc -f /tmp/indico.dump indico

And this to restore:

    su - postgres -c 'createdb -O indico indico'
    su - postgres -c 'psql indico -c "CREATE EXTENSION unaccent; CREATE EXTENSION pg_trgm;"'

Then, as the indico user:

    pg_restore -d indico -O /tmp/indico.dump

**Comment by ThiefMaster** [comment]
This means you installed a newer version than you had before. Like after any [upgrade][1] you need to run `indico db upgrade` to apply database structure changes.

[1]: https://docs.getindico.io/en/latest/installation/upgrade/
