### ISSUE TITLE
Error Deploy Heroku/GitHub

### ISSUE THREAD

**Issue by eliasdesousa** [indico/indico#3099]
I am try make the deploy of repository  with Heroku, but receive the next error:

```
> -----> Python app detected
>  !     Warning: Your application is missing a Procfile. This file tells Heroku how to run your application.
>  !     Learn more: https://devcenter.heroku.com/articles/procfile
> -----> Installing python-3.6.2
> -----> Installing pip
> -----> Installing requirements with pip
>        Collecting Babel==2.5.1 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 1))
>          Downloading Babel-2.5.1-py2.py3-none-any.whl (6.8MB)
>        Collecting Mako==1.0.7 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 2))
>          Downloading Mako-1.0.7.tar.gz (564kB)
>        Collecting MarkupSafe==1.0 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 3))
>          Downloading MarkupSafe-1.0.tar.gz
>        Collecting indico-fonts==1.1 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 4))
>          Downloading indico_fonts-1.1-py2.py3-none-any.whl (25.6MB)
>        Collecting csscompressor==0.9.4 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 5))
>          Downloading csscompressor-0.9.4.tar.gz (237kB)
>        Collecting icalendar==3.11.7 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 6))
>          Downloading icalendar-3.11.7-py2.py3-none-any.whl (77kB)
>        Collecting jsmin==2.2.2 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 7))
>          Downloading jsmin-2.2.2.tar.gz
>        Collecting lxml==4.0.0 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 8))
>          Downloading lxml-4.0.0-cp36-cp36m-manylinux1_x86_64.whl (5.3MB)
>        Collecting pojson==0.7 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 9))
>          Downloading pojson-0.7.zip
>        Collecting pyPdf==1.13 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 10))
>          Downloading pyPdf-1.13.tar.gz
>        Collecting pyatom==1.4 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 11))
>          Downloading pyatom-1.4.tar.gz
>        Collecting pycountry==17.9.23 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 12))
>          Downloading pycountry-17.9.23.tar.gz (9.2MB)
>        Collecting mock==2.0.0 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 13))
>          Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
>        Collecting freezegun==0.3.9 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 14))
>          Downloading freezegun-0.3.9-py2.py3-none-any.whl
>        Collecting pytest==3.2.3 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 15))
>          Downloading pytest-3.2.3-py2.py3-none-any.whl (187kB)
>        Collecting pytest-catchlog==1.2.2 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 16))
>          Downloading pytest_catchlog-1.2.2-py2.py3-none-any.whl
>        Collecting pytest-cov==2.5.1 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 17))
>          Downloading pytest_cov-2.5.1-py2.py3-none-any.whl
>        Collecting pytest-localserver==0.3.7 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 18))
>          Downloading pytest-localserver-0.3.7.tar.gz
>        Collecting pytest-mock==1.6.3 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 19))
>          Downloading pytest_mock-1.6.3-py2.py3-none-any.whl
>        Collecting python-dateutil==2.6.1 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 20))
>          Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
>        Collecting pytz (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 21))
>          Downloading pytz-2017.2-py2.py3-none-any.whl (484kB)
>        Collecting reportlab==3.4.0 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 22))
>          Downloading reportlab-3.4.0-cp36-cp36m-manylinux1_x86_64.whl (3.7MB)
>        Collecting simplejson==3.11.1 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 23))
>          Downloading simplejson-3.11.1.tar.gz (78kB)
>        Collecting termcolor==1.1.0 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 24))
>          Downloading termcolor-1.1.0.tar.gz
>        Collecting webassets==0.12.1 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 25))
>          Downloading webassets-0.12.1.tar.gz (179kB)
>        Collecting wsgiref==0.1.2 (from -r /tmp/build_f75d2ca278ee9775529ad58972827cf7/eliasdesousa-indico-ab98259/requirements.txt (line 26))
>          Downloading wsgiref-0.1.2.zip
>            Complete output from command python setup.py egg_info:
>            Traceback (most recent call last):
>              File "<string>", line 1, in <module>
>              File "/tmp/pip-build-2gctlmv2/wsgiref/setup.py", line 5, in <module>
>                import ez_setup
>              File "/tmp/pip-build-2gctlmv2/wsgiref/ez_setup/__init__.py", line 170
>                print "Setuptools version",version,"or greater has been installed."
>                                         ^
>            SyntaxError: Missing parentheses in call to 'print'
>            
>            ----------------------------------------
>        Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2gctlmv2/wsgiref/
>  !     Push rejected, failed to compile Python app.
>  !     Push failed
```

Somebody can help?

How i can install "Indico" in Cloud?

**Comment by ThiefMaster** [comment]
Indico uses Python 2.7; your deployment script seems to be using Python 3. Also, I doubt you can run something as complex as Indico (it needs e.g. the celery worker process) *that* easily on heroku.

FWIW, we intend to provide a Docker image in the future. This will make cloud deployment much easier, but I don't think Heroku supports Docker...

**Comment by eliasdesousa** [comment]
Understand! Tranks!

I am Brazilian and work to office of human rigths of governament. Recently knew the Indico through https://reg.unog.ch/!

I'm not developer, but wish to test the features of tool or contribute to a translation in portuguese (pt_BR).

**Comment by pferreir** [comment]
@eliasdesousa, if you wish to help with the translation, [this](https://talk.getindico.io/t/portuguese-pt-translation-group/37/3) is the place to get started:
