### ISSUE TITLE
db upgrade after upgrade to 2.0.a1 failed

### ISSUE THREAD

**Issue by drosskopp** [indico/indico#3123]
```
(.venv) indico@indico-test:~$ indico db upgrade
/opt/indico/.venv/local/lib/python2.7/site-packages/indico/core/config.py:181: UserWarning: Ignoring unknown config key CHECKIN_APP_CLIENT_ID
  warnings.warn('Ignoring unknown config key {}'.format(key))
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "/opt/indico/.venv/bin/indico", line 11, in <module>
    sys.exit(cli())
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/cli/util.py", line 119, in invoke
    return self._impl.invoke(ctx)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/cli/database.py", line 148, in _call_with_plugins
    func(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/migrations/env.py", line 83, in <module>
    run_migrations_online()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/migrations/env.py", line 75, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 321, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/command.py", line 243, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 338, in _upgrade_revs
    for script in reversed(list(revs))
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 174, in _catch_revision_errors
    compat.raise_from_cause(util.CommandError(resolution))
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/util/compat.py", line 205, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 143, in _catch_revision_errors
    yield
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 334, in _upgrade_revs
    revs = list(revs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/script/revision.py", line 645, in _iterate_revisions
    requested_lowers = self.get_revisions(lower)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/script/revision.py", line 299, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/script/revision.py", line 304, in get_revisions
    for rev_id in resolved_id)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/script/revision.py", line 304, in <genexpr>
    for rev_id in resolved_id)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/alembic/script/revision.py", line 362, in _revision_for_ident
    resolved_id)
alembic.util.exc.CommandError: Can't locate revision identified by '65c079b091bf'
```

**Comment by ThiefMaster** [comment]
After updating to 2.0, the command to run is `indico db reset_alembic`. You do not need to run `indico db upgrade` at this point.

Also, if you have a checkin oauth app configured (which seems likely since you have a `CheckinAppClientId` in your indico.conf), it is a good idea to use this command when upgrading to the latest `1.9.11.dev17`:

    indico db upgrade -x checkin_app_id=00000000-dead-c0de-beef-000000001111

Replace `00000000-dead-c0de-beef-000000001111` with your `CheckinAppClientId`, and then remove that option since it's obsolete.

If you already upgraded to 2.0 or 1.9.11.dev17 without using that extra option to `indico db upgrade`, you might have two checkin oauth apps now. You can safely delete the old one (the new one cannot be deleted). Note that you will need to scan the event QR code again if you are currently doing a checkin process!
