### ISSUE TITLE
Unexpected Exception occurred generating PDFs

### ISSUE THREAD

**Issue by sdspacecowboy** [indico/indico#3147]
Already have xelatex installed. 

Have the following in my conf file:
PDFLatexProgram = '/bin/xelatex'
StrictLatex = False

Every time I try to generate pdfs I get hit with the following error. Any Ideas?

```
2017-11-09 14:09:30,118  ERROR    f6a58094eb094194  indico.requestHandler     Request finished: LaTeXRuntimeException (LaTeX compilation of /opt/indico/tmp/indico-texgen-iJaUN1/single_doc.tpl.tex failed)
Traceback (most recent call last):
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/rh/base.py", line 493, in process
    profile_name, res = self._do_process(profile)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/rh/base.py", line 464, in _do_process
    res = self._process()
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/events/abstracts/controllers/abstract.py", line 96, in _process
    return send_file(filename, pdf.generate(), 'application/pdf')
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/pdfinterface/base.py", line 685, in generate
    pdffile = latex.run(self._tpl_filename, **self._args)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/pdfinterface/base.py", line 751, in run
    raise LaTeXRuntimeException(source_filename, log_filename)
LaTeXRuntimeException: LaTeX compilation of /opt/indico/tmp/indico-texgen-iJaUN1/single_doc.tpl.tex failed
```

**Comment by ThiefMaster** [comment]
Which indico version is that?

Anyway, check the logfile in `/opt/indico/tmp/indico-texgen-iJaUN1/`; it may contain some useful details.

**Comment by sdspacecowboy** [comment]
Thanks for the speedy reply.

This is indico version 1.9.11.dev15

The /opt/indico/tmp/indico-texgen-iJaUN1/output.log says that it can't find truncate.sty.

**Comment by ThiefMaster** [comment]
You should upgrade soon :) Anyway, sounds like you need to install additional texlive packages. Using your distro's `-full` version will probably do the job.

**Comment by sdspacecowboy** [comment]
Yeah. I put it in my calendar.  Just need the sys admin to sign off on it. X(
I think Centos 7 -full version doesn't come with truncate.sty for some reason. Downloaded it manually. Know where I should put it?

**Comment by ThiefMaster** [comment]
Use tlmgr to install it.

**Comment by pferreir** [comment]
We should probably write a guide on how to configure texlive...

**Comment by sdspacecowboy** [comment]
@ThiefMaster Already did `yum install texlive*`. No luck.

**Comment by ThiefMaster** [comment]
Installing texlive manually using [this profile](https://github.com/indico/indico/issues/3003#issuecomment-316355880) would be an option. That's actually what we do for our own instances.

**Comment by ThiefMaster** [comment]
We now have documentation on how to setup a working texlive installation manually: https://docs.getindico.io/en/latest/installation/latex/
