### ISSUE TITLE
Tons of Emails

### ISSUE THREAD

**Issue by sdspacecowboy** [indico/indico#3167]
Hey guys. My admin is complaining about the number of emails indico sends when we run our security scans. Is there a way to turn off all the emails?

**Comment by mic4ael** [comment]
What is the source of the emails? Are those error reports? What version of Indico are you using?

**Comment by ThiefMaster** [comment]
You can edit `/opt/indico/etc/logging.yaml` and remove the `email` handler from the `indico` logger ([this line](https://github.com/indico/indico/blob/master/indico/logging.yaml.sample#L30)).

However, it would be helpful if you actually included the tracebacks from exceptions caused by security scans in here. While it's usually harmless background noise, we may want to catch some errors so they don't even trigger an email.

**Comment by sdspacecowboy** [comment]
I'm on version 1.9.11.dev15 so I don't have a logging.yaml . There is a logging.conf file.

All of the errors are cause by our web scanner (netsparker) when it puts bad character into a field. Mostly noise but it all the emails are clogging the email server.

An example of most of the emails:
2017-11-02 12:56:52,513 indico.wsgi - ERROR app.py:325 -- expected only letters, got u'https://fusion'
Traceback (most recent call last):
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/web/flask/util.py", line 120, in wrapper
    return obj().process(params)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/rh/base.py", line 511, in process
    res = self._getMethodByExceptionName(e)(e)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/util/decorators.py", line 132, in wrapper
    return f(*args, **kw)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/rh/base.py", line 334, in _processUnexpectedError
    return WPUnexpectedError(self).display()
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/pages/base.py", line 181, in display
    body = to_unicode(self._display(params))
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/pages/base.py", line 207, in _display
    return self._applyDecoration(self._getBody(params))
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/pages/errors.py", line 155, in _getBody
    return wc.getHTML()
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/wcomponents.py", line 112, in getHTML
    return render_mako(self.tplFile, vars, self)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/common/TemplateExec.py", line 108, in render
    return template.render(**params)
  File "/opt/indico/.venv/lib/python2.7/site-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/opt/indico/.venv/lib/python2.7/site-packages/mako/runtime.py", line 807, in _render
    **_kwargs_for_callable(callable_, data))
  File "/opt/indico/.venv/lib/python2.7/site-packages/mako/runtime.py", line 839, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/opt/indico/.venv/lib/python2.7/site-packages/mako/runtime.py", line 865, in _exec_template
    callable_(context, *args, **kwargs)
  File "/opt/indico/tmp/mako_modules/UnexpectedError.tpl.py", line 40, in render_body
    __M_writer(str(encode_if_unicode( _("Sorry, your request cannot be completed because of an unexpected error on the Indico server."))))
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/util/i18n.py", line 111, in _wrap
    **kwargs)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/util/i18n.py", line 75, in gettext_unicode
    translations = get_translation_domain(plugin_name).get_translations()
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask_babelex/__init__.py", line 510, in get_translations
    locale = get_locale()
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask_babelex/__init__.py", line 224, in get_locale
    locale = babel.load_locale(rv)
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask_babelex/__init__.py", line 198, in load_locale
    self._locale_cache[locale] = rv = Locale.parse(locale)
  File "/opt/indico/.venv/lib/python2.7/site-packages/babel/core.py", line 267, in parse
    parts = parse_locale(identifier, sep=sep)
  File "/opt/indico/.venv/lib/python2.7/site-packages/babel/core.py", line 1093, in parse_locale
    raise ValueError('expected only letters, got %r' % lang)
ValueError: expected only letters, got u'https://fusion'


Request data:

{u'data': {u'get': {},
           u'headers': {'Accept': u'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
                        'Accept-Encoding': u'gzip, deflate',
                        'Accept-Language': u'en-us,en;q=0.5',
                        'Cache-Control': u'no-cache',
                        'Content-Length': u'84',
                        'Content-Type': u'application/x-www-form-urlencoded',
                        'Cookie': u'indico_session=56730756-9a67-48ea-9f45-0e063942598e',
                        'Host': u'fusion.gat.com',
                        'Referer': u'https://fusion.gat.com/conference/event/60/',
                        'User-Agent': u'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.16 Safari/537.36',
                        'X-Scanner': u'Netsparker'},
           u'json': None,
           u'post': {'accessKey': u'N3tsp@rker-',
                     'csrf_token': u'//r87.com/?http://fusion.gat.com/'},
           u'url': {'confId': u'60'}},
 u'endpoint': u'event.conferenceDisplay-accessKey',
 u'id': '6f469262600f4ea3',
 u'ip': '192.5.166.188',
 u'method': 'POST',
 u'referrer': 'https://fusion.gat.com/conference/event/60/',
 u'rh': 'RHConferenceAccessKey',
 u'url': u'https://fusion.gat.com/conference/event/60/accesskey',
 u'user': 'None',
 u'user_agent': u'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.16 Safari/537.36'}

**Comment by ThiefMaster** [comment]
You really need to upgrade... anyway, logging.conf lets you do the same, it just uses a different syntax...
