### ISSUE TITLE
BOA error but output.log is empty

### ISSUE THREAD

**Issue by hormiai76** [indico/indico#3226]
```
2018-02-02 09:18:14,646  WARNING  47db72677d2c4215  indico.pdflatex           PDF creation possibly failed (non-zero exit code)!
2018-02-02 09:18:14,653  WARNING  47db72677d2c4215  indico.pdflatex           PDF creation possibly failed (non-zero exit code)!
2018-02-02 09:18:14,679  ERROR    47db72677d2c4215  indico.flask              Impossible to compile '/opt/indico/tmp/indico-texgen-EGDUSA/book_of_abstracts.tpl.tex'. Read '/opt/indico/tmp/indico-texgen-EGDUSA/output.log' for details
Traceback (most recent call last):
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/flask/util.py", line 114, in wrapper
    return obj().process()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/rh.py", line 270, in process
    res = self._do_process()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/events/controllers/base.py", line 63, in _do_process
    return RHEventBase._do_process(self)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/rh.py", line 249, in _do_process
    return self._process()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/events/abstracts/controllers/boa.py", line 48, in _process
    return send_file('book-of-abstracts.pdf', create_boa(self.event), 'application/pdf')
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/events/abstracts/util.py", line 299, in create_boa
    tmp_path = pdf.generate()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/legacy/pdfinterface/base.py", line 683, in generate
    pdffile = latex.run(self._tpl_filename, **self._args)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/legacy/pdfinterface/base.py", line 749, in run
    raise LaTeXRuntimeException(source_filename, log_filename)
LaTeXRuntimeException: LaTeX compilation of /opt/indico/tmp/indico-texgen-EGDUSA/book_of_abstracts.tpl.tex failed
```

**Comment by ThiefMaster** [comment]
Please check `/opt/indico/tmp/indico-texgen-EGDUSA/output.log` for the LaTeX output. You may want to include the `.tex` file from the same folder as well if you cannot see what's the problem from that log file.

**Comment by hormiai76** [comment]
The output.log is empty :(
[book_of_abstracts.tpl.tex.zip](https://github.com/indico/indico/files/1688562/book_of_abstracts.tpl.tex.zip)

**Comment by ThiefMaster** [comment]
Worked fine for me when trying it on my dev machine:

    /opt/texlive/bin/x86_64-linux/xelatex -no-shell-escape -interaction nonstopmode book_of_abstracts.tpl.tex

So I'd check whether indico can actually run xelatex (check whether `XELATEX_PATH` in indico.conf is correct), and maybe also try running it manually.

**Comment by hormiai76** [comment]
I reinstalled xelatex and now the output.log is not empty!
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017) (preloaded format=xelatex)
I can't find the format file `xelatex.fmt'!

**Comment by ThiefMaster** [comment]
Did you install it using this guide? Otherwise some of the required packages may be missing.

https://docs.getindico.io/en/latest/installation/latex/

**Comment by hormiai76** [comment]
I reinstalled latex and now it works fine and the BOA is generated. However I'm pretty sure I installed the previous latex following the installation guide... 
I removed the zip file becasue it contains data I'm not sure I can publish
Thank you

**Comment by ThiefMaster** [comment]
Very strange...

BTW, next time feel free to email such data to our team mailing list (indico-team at cern.ch) instead of adding it to the GitHub issue if you don't know for sure whether it's publishable or not. In such a case we'd use the data only for testing and delete it right afterwards, without sharing it outside the team.

Anyway, if that particular event was public, anyone can get the BoA anyway by just accessing the URL, so the risk of disclosing protected data via the latex file is low.
