### ISSUE TITLE
User in ldap group, not given access to category.

### ISSUE THREAD

**Issue by gholman** [indico/indico#3276]
# Error: TypeError: 'NoneType' object is not iterable

Behavior:  LDAP group members receive error when accessing categories are protected with LDAP group (that they are a member of).

I am running:
    Server default language (en_GB)
    Indico version installed (2.0.2)
    Python version used (2.7.12)
    Postgres version used (9.6.8)
    Operating system used (Linux Ubuntu 16.04)
    Debug mode (disabled)
    Basic statistics (number of events, contributions and users)
    OpenLDAP 

My category is protected with LDAP external group, A user can successfully log in, however when they attempt to access the protected category, it results in the NoneType error.  

If I change the protection and  explicitly add the user's name as user, they can access as expected.
If I search/group members in the external Group 'https://.../admin/groups/ldap/(Group Name) the users are indeed listed.

Originally the system only had local users.  When we converted to LDAP, existing user accounts were mapped on login to local accounts.  I suspect there is something wrong with this step in new accounts.

logs - IP and emails removed.
```
2018-03-26 13:51:41,453  INFO     60c7493125434dbc  indico.auth               Received identity info: <IdentityInfo(<LDAPIdentityProvider(ldap)>,*@*, address=None, affiliation=None, email=u'*@*', first_name=u'test', last_name=u'user', phone=None)>
2018-03-26 13:51:41,463  INFO     60c7493125434dbc  indico.auth               Found existing identity <Identity(218, 162, ldap,*@*)> for user <User(162, *@*): "test user">
2018-03-26 13:51:41,544  INFO     778433e1dd9141b2  indico.rh                 GET /category/1/manage/protection [IP=*.*.*.*] [PID=22641] [UID=162]
2018-03-26 13:51:52,180  INFO     58e0dacac6154494  indico.rh                 GET / [IP=*.*.*.*] [PID=22641] [UID=162]
2018-03-26 13:51:52,794  INFO     085835ba1b134afb  indico.rh                 GET /category/0/subcat-info [IP=*.*.*.*] [PID=22641] [UID=162]
2018-03-26 13:51:56,493  INFO     b12a1aab37044986  indico.rh                 GET /category/1/ [IP=*.*.*.*] [PID=22641] [UID=162]
2018-03-26 13:51:56,525  ERROR    b12a1aab37044986  indico.flask              'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/flask/util.py", line 114, in wrapper
    return obj().process()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/rh.py", line 270, in process
    res = self._do_process()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/rh.py", line 239, in _do_process
    self._check_access()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/categories/controllers/base.py", line 54, in _check_access
    if not self.category.can_access(session.user):
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/util/caching.py", line 67, in memoizer
    cache[key] = f(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/core/db/sqlalchemy/protection.py", line 186, in can_access
    if any(user in entry.principal for entry in iter_acl(self.acl_entries)):
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/core/db/sqlalchemy/protection.py", line 186, in <genexpr>
    if any(user in entry.principal for entry in iter_acl(self.acl_entries)):
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/groups/core.py", line 78, in __contains__
    return self.has_member(user)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/groups/core.py", line 247, in has_member
    rv = any(x[1] in self.group for x in user.iter_identifiers(check_providers=True, providers={self.provider}))
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/groups/core.py", line 247, in <genexpr>
    rv = any(x[1] in self.group for x in user.iter_identifiers(check_providers=True, providers={self.provider}))
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask_multipass/group.py", line 55, in __contains__
    return self.has_member(identifier)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask_multipass/providers/ldap/providers.py", line 135, in has_member
    return any(group_sid in token_groups for group_sid in group_sids)
TypeError: 'NoneType' object is not iterable
2
```

**Comment by ThiefMaster** [comment]
Sounds like something is wrong with your LDAP config (in indico.conf) related to groups. Please post the relevant parts.

**Comment by gholman** [comment]
```
_ldap_config = {
    'uri': 'ldap://XXX',
    'bind_dn': 'cn=XXX,dc=XXX,dc=XXX',
    'bind_password': 'XXX,
    'timeout': 30,
    'verify_cert': True,
    'page_size': 1500,

    'uid': 'mail',
    'user_base': 'ou=XXX,dc=XXX,dc=XXX',

    'gid': 'cn',
    'group_base': 'ou=XXX,dc=XXX,dc=XXX',
    'member_of_attr': 'memberOf',
    'ad_group_style': True
}


AUTH_PROVIDERS = {
    'ldap': {
        'type': 'ldap',
        'title': 'LDAP',
        'ldap': _ldap_config,
        'default': True
    }
}

IDENTITY_PROVIDERS = {
    'ldap': {
        'type': 'ldap',
        'title': 'LDAP',
        'ldap': _ldap_config,
        'mapping': {
            'first_name': 'givenName',
            'last_name': 'sn',
            'email': 'mail',
        },
        'trusted_email': True,
        'default_group_provider': True,
    }
}
```

**Comment by gholman** [comment]
It appears to be working with the following changes to indico.conf.   Thanks for pointing me in the correct direction:

```
    'uid': 'uid',
    'user_base': 'ou=XXX,dc=XXX,dc=XXX',

    'gid': 'cn',
    'group_base': 'ou=XXX,dc=XXX,dc=XXX',
    'member_of_attr': 'memberOf',
    'group_filter': '(objectClass=groupOfNames)',
    'ad_group_style': False,
```
