### ISSUE TITLE
problems after updating to 2.1

### ISSUE THREAD

**Issue by hormiai76** [indico/indico#3369]
Hi,
I just updated our test server from 2.0.3 to 2.1 and I got this error after login in.
Any suggestion?
Thank you
Alberto Nardella
```
Traceback
---------
Traceback (most recent call last):
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/flask/util.py", line 114, in wrapper
    return obj().process()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/rh.py", line 299, in process
    handle_sqlalchemy_database_error()  # this will re-raise an exception
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/rh.py", line 289, in process
    res = self._do_process()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/rh.py", line 259, in _do_process
    rv = self._process()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/categories/controllers/display.py", line 330, in _process
    managers = sorted(self.category.get_manager_list(), key=attrgetter('principal_type.name', 'name'))
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/core/db/sqlalchemy/protection.py", line 467, in get_manager_list
    managers = {x.principal for x in self.acl_entries if x.has_management_permission()}
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 242, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 599, in get
    value = self.callable_(state, passive)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 631, in _load_for_state
    session, state, primary_key_identity, passive)
  File "<string>", line 1, in <lambda>
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 756, in _emit_lazyload
    result = q(session).params(**params).all()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/ext/baked.py", line 434, in all
    return list(self)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/ext/baked.py", line 341, in __iter__
    return q._execute_and_instances(context)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2948, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) column principals.permissions does not exist LINE 1: ...full_access AS categories_principals_full_access, categories...
                                                             ^
 [SQL: 'SELECT categories.principals.mp_group_provider AS categories_principals_mp_group_provider, categories.principals.mp_group_name AS categories_principals_mp_group_name, categories.principals.read_access AS categories_principals_read_access, categories.principals.full_access AS categories_principals_full_access, categories.principals.permissions AS categories_principals_permissions, categories.principals.id AS categories_principals_id, categories.principals.category_id AS categories_principals_category_id, categories.principals.local_group_id AS categories_principals_local_group_id, categories.principals.user_id AS categories_principals_user_id, categories.principals.ip_network_group_id AS categories_principals_ip_network_group_id, categories.principals.type AS categories_principals_type, ip_networks_1.group_id AS ip_networks_1_group_id, ip_networks_1.network AS ip_networks_1_network, ip_network_groups_1.id AS ip_network_groups_1_id, ip_network_groups_1.name AS ip_network_groups_1_name, ip_network_groups_1.description AS ip_network_groups_1_description, ip_network_groups_1.hidden AS ip_network_groups_1_hidden, ip_network_groups_1.attachment_access_override AS ip_network_groups_1_attachment_access_override, users_1.title AS users_1_title, affiliations_1.id AS affiliations_1_id, affiliations_1.user_id AS affiliations_1_user_id, affiliations_1.name AS affiliations_1_name, emails_1.id AS emails_1_id, emails_1.user_id AS emails_1_user_id, emails_1.email AS emails_1_email, emails_1.is_primary AS emails_1_is_primary, emails_1.is_user_deleted AS emails_1_is_user_deleted, users_1.id AS users_1_id, users_1.first_name AS users_1_first_name, users_1.last_name AS users_1_last_name, users_1.phone AS users_1_phone, users_1.address AS users_1_address, users_1.merged_into_id AS users_1_merged_into_id, users_1.is_system AS users_1_is_system, users_1.is_admin AS users_1_is_admin, users_1.is_blocked AS users_1_is_blocked, users_1.is_pending AS users_1_is_pending, users_1.is_deleted AS users_1_is_deleted, groups_1.id AS groups_1_id, groups_1.name AS groups_1_name \nFROM categories.principals LEFT OUTER JOIN indico.ip_network_groups AS ip_network_groups_1 ON ip_network_groups_1.id = categories.principals.ip_network_group_id LEFT OUTER JOIN indico.ip_networks AS ip_networks_1 ON ip_network_groups_1.id = ip_networks_1.group_id LEFT OUTER JOIN users.users AS users_1 ON users_1.id = categories.principals.user_id LEFT OUTER JOIN users.affiliations AS affiliations_1 ON users_1.id = affiliations_1.user_id LEFT OUTER JOIN users.emails AS emails_1 ON users_1.id = emails_1.user_id AND emails_1.is_primary LEFT OUTER JOIN users.groups AS groups_1 ON groups_1.id = categories.principals.local_group_id \nWHERE %(param_1)s = categories.principals.category_id'] [parameters: {'param_1': 0}] (Background on this error at: http://sqlalche.me/e/f405)


Request Data
------------
{u'data': {u'get': {},
           u'headers': {'Accept': u'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
                        'Accept-Encoding': u'gzip, deflate, br',
                        'Accept-Language': u'it,ca;q=0.8,es;q=0.5,en;q=0.3',
                        'Cookie': u'_ga=GA1.2.866956967.1525950719; _pk_id.9.6d9f=35e9428f4517225e.1526403139.3.1527011498.1527011416.; indico_session=93d24018-2901-4e21-b650-059467d12323; _pk_ses.9.6d9f=*',
                        'Host': u'indico-test.maxiv.lu.se',
                        'Referer': u'https://indico-test.maxiv.lu.se/',
                        'Upgrade-Insecure-Requests': u'1',
                        'User-Agent': u'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0'},
           u'json': None,
           u'post': {},
           u'url': {u'category_id': 0}},
 u'endpoint': u'categories.display',
 u'id': 'e733331e260c4297',
 u'ip': '194.47.255.202',
 u'method': 'GET',
 u'referrer': 'https://indico-test.maxiv.lu.se/',
 u'rh': 'RHDisplayCategory',
 u'time': '2018-05-22T19:51:40.869023',
 u'url': u'https://indico-test.maxiv.lu.se/',
 u'user': {u'email': u'alberto.nardella@maxiv.lu.se',
           u'id': 354,
           u'name': u'Alberto Nardella'},
 u'user_agent': u'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0'}
```

**Comment by hormiai76** [comment]
It works. Thank you.

**Comment by ThiefMaster** [comment]
Great! This is mentioned in the upgrade guide btw: https://docs.getindico.io/en/latest/installation/upgrade/
