### ISSUE TITLE
column contribution_principals.roles does not exist

### ISSUE THREAD

**Issue by hormiai76** [indico/indico#3373]
Hi all,
I just got this error message sent by Indico (v2.1).
Regards,
Alberto Nardella

`2018-05-25 07:00:00,169  0000000000000000  celery.app.trace - ERROR trace.py:248 -- Task category_suggestions[70f66c56-1682-4d35-bd2f-e597de7e50ad] raised unexpected: ProgrammingError('(psycopg2.ProgrammingError) column contribution_principals.roles does not exist\nLINE 1: ...ss AS events_contribution_principals_full_access, events.con...\n                                                             ^\n',)

Traceback (most recent call last):
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/core/celery/core.py", line 156, in __call__
    rv = super(IndicoTask, s).__call__(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/core/celery/util.py", line 40, in wrapper
    return f(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/categories/tasks.py", line 48, in category_suggestions
    for category, score in get_category_scores(user).iteritems():
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/util/suggestions.py", line 121, in get_category_scores
    for id_, roles in get_events_with_linked_contributions(user).iteritems()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/events/contributions/util.py", line 82, in get_events_with_linked_contributions
    .options(noload('*'))
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/events/contributions/util.py", line 56, in add_acl_data
    def add_acl_data():
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    :meth:`.Query.first`
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    except AttributeError:
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    # if no clone, since we have no annotations we return
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    if not self.schema_for_object.is_default else None)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    self.dialect.do_execute(
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    if not self._is_disconnect:
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    else:
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor = None
ProgrammingError: (psycopg2.ProgrammingError) column contribution_principals.roles does not exist LINE 1: ...ss AS events_contribution_principals_full_access, events.con...
                                                             ^
 [SQL: 'SELECT events.contribution_principals.read_access AS events_contribution_principals_read_access, events.contribution_principals.full_access AS events_contribution_principals_full_access, events.contribution_principals.roles AS events_contribution_principals_roles, events.contribution_principals.id AS events_contribution_principals_id, events.contribution_principals.contribution_id AS events_contribution_principals_contribution_id, events.contributions.id AS events_contributions_id, events.contributions.event_id AS events_contributions_event_id \nFROM events.contribution_principals JOIN events.contributions ON events.contributions.id = events.contribution_principals.contribution_id JOIN events.events ON events.events.id = events.contributions.event_id \nWHERE %(param_1)s = events.contribution_principals.user_id AND NOT events.contributions.is_deleted AND NOT events.events.is_deleted'] [parameters: {'param_1': 1667}] 
`

**Comment by ThiefMaster** [comment]
did you restart celery after updating to 2.1?

**Comment by hormiai76** [comment]
It seems the celery service was not restarted correctly. Thank you

**Comment by ThiefMaster** [comment]
Just FYI for future updates, the upgrade docs actually mention to stop celery before the upgrade and start it again only after finishing the upgrade: https://docs.getindico.io/en/latest/installation/upgrade/
