### ISSUE TITLE
"'NoneType' object is not iterable" during upgrade from 2.1.1 to 2.1.2

### ISSUE THREAD

**Issue by Marx1st** [indico/indico#3412]
When I try to start the db upgrade I get the following error:

```
(.venv) indico@indico:~$ indico db upgrade
Traceback (most recent call last):
  File "/opt/indico/.venv/bin/indico", line 11, in <module>
    sys.exit(cli())
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/cli/util.py", line 119, in invoke
    return self._impl.invoke(ctx)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/cli.py", line 256, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/cli.py", line 229, in load_app
    rv = self.create_app(self)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/cli/util.py", line 37, in _create_app
    return make_app(set_path=True)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/flask/app.py", line 355, in make_app
    multipass.init_app(app)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/core/auth.py", line 74, in init_app
    super(IndicoMultipass, self).init_app(app)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask_multipass/core.py", line 73, in init_app
    state.auth_providers = ImmutableDict(self._create_providers('AUTH', AuthProvider))
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask_multipass/core.py", line 406, in _create_providers
    providers[name] = cls(self, name, settings)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask_multipass/providers/shibboleth.py", line 43, in __init__
    self.attrs = [attr.lower() for attr in self.settings.get('attrs')]
TypeError: 'NoneType' object is not iterable
```

**Comment by ThiefMaster** [comment]
Run `pip install flask-multipass==0.1.8`, then try again

**Comment by ThiefMaster** [comment]
@Marx1st did you manage to try this fix and did it work for you?

**Comment by Marx1st** [comment]
Hi!

I get the following warning when installing flask-multipass 0.1.8:

`indico 2.1.1 has requirement Flask-Multipass==0.1.3, but you'll have flask-multipass 0.1.8 which is incompatible.
Installing collected packages: flask-multipass
  Found existing installation: Flask-Multipass 0.1.3
    Uninstalling Flask-Multipass-0.1.3:
      Successfully uninstalled Flask-Multipass-0.1.3
Successfully installed flask-multipass-0.1.8`

But apart from that it works! The db upgrade did finish this time.

Thanks!

**Comment by ThiefMaster** [comment]
Are you sure you already have 2.1.2 installed? Or did you install it only after updating flask-multipass?

**Comment by Marx1st** [comment]
I did install flask first and then Indico 2.1.2.

**Comment by ThiefMaster** [comment]
ok then the warning makes sense.
