### ISSUE TITLE
UnicodeDecodeError with umlauts during LDAP user lookup

### ISSUE THREAD

**Issue by SethosII** [indico/indico#3559]
I just set up Indico with LDAP and always get the error `UnicodeDecodeError` whenever I try to search for a user and the result contains an umlaut. The issue isn't present when searching for groups.

Here is the relevant section of the `indico.log` file:

```
2018-10-01 05:13:57,001  ERROR    0867c0445a0645f4  indico.flask              Uncaught Exception
Traceback (most recent call last):
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/flask/util.py", line 114, in wrapper
    return obj().process()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/rh.py", line 289, in process
    res = self._do_process()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/rh.py", line 259, in _do_process
    rv = self._process()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/users/controllers.py", line 369, in _process
    external=external, allow_system_user=True, **form_data)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/users/util.py", line 239, in search_users
    for ident in identities:
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask_multipass/core.py", line 347, in search_identities
    for identity_info in provider.search_identities(provider.map_search_criteria(criteria), exact=exact):
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask_multipass/providers/ldap/providers.py", line 191, in search_identities
    yield IdentityInfo(self, identifier=user_data[self.ldap_settings['uid']][0], **to_unicode(user_data))
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask_multipass/data.py", line 67, in __init__
    self.identifier = text_type(identifier)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

Seems related to https://github.com/indico/indico/issues/3143?

Versions:
Indico 2.1.4
Flask-Multipass: 0.1.8

**Comment by SethosII** [comment]
I looked into the code but couldn't find something obvious or similar to the mentioned issue. Has someone an idea how to fix this? Login with LDAP is not possible due to this (at least I think this is the cause ...).

**Comment by ThiefMaster** [comment]
self.identifier = text_type(identifier)

Try replacing this line with:

    self.identifier = identifier.decode('utf-8')

in

    /opt/indico/.venv/local/lib/python2.7/site-packages/flask_multipass/data.py

**Comment by SethosII** [comment]
@ThiefMaster Thank you, that fixed the search!

However, I'm still not able to login with LDAP. I tried with the mail adress (forename.surname@domain.tld) and username as shown by the search (Forename Surname), and with the usual account name (forename.surname). The error I get is `Login failed: No such user`. What is the username supposed to be with LDAP authentication?

**Comment by ThiefMaster** [comment]
The username for LDAP auth is whatever is set as 'uid' in the config's `ldap_settings`.

**Comment by SethosII** [comment]
@ThiefMaster That worked, thank you very much!

For the fix in the LDAP search, will you add a commit so that this is fixed in an upcoming version?

**Comment by ThiefMaster** [comment]
yes
