### ISSUE TITLE
Error while installing Indico: ImportError: cannot import name ReparseException

### ISSUE THREAD

**Issue by nop33** [indico/indico#3592]
Trying to install (development) Indico on maOS. I followed the guide step by step, but after executing
```
indico setup wizard --dev
```
I got this error:
```
Traceback (most recent call last):
  File "/Users/iliastrichopoulos/dev/indico/env/bin/indico", line 11, in <module>
    load_entry_point('indico', 'console_scripts', 'indico')()
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 1018, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 875, in parse_args
    parser = self.make_parser(ctx)
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 821, in make_parser
    for param in self.get_params(ctx):
  File "/Users/iliastrichopoulos/dev/indico/src/indico/cli/util.py", line 125, in get_params
    return self._impl.get_params(ctx)
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/werkzeug/utils.py", line 73, in __get__
    value = self.func(obj)
  File "/Users/iliastrichopoulos/dev/indico/src/indico/cli/util.py", line 110, in _impl
    return getattr(import_module(module), name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/iliastrichopoulos/dev/indico/src/indico/cli/setup.py", line 44, in <module>
    from indico.util.console import cformat
  File "/Users/iliastrichopoulos/dev/indico/src/indico/util/console.py", line 31, in <module>
    from indico.util.string import is_valid_mail, to_unicode
  File "/Users/iliastrichopoulos/dev/indico/src/indico/util/string.py", line 34, in <module>
    import bleach
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/bleach/__init__.py", line 11, in <module>
    from bleach.sanitizer import (
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/bleach/sanitizer.py", line 10, in <module>
    from html5lib.constants import (
ImportError: cannot import name ReparseException
```

The steps I followed:
```
brew install python2 redis libjpeg libffi pcre libyaml
mkdir ~/dev/indico
mkdir -p ~/dev/indico/data
cd ~/dev/indico
virtualenv env -p /usr/bin/python2.7
git clone --recursive git@github.com:nop33/indico.git src
cd src
git remote add upstream https://github.com/indico/indico.git
cd ..
source ./env/bin/activate
pip install -U pip setuptools
cd src
pip install -r requirements.dev.txt
pip install -e .
npm install
indico setup wizard --dev
```

**Comment by ThiefMaster** [comment]
get the latest `upstream/master` instead of your (probably very outdated) fork's master. this error happens due to outdated dependencies (mozilla/bleach#337)

**Comment by nop33** [comment]
Yeah, I forgot to fetch the updated master, thanks!

Is this also a common error?

```
32939 verbose stack Error: indico@2.0.0 postinstall: `patch -p0 -d node_modules/jquery-ui --merge < indico/web/client/js/jquery/contrib/jquery-ui-changes.diff`
32939 verbose stack Exit status 2
```

**Comment by ThiefMaster** [comment]
never seen that; any useful output above?

**Comment by nop33** [comment]
That's the output of `npm install`

```
› npm install

> indico@2.0.0 postinstall /Users/iliastrichopoulos/dev/indico/src
> patch -p0 -d node_modules/jquery-ui --merge < indico/web/client/js/jquery/contrib/jquery-ui-changes.diff

patch: unrecognized option `--merge'
patch: Try `patch --help' for more information.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! indico@2.0.0 postinstall: `patch -p0 -d node_modules/jquery-ui --merge < indico/web/client/js/jquery/contrib/jquery-ui-changes.diff`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the indico@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/iliastrichopoulos/.npm/_logs/2018-10-16T20_46_00_862Z-debug.log
```
and `/Users/iliastrichopoulos/.npm/_logs/2018-10-16T20_46_00_862Z-debug.log` is:
https://gist.github.com/nop33/4791662d0c7f23379eb90b5600fc928b

**Comment by ThiefMaster** [comment]
you can probably remove the `--merge` switch from the patch call (inside package.json); iirc i just added it to avoid errors when running `npm install` again later

**Comment by nop33** [comment]
you mean change the 
```
"postinstall": "patch -p0 -d node_modules/jquery-ui --merge < indico/web/client/js/jquery/contrib/jquery-ui-changes.diff",
```
to
```
"postinstall": "patch -p0 -d node_modules/jquery-ui",
```
?

**Comment by ThiefMaster** [comment]
no, don't remove the input file. just the `--merge`

**Comment by nop33** [comment]
next issue...
```
› ./bin/maintenance/build-assets.py indico --dev --watch
fatal: No annotated tags can describe '731572975282e1ebe08a98ca1adc0a6a6f6f4939'.
However, there were unannotated tags: try --tags.
Traceback (most recent call last):
  File "bin/maintenance/dump_url_map.py", line 71, in <module>
    main()
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "bin/maintenance/dump_url_map.py", line 60, in main
    version = get_map_version()
  File "bin/maintenance/dump_url_map.py", line 35, in get_map_version
    h.update(subprocess.check_output(['git', 'describe']))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'describe']' returned non-zero exit status 128
Traceback (most recent call last):
  File "./bin/maintenance/build-assets.py", line 267, in <module>
    cli()
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/iliastrichopoulos/dev/indico/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./bin/maintenance/build-assets.py", line 177, in build_indico
    subprocess.check_call(['python', 'bin/maintenance/dump_url_map.py'] + force_url_map)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'bin/maintenance/dump_url_map.py']' returned non-zero exit status 1
```

**Comment by ThiefMaster** [comment]
`git fetch upstream --tags`

**Comment by nop33** [comment]
^ should be mentioned in the docs ;)

**Comment by ThiefMaster** [comment]
if a normal git clone doesn't fetch tags I'd rather change that git describe call there to not include a tag

**Comment by nop33** [comment]
Probably it does, the problem must have been that I cloned my (very old) fork and no tags there. Anyway, I managed to get indico up and running! Thanks for the help!
