### ISSUE TITLE
Create room failed with UnicodeEncodeError

### ISSUE THREAD

**Issue by csabibela** [indico/indico#3740]
Create room failed with UnicodeEncodeError if the location name contains accents.

1. Create location 'Igazgatási Épület' (Administration Building)
2. Open the location
3. Push the new room button.

The exception:

2019-01-29 18:16:03,429  9b36aacec33f4676  indico.flask - ERROR errors.py:107 -- Uncaught Exception

Traceback (most recent call last):
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/web/flask/util.py", line 114, in wrapper
    return obj().process()
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/web/rh.py", line 289, in process
    res = self._do_process()
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/web/rh.py", line 259, in _do_process
    rv = self._process()
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/rb/controllers/admin/rooms.py", line 137, in _process
    location=self._location, errors=self._form.error_list).display()
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/web/views.py", line 231, in display
    body = to_unicode(self._display(params))
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/web/views.py", line 261, in _display
    return self._applyDecoration(self._getBody(params))
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/admin/views.py", line 40, in _getBody
    return self._getPageContent(params)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/rb/views/admin/__init__.py", line 31, in _getPageContent
    return render_template('rb/admin.html', body=self._get_legacy_content(params), subtitle=self.subtitle,
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/rb/views/admin/rooms.py", line 35, in _get_legacy_content
    return WTemplated('RoomBookingRoomForm').getHTML(params)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/webinterface/wcomponents.py", line 85, in getHTML
    return render_mako(self.tplFile, vars)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/common/TemplateExec.py", line 85, in render
    return template.render(**params)
  File "/opt/indico/.venv/lib/python2.7/site-packages/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/opt/indico/.venv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/opt/indico/.venv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/opt/indico/.venv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/opt/indico/tmp/mako_modules/2.1.7/RoomBookingRoomForm.tpl.py", line 328, in render_body
    __M_writer(str(encode_if_unicode( _('You may first add some to location, {0}.').format(location.name) )))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 7: ordinal not in range(128)

{u'data': {u'get': {},
           u'headers': {'Accept': u'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
                        'Accept-Encoding': u'gzip, deflate, br',
                        'Accept-Language': u'hu,en;q=0.9,en-US;q=0.8,de;q=0.7,nb;q=0.6,af;q=0.5',
                        'Connection': u'keep-alive',
                        'Cookie': u'_shibsession_64656661756c7468747470733a25f76656e742e737a652e68752f733sd2626f6c657468=_323444ae58c02d7f4dce2dd9c6510389; indico_session=f6be1726-a1aa-2323-af99-ec8e3b6b2055; _ga=GA1.2.88296902.1547062161',
                        'Host': u'event.XXX.hu',
                        'Referer': u'https://event.XXX.hu/admin/rooms/location/Igazgat%C3%A1si%20%C3%A9p%C3%BClet/',
                        'Upgrade-Insecure-Requests': u'1',
                        'User-Agent': u'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36'},
           u'json': None,
           u'post': {},
           u'url': {'roomLocation': u'Igazgat\xe1si \xe9p\xfclet'}},
 u'endpoint': 'rooms_admin.create_room',
 u'id': '9b36aacec33f4676',
 u'ip': 'XXX.XXX.XXX.XXX',
 u'method': 'GET',
 u'referrer': 'https://event.XXX.hu/admin/rooms/location/Igazgat%C3%A1si%20%C3%A9p%C3%BClet/',
 u'rh': 'RHRoomBookingCreateRoom',
 u'time': '2019-01-29T18:16:03.559627',
 u'url': u'https://event.XXX.hu/admin/rooms/room/Igazgat\xe1si \xe9p\xfclet/create',
 u'user': {u'email': u'XXX@XXX.hu', u'id': 1, u'name': u'B\xe9la Cs\xe1bi'},
 u'user_agent': u'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36'}

**Comment by mic4ael** [comment]
Hey, thanks for reporting the issue. Currently there is an ongoing overhaul of the roombooking system and we will definitely make sure that something like this doesn't occur anymore.

**Comment by wiene** [comment]
> Currently there is an ongoing overhaul of the roombooking system and we will definitely make sure that something like this doesn't occur anymore.

Looking at the [project board for release 2.2](https://github.com/indico/indico/projects/2) it seems that the mentioned overhaul of the room booking system will become part of release 2.2. @mic4ael, does your comment mean that this issue will also be fixed in release 2.2?

**Comment by ThiefMaster** [comment]
Yes, any unicode-related problems should be gone. But just in case, we'll test a room and location with non-ascii chars before the release.

**Comment by ThiefMaster** [comment]
I can confirm that rooms andlocations with non-ascii chars in the name work fine as of 2.2.
