### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by dieperie** [indico/indico#3817]
```
$ pip install -U indico
Traceback (most recent call last):
  File "/opt/indico/.venv/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/pip/_internal/__init__.py", line 5, in <module>
    import logging
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

**Comment by ThiefMaster** [comment]
That looks like your Python installation is broken.
