### ISSUE TITLE
setup.py includes Python2 print statement

### ISSUE THREAD

**Issue by tenomoto** [indico/indico#3901]
**Describe the bug**
`setup.py` fails due to print statements in setup.py.
Tested with python36 on FreeBSD.

**To Reproduce**
1. Create `etc/indico.ini`
2. Create venv with `python3.6`.
    $ python3.6 -m venv venv
    $ . venv/bin/activate
3. Install indico
    (venv) $ pip install indico

**Expected behavior**
```
Collecting indico
  Downloading https://files.pythonhosted.org/packages/ef/07/b8307e72a251e6080fdadf9aa8fea91d11f4a7d426aac40531337386dcf6/indico-1.2.2.tar.gz (54.2MB)
    100% |################################| 54.2MB 849kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-v_px0yez/indico/setup.py", line 219
        print 'Upgrading existing etc/indico.conf...'
                                                    ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Upgrading existing etc/indico.conf...')?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-v_px0yez/indico/
```

**Additional context**
`setup.py` contains Python2 print statements.
```
$ grep "print '" setup.py
            print 'Upgrading existing etc/indico.conf...'
            print 'Creating new etc/indico.conf..'
        print 'Creating directories...',
        print 'Done!'
        print '''
```

**Comment by ThiefMaster** [comment]
thanks, but we do not support Python 3 yet. also, you're installing an ancient version that's completely obsolete and unsupported..

**Comment by cederom** [comment]
The same here, first contact with Indico :-(

```
$ uname -a
Linux fadeaway 4.14.117-grsec-grsec+ #1 SMP Sat May 11 00:40:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


(.venv) [fadeaway]$ pip install indico
Collecting indico
  Downloading https://files.pythonhosted.org/packages/ef/07/b8307e72a251e6080fdadf9aa8fea91d11f4a7d426aac40531337386dcf6/indico-1.2.2.tar.gz (54.2MB)
     |################################| 54.2MB 18.4MB/s
    ERROR: Command errored out with exit status 1:
     command: /home/pttmkonferencje/.venv/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b4nwss9z/indico/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b4nwss9z/indico/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-b4nwss9z/indico/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-b4nwss9z/indico/setup.py", line 219
        print 'Upgrading existing etc/indico.conf...'
                                                    ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Upgrading existing etc/indico.conf...')?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(.venv) [fadeaway]$ pip install indico==
Collecting indico==
  ERROR: Could not find a version that satisfies the requirement indico== (from versions: 1.2.1rc5, 1.2.1rc7, 1.2.1rc9, 1.2.1rc10, 1.2.1rc11, 1.2.1, 1.2.2rc1, 1.2.2)
ERROR: No matching distribution found for indico==
```

As Python3 is not yet supported, that would be worth mentioning in the installation guide:
https://docs.getindico.io/en/latest/installation/production/debian/nginx/
