### ISSUE TITLE
Error running: indico i18n compile-catalog-react

### ISSUE THREAD

**Issue by VZsI** [indico/indico#4030]
I get the following output. (Running **indico i18n compile-catalog** works fine... ver. 2.2)

```
Traceback (most recent call last):
  File "/opt/indico/.venv/bin/indico", line 10, in <module>
    sys.exit(cli())
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/cli/util.py", line 110, in invoke
    return self._impl.invoke(ctx)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/cli/i18n.py", line 157, in compile_catalog_react
    output = subprocess.check_output(['npx', 'react-jsx-i18n', 'compile', po_file])
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by ThiefMaster** [comment]
Sounds like you do not have a recent nodejs version (e.g. node 10) installed, `npx` and `npm` come with all recent node versions... See https://nodejs.org/en/download/package-manager/ on how to install node on your linux distro.
