### ISSUE TITLE
running `indico db update` fails for dependency pillow==6.2.1 (but works for 6.1.0)

### ISSUE THREAD

**Issue by marengeti** [indico/indico#4228]
When installing (or updating) Indico, and executing:

```
src]$ pip install -r requirements.txt
...
ERROR: indico 2.2.dev0 has requirement Pillow==6.1.0, but you'll have pillow 6.2.1 which is incompatible.
Installing collected packages: Pillow
  Found existing installation: Pillow 6.1.0
    Uninstalling Pillow-6.1.0:
      Successfully uninstalled Pillow-6.1.0
Successfully installed Pillow-6.2.1

but then, doing other followup commands for the update fail, e.g.:

src]$ indico db upgrade
Traceback (most recent call last):
  File "/data/opt/indico/.venv/bin/indico", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/data/opt/indico/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/data/opt/indico/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/data/opt/indico/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/data/opt/indico/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/data/opt/indico/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/data/opt/indico/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Pillow==6.1.0' distribution was not found and is required by indico 
```

The db update command runs successfully however after uninstalling pillow and installing 6.1.0.

**Comment by ThiefMaster** [comment]
That sounds like your installed dependencies don't match the requirements. Running `pip install -e .` should fix this. But if `indico db` fails then any other `indico` command should fails as well...

**Comment by marengeti** [comment]
OK thanks, that seems to have resolved this:

src]$ pip install -e .
...
Installing collected packages: Pillow, indico
  Found existing installation: Pillow 6.1.0
    Uninstalling Pillow-6.1.0:
      Successfully uninstalled Pillow-6.1.0
  Found existing installation: indico 2.3.dev0
    Uninstalling indico-2.3.dev0:
      Successfully uninstalled indico-2.3.dev0
  Running setup.py develop for indico
Successfully installed Pillow-6.2.1 indico
WARNING: You are using pip version 19.2.2, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(.venv) [indico@rtce-indico2-test src]$ 
(.venv) [indico@rtce-indico2-test src]$ 
(.venv) [indico@rtce-indico2-test src]$ 
src]$ indico db upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
src]$
