### ISSUE TITLE
installing Indico 2.2.5 at Debian 9 did not work.

### ISSUE THREAD

**Issue by mohammadamro2** [indico/indico#4249]
I tried to install indico 2.2.5 at Debian and I received the following error :

```
   ERROR: Command errored out with exit status 1:
     command: /opt/indico/.venv/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5qMEL8/translitcodec/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5qMEL8/translitcodec/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-5qMEL8/translitcodec/pip-egg-info
         cwd: /tmp/pip-install-5qMEL8/translitcodec/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5qMEL8/translitcodec/setup.py", line 9, in <module>
        import translitcodec
      File "translitcodec/__init__.py", line 24
    SyntaxError: Non-ASCII character '\xc3' in file translitcodec/__init__.py on line 25, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by ThiefMaster** [comment]
Try to `pip install 'translitcodec==0.4.0'` before installing indico; looks like they made a new release after 5 years, and we don't have pinned the version there..

**Comment by ThiefMaster** [comment]
Related: claudep/translitcodec#3

**Comment by ThiefMaster** [comment]
OK, this problem should be gone since all newer versions of the dependency now explicitly require python 3.

leaving this issue open as a reminder to pin `translitcodec==0.4.0`

**Comment by mohammadamro2** [comment]
Thanks, the issue has been resolved.
