### ISSUE TITLE
Exception in initial livesync export

### ISSUE THREAD

**Issue by sowo** [indico/indico#5373]
**Describe the bug**
I am on master (c40ec0bee9e7cb0497274f652ddf561023c54133) and when running an initial export with the livesync_debug adapter I get the following exception:

```
Traceback (most recent call last):
  File "/home/sommerer/.venv/bin/indico", line 33, in <module>
    sys.exit(load_entry_point('indico', 'console_scripts', 'indico')())
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/flask/cli.py", line 579, in main
    return super().main(*args, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/flask_pluginengine/util.py", line 190, in wrapped
    return func(*args, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/flask/cli.py", line 427, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/indico_livesync/cli.py", line 101, in initial_export
    if not backend.run_initial_export(batch, force, verbose):
  File "/home/sommerer/.venv/lib/python3.9/site-packages/indico_livesync/base.py", line 193, in run_initial_export
    if not uploader.run_initial(events.yield_per(batch_size), events.count()):
  File "/home/sommerer/.venv/lib/python3.9/site-packages/indico_livesync/uploader.py", line 59, in run_initial
    return self.upload_records(records, initial=True)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/indico_livesync_debug/backend.py", line 68, in upload_records
    collections.deque(dumped_records, maxlen=0)  # exhaust the iterator
  File "/home/sommerer/.venv/lib/python3.9/site-packages/indico_livesync_debug/backend.py", line 66, in <genexpr>
    dumped_records = (_print_record(*x, print_blank=(not self._is_queue_run), verbose=self.verbose)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/indico_livesync_debug/backend.py", line 58, in <genexpr>
    dumped_records = (
  File "/home/sommerer/Projects/indico/indico/util/console.py", line 93, in verbose_iterator
    text = fmt.format(i, total, (i / total * 100.0), remaining, id_, title)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/colorclass/core.py", line 187, in format
    return self.__class__(super(ColorStr, self).format(*args, **kwargs), keep_tags=True)
KeyError: 'grey'
```

Reverting to the 3.1.x branch produces regular output but unfortunately I already performed a db upgrade so it won't do the initial export either due to affiliation table issues

**To Reproduce**
1. perform "indico livesync initial-export" using the livesync_Debug adapter

**Expected behavior**
Works without raising an exception

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ThiefMaster** [comment]
Nice catch. It's now fixed in master.

**Comment by sowo** [comment]
That was quick!! I pulled the latest commit and the issue is gone.
Thank you!
