### ISSUE TITLE
Exception livesync initial-export

### ISSUE THREAD

**Issue by sowo** [indico/indico#5377]
**Describe the bug**
I am on master (b732cbe299e2a8a5aeacebd38b90b309abc37ca7)  and alembic version 0c4bb2973536. When running "indico livesync initial-export" using the Livesync_Debug adapter, I get the following exception once it starts exporting attachments.

```
Exporting attachments
Traceback (most recent call last):
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/orm/strategy_options.py", line 338, in _generate_path
    attr = getattr(ent.class_, attr)
AttributeError: type object 'User' has no attribute '_affiliation'
```

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "/home/sommerer/.venv/bin/indico", line 33, in <module>
    sys.exit(load_entry_point('indico', 'console_scripts', 'indico')())
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/flask/cli.py", line 579, in main
    return super().main(*args, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/flask_pluginengine/util.py", line 190, in wrapped
    return func(*args, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/flask/cli.py", line 427, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/indico_livesync/cli.py", line 101, in initial_export
    if not backend.run_initial_export(batch, force, verbose):
  File "/home/sommerer/.venv/lib/python3.9/site-packages/indico_livesync/base.py", line 205, in run_initial_export
    if not uploader.run_initial(attachments.yield_per(batch_size), attachments.count()):
  File "/home/sommerer/.venv/lib/python3.9/site-packages/indico_livesync/uploader.py", line 57, in run_initial
    records = ((rec, SimpleChange.created) for rec in records)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2896, in __iter__
    return self._iter().__iter__()
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1490, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 523, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 558, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 776, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 451, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3263, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 510, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 735, in create_for_statement
    opt.process_compile_state(self)
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/orm/strategy_options.py", line 260, in process_compile_state
    self._process(
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/orm/strategy_options.py", line 905, in _process
    val._bind_loader(
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/orm/strategy_options.py", line 1096, in _bind_loader
    if not loader._generate_path(
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/orm/strategy_options.py", line 341, in _generate_path
    util.raise_(
  File "/home/sommerer/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Can't find property named "_affiliation" on mapped class User->users in this Query.
```

**To Reproduce**
1. Run "indico livesync initial-export" for an event with attachments

**Expected behavior**
No exception raised

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ThiefMaster** [comment]
Are you using the plugin from the latest indico-plugins master? The error you get seems like your plugin doesn't contain the commit indico/indico-plugins@187a8bd...

**Comment by sowo** [comment]
Switching the plugins to master resolved the issue.

Sorry for having missed that.
