### ISSUE TITLE
SAML encoding error when special characters are returned

### ISSUE THREAD

**Issue by arturo-seijas** [indico/indico#5410]
**Describe the bug**
When configuring SAML authentication, if a special character is returned as part of the first_name, an encoding error occurs. Stacktrace is included below.

**Screenshots**
![image](https://user-images.githubusercontent.com/102022572/178310107-b6ce2373-2d83-4376-9134-85489ecc0b94.png)

**Additional context**
2022-07-11T15:45:13.641Z [indico] Traceback (most recent call last):
2022-07-11T15:45:13.641Z [indico]   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
2022-07-11T15:45:13.641Z [indico]     rv = self.dispatch_request()
2022-07-11T15:45:13.641Z [indico]   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
2022-07-11T15:45:13.641Z [indico]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2022-07-11T15:45:13.641Z [indico]   File "/usr/local/lib/python3.9/dist-packages/indico/web/rh.py", line 333, in wrapper
2022-07-11T15:45:13.641Z [indico]     return rh.process()
2022-07-11T15:45:13.641Z [indico]   File "/usr/local/lib/python3.9/dist-packages/indico/web/rh.py", line 281, in process
2022-07-11T15:45:13.641Z [indico]     res = self._do_process()
2022-07-11T15:45:13.641Z [indico]   File "/usr/local/lib/python3.9/dist-packages/indico/web/rh.py", line 252, in _do_process
2022-07-11T15:45:13.641Z [indico]     rv = self._process()
2022-07-11T15:45:13.641Z [indico]   File "/usr/local/lib/python3.9/dist-packages/indico/web/rh.py", line 322, in _process
2022-07-11T15:45:13.641Z [indico]     rv = self.func()
2022-07-11T15:45:13.641Z [indico]   File "/usr/local/lib/python3.9/dist-packages/flask_multipass/util.py", line 119, in decorator
2022-07-11T15:45:13.641Z [indico]     return func(*args, **kwargs)
2022-07-11T15:45:13.641Z [indico]   File "/usr/local/lib/python3.9/dist-packages/flask_multipass/providers/saml.py", line 142, in _saml_acs
2022-07-11T15:45:13.641Z [indico]     print(f'Login successful; received attributes: {attributes}')
2022-07-11T15:45:13.641Z [indico] UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 158: ordinal not in range(128)
2022-07-11T15:45:13.641Z [indico] 
2022-07-11T15:45:13.641Z [indico] During handling of the above exception, another exception occurred:
2022-07-11T15:45:13.641Z [indico] 
2022-07-11T15:45:13.641Z [indico] Traceback (most recent call last):
2022-07-11T15:45:13.641Z [indico]   File "/usr/lib/python3.9/logging/handlers.py", line 1065, in emit
2022-07-11T15:45:13.641Z [indico]     smtp.send_message(msg)
2022-07-11T15:45:13.641Z [indico]   File "/usr/lib/python3.9/smtplib.py", line 943, in send_message
2022-07-11T15:45:13.641Z [indico]     self.ehlo_or_helo_if_needed()
2022-07-11T15:45:13.641Z [indico]   File "/usr/lib/python3.9/smtplib.py", line 611, in ehlo_or_helo_if_needed
2022-07-11T15:45:13.641Z [indico]     if not (200 <= self.ehlo()[0] <= 299):
2022-07-11T15:45:13.641Z [indico]   File "/usr/lib/python3.9/smtplib.py", line 451, in ehlo
2022-07-11T15:45:13.641Z [indico]     self.putcmd(self.ehlo_msg, name or self.local_hostname)
2022-07-11T15:45:13.641Z [indico]   File "/usr/lib/python3.9/smtplib.py", line 378, in putcmd
2022-07-11T15:45:13.641Z [indico]     self.send(f'{s}{CRLF}')
2022-07-11T15:45:13.641Z [indico]   File "/usr/lib/python3.9/smtplib.py", line 365, in send
2022-07-11T15:45:13.641Z [indico]     raise SMTPServerDisconnected('please run connect() first')
2022-07-11T15:45:13.641Z [indico] smtplib.SMTPServerDisconnected: please run connect() first
2022-07-11T15:45:13.641Z [indico] Call stack:
2022-07-11T15:45:13.644Z [indico]   File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/flask.py", line 90, in sentry_patched_wsgi_app
2022-07-11T15:45:13.644Z [indico]     return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
2022-07-11T15:45:13.644Z [indico]   File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/wsgi.py", line 133, in __call__
2022-07-11T15:45:13.644Z [indico]     rv = self.app(
2022-07-11T15:45:13.644Z [indico]   File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/flask.py", line 90, in <lambda>
2022-07-11T15:45:13.644Z [indico]     return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
2022-07-11T15:45:13.644Z [indico]   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2091, in __call__
2022-07-11T15:45:13.644Z [indico]     return self.wsgi_app(environ, start_response)
2022-07-11T15:45:13.644Z [indico]   File "/usr/local/lib/python3.9/dist-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
2022-07-11T15:45:13.644Z [indico]     return self.app(environ, start_response)
2022-07-11T15:45:13.644Z [indico]   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
2022-07-11T15:45:13.644Z [indico]     response = self.full_dispatch_request()
2022-07-11T15:45:13.644Z [indico]   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
2022-07-11T15:45:13.644Z [indico]     rv = self.handle_user_exception(e)
2022-07-11T15:45:13.644Z [indico]   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1393, in handle_user_exception
2022-07-11T15:45:13.644Z [indico]     return self.ensure_sync(handler)(e)
2022-07-11T15:45:13.644Z [indico]   File "/usr/local/lib/python3.9/dist-packages/indico/web/flask/errors.py", line 98, in handle_exception
2022-07-11T15:45:13.644Z [indico]     Logger.get('flask').exception(str(exc) or 'Uncaught Exception')
2022-07-11T15:45:13.644Z [indico]   File "/usr/lib/python3.9/logging/__init__.py", line 1481, in exception
2022-07-11T15:45:13.644Z [indico]     self.error(msg, *args, exc_info=exc_info, **kwargs)
2022-07-11T15:45:13.644Z [indico]   File "/usr/lib/python3.9/logging/__init__.py", line 1475, in error
2022-07-11T15:45:13.644Z [indico]     self._log(ERROR, msg, args, **kwargs)
2022-07-11T15:45:13.644Z [indico]   File "/usr/lib/python3.9/logging/__init__.py", line 1589, in _log
2022-07-11T15:45:13.644Z [indico]     self.handle(record)
2022-07-11T15:45:13.644Z [indico]   File "/usr/lib/python3.9/logging/__init__.py", line 1599, in handle
2022-07-11T15:45:13.644Z [indico]     self.callHandlers(record)
2022-07-11T15:45:13.644Z [indico]   File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/logging.py", line 86, in sentry_patched_callhandlers
2022-07-11T15:45:13.644Z [indico]     return old_callhandlers(self, record)
2022-07-11T15:45:13.644Z [indico] Message: "'ascii' codec can't encode character '\\xe1' in position 158: ordinal not in range(128)"

**Comment by ThiefMaster** [comment]
Weird. Any chance that you default encoding is *not* utf-8 for some reason?

**Comment by arturo-seijas** [comment]
> 

Python's? It's the default one. It should be utf-8

**Comment by ThiefMaster** [comment]
Should be... I remember some other (odd) case where someone ended up with a different default encoding which also caused all kinds of weird issues - and your errors looks a lot like it's trying to decode using ASCII instead of UTC-8..

**Comment by arturo-seijas** [comment]
After several tests, I've came to the conclusion that the issue only happens when `debug`is set to `true`. Also, I've been checking the uwsgi docs and the default encoding seems to be ASCII.
Thank you for your help.
