### ISSUE TITLE
Redis connection errors result in several spawned processes

### ISSUE THREAD

**Issue by paulmenzel** [indico/indico#5470]
Updating Indico to 3.2.2, we also upgraded Redis from 6.2.2 to 7.0.4. This features a new protected mode disallowing connections for certain clients. This resulted in Indico restarting itself several times. From the log:

```
Traceback (most recent call last):
  File "/project/indico/home/.local/lib/python3.9/site-packages/indico/core/cache.py", line 148, in get
    return super().get(key, default)
  File "/project/indico/home/.local/lib/python3.9/site-packages/flask_caching/__init__.py", line 190, in get
    return self.cache.get(*args, **kwargs)
  File "/project/indico/home/.local/lib/python3.9/site-packages/indico/core/cache.py", line 69, in get
    return CachedNone.unwrap(super().get(key), default)
  File "/project/indico/home/.local/lib/python3.9/site-packages/cachelib/redis.py", line 72, in get
    return self.serializer.loads(self._read_client.get(self.key_prefix + key))
  File "/project/indico/home/.local/lib/python3.9/site-packages/redis/commands/core.py", line 1705, in get
    return self.execute_command("GET", name)
  File "/project/indico/home/.local/lib/python3.9/site-packages/sentry_sdk/integrations/redis.py", line 168, in sentry_patched_execute_command
    return old_execute_command(self, name, *args, **kwargs)
  File "/project/indico/home/.local/lib/python3.9/site-packages/redis/client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/project/indico/home/.local/lib/python3.9/site-packages/redis/connection.py", line 1387, in get_connection
    connection.connect()
  File "/project/indico/home/.local/lib/python3.9/site-packages/redis/connection.py", line 623, in connect
    self.on_connect()
  File "/project/indico/home/.local/lib/python3.9/site-packages/redis/connection.py", line 734, in on_connect
    if str_if_bytes(self.read_response()) != "OK":
  File "/project/indico/home/.local/lib/python3.9/site-packages/redis/connection.py", line 839, in read_response
    raise response
redis.exceptions.ResponseError: DENIED Redis is running in protected mode because protected mode is enabled and no password is set for the default user. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a an authentication password for the default user. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
```

**Comment by ThiefMaster** [comment]
Not sure if there's anything we can do there... If redis is down - regardless if that's because of a misconfiguration, invalid password, or anything else, Indico will be broken at least for authenticated users since currently e.g. sessions are stored in Redis.
