### ISSUE TITLE
UnicodeDecodeError with en_GB locale

### ISSUE THREAD

**Issue by mthaddon** [indico/indico#5471]
**Describe the bug**
If I connect to a deployed indico instance with a browser that has the en_GB locale configured, I see errors in the javascript console for my browser connecting to the `/assets/i18n/en_GB-react.js` resource as follows:
```
2022-08-25T13:47:37.604Z [indico] --- Logging error ---
2022-08-25T13:47:37.604Z [indico] Traceback (most recent call last):
2022-08-25T13:47:37.604Z [indico]   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1517, in full_dispatch_request
2022-08-25T13:47:37.604Z [indico]     rv = self.dispatch_request()
2022-08-25T13:47:37.604Z [indico]   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1503, in dispatch_request
2022-08-25T13:47:37.604Z [indico]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2022-08-25T13:47:37.604Z [indico]   File "/usr/local/lib/python3.9/dist-packages/indico/web/assets/blueprint.py", line 85, in i18n_locale_react
2022-08-25T13:47:37.604Z [indico]     return _get_i18n_locale(locale_name, react=True)
2022-08-25T13:47:37.604Z [indico]   File "/usr/local/lib/python3.9/dist-packages/indico/web/assets/blueprint.py", line 107, in _get_i18n_locale
2022-08-25T13:47:37.604Z [indico]     i18n_data = generate_i18n_file(locale_name, react=react)
2022-08-25T13:47:37.604Z [indico]   File "/usr/local/lib/python3.9/dist-packages/indico/web/assets/vars_js.py", line 47, in generate_i18n_file
2022-08-25T13:47:37.604Z [indico]     i18n_data = get_locale_data(root_path, locale_name, 'indico', react=react)
2022-08-25T13:47:37.604Z [indico]   File "/usr/local/lib/python3.9/dist-packages/indico/web/assets/vars_js.py", line 29, in get_locale_data
2022-08-25T13:47:37.604Z [indico]     rv = json.load(f)
2022-08-25T13:47:37.604Z [indico]   File "/usr/local/lib/python3.9/dist-packages/flask/json/__init__.py", line 200, in load
2022-08-25T13:47:37.604Z [indico]     return _json.load(fp, **kwargs)
2022-08-25T13:47:37.604Z [indico]   File "/usr/lib/python3.9/json/__init__.py", line 293, in load
2022-08-25T13:47:37.604Z [indico]     return loads(fp.read(),
2022-08-25T13:47:37.604Z [indico]   File "/usr/lib/python3.9/encodings/ascii.py", line 26, in decode
2022-08-25T13:47:37.604Z [indico]     return codecs.ascii_decode(input, self.errors)[0]
2022-08-25T13:47:37.604Z [indico] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 14853: ordinal not in range(128)
```

**To Reproduce**
1. Configure your browser with the en_GB locale
2. Go to a deployed indico instance running version 3.2.
3. Check the javascript console for errors.

**Expected behavior**
If I switch to en_US I see no such errors.

**Comment by arturo-seijas** [comment]
The same occurs for es_ES locale

**Comment by ThiefMaster** [comment]
Does your Python locale default to ASCII instead of UTF-8 by any chance?

**Comment by mthaddon** [comment]
Thanks for the hint and sorry for the noise. Explicitly setting the locale in the docker image we're using to deploy this has fixed the issue for us.

**Comment by ThiefMaster** [comment]
Could you leave a comment what exactly you did here? I've seen one or two people with similar issues (not sure if here or in the forums..)

**Comment by arturo-seijas** [comment]
We just followed this [stackoverflow answer](https://stackoverflow.com/questions/28405902/how-to-set-the-locale-inside-a-debian-ubuntu-docker-container/41648500#41648500). That is, installing `locale`and defining the env vars
```
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV LC_LANG=C.UTF-8
```
inside our Docker container
