### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ycruzz** [indico/indico#5773]
Hi, I just installed version 3.2.3 and I'm having this error

2023-05-13 05:22:14,185  INFO     a068724dd2a3454b  -       indico.rh                 GET / [IP=10.14.6.101] [PID=2570]
2023-05-13 05:22:14,974  ERROR    8aa992b9cd474814  -       indico.flask              'ascii' codec can't decode byte 0xc3 in position 288: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/indico/.venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/indico/.venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/web/assets/blueprint.py", line 85, in i18n_locale_react
    return _get_i18n_locale(locale_name, react=True)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/web/assets/blueprint.py", line 107, in _get_i18n_locale
    i18n_data = generate_i18n_file(locale_name, react=react)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/web/assets/vars_js.py", line 47, in generate_i18n_file
    i18n_data = get_locale_data(root_path, locale_name, 'indico', react=react)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/web/assets/vars_js.py", line 29, in get_locale_data
    rv = json.load(f)
  File "/opt/indico/.venv/lib/python3.9/site-packages/flask/json/__init__.py", line 251, in load
    return app.json.load(fp, **kwargs)
  File "/opt/indico/.venv/lib/python3.9/site-packages/flask/json/provider.py", line 74, in load
    return self.loads(fp.read(), **kwargs)
  File "/opt/indico/.pyenv/versions/3.9.16/lib/python3.9/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 288: ordinal not in range(128)

how can i fix that error?

**Comment by ThiefMaster** [comment]
See https://talk.getindico.io/t/ascii-codec-cant-decode-in-3-2-2/2947/7?
