### ISSUE TITLE
Resending invitation reminders fails

### ISSUE THREAD

**Issue by bpedersen2** [indico/indico#5879]
I f trying to resend invitation reminders,  serialize is called without params and this triggers an argument error in iter_param_info.

```
Traceback
---------
Traceback (most recent call last):
  File "/opt/indico/.venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/indico/.venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/indico/.venv/lib/python3.10/site-packages/indico/web/flask/util.py", line 79, in wrapper
    return obj().process()
  File "/opt/indico/.venv/lib/python3.10/site-packages/indico/web/rh.py", line 285, in process
    res = self._do_process()
  File "/opt/indico/.venv/lib/python3.10/site-packages/indico/web/rh.py", line 256, in _do_process
    rv = self._process()
  File "/opt/indico/.venv/lib/python3.10/site-packages/indico/modules/events/registration/controllers/management/invitations.py", line 141, in _process
    'placeholders': [p.serialize() for p in placeholders],
  File "/opt/indico/.venv/lib/python3.10/site-packages/indico/modules/events/registration/controllers/management/invitations.py", line 141, in <listcomp>
    'placeholders': [p.serialize() for p in placeholders],
  File "/opt/indico/.venv/lib/python3.10/site-packages/indico/util/placeholders.py", line 190, in serialize
    for param, description in cls.iter_param_info(**kwargs)]
TypeError: EventLinkPlaceholder.iter_param_info() missing 2 required positional arguments: 'person' and 'event'
```

patch is coming

**Comment by ThiefMaster** [comment]
Nice catch. Please open the PR against the 3.2.x branch
