### ISSUE TITLE
More documentation needed for OAuth2

### ISSUE THREAD

**Issue by axu-trex** [indico/indico#5884]
**Is your feature request related to a problem? Please describe.**
I'm trying to make our indico use the OAuth server in our mattermost, and the OAuth at peeringdb.com, and I get the same weird error from both.

**Describe the solution you'd like**
The installation/configuration instructions cover local, LDAP and SAML authentication in detail, but Shibboleth is glossed over and OAuth2 is only mentioned in passing.

**Your configuration**
```
AUTH_PROVIDERS = {
    'mattermost': {
        'type': 'authlib',
        'title': 'mattermost.nog.fi',
        'callback_uri': '/multipass/authlib/mattermost',
        'authlib_args': {
            'client_id': 'myclient',
            'client_secret': 'mysecret',
            'authorize_url': 'https://mattermost.nog.fi/oauth/authorize',
            'access_token_url': 'https://mattermost.nog.fi/oauth/access_token',
            'userinfo_endpoint': 'https://mattermost.nog.fi/api/v4/users/me',
        }
    },
    'peeringdb': {
        'type': 'authlib',
        'title': 'PeeringDB',
        'callback_uri': '/multipass/authlib/peeringdb',
        'authlib_args': {
            'client_id': 'myclient',
            'client_secret': 'mysecret',
            'authorize_url': 'https://auth.peeringdb.com/oauth2/authorize/',
            'access_token_url': 'https://auth.peeringdb.com/oauth2/token/',
            'userinfo_endpoint': 'https://auth.peeringdb.com/profile/v1',
        }
    }
}

IDENTITY_PROVIDERS = {
    'mattermost': {
        'type': 'authlib',
        'identifier_field': 'id',
        'trusted_email': True,
    },
    'peeringdb': {
        'type': 'authlib',
        'identifier_field': 'id',
        'trusted_email': True,
        'mapping': {
            'first_name': 'given_name',
            'last_name': 'family_name',
            'affiliation': 'networks[0].name',
        }
    }
}

PROVIDER_MAP = {
    'mattermost': 'mattermost',
    'peeringdb': 'peeringdb',
}
```

**The error message you're getting**
```
2023-08-07 10:37:40,854  65b0d4ec68194780  -       indico.auth - ERROR auth.py:116 -- Authentication via mattermost failed: unsupported_token_type: Unsupported token_type: 'access_token' (None)


{'data': {'get': {'code': 'b5g9shgmrifs3cbuwafuruikrw9bh3p8fuwfght8b6cjka5shxwc',
                  'state': 'wdb7FU8ooAkpCZQe8oEjx6GMjc5teB'},
          'headers': {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
                      'Accept-Encoding': 'gzip, deflate, br',
                      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8',
                      'Cookie': 'indico_session=a4fccfe0-3a27-47a6-a4f5-60451cee7152',
                      'Host': 'indico.nog.fi',
                      'Sec-Ch-Ua': '"Not/A)Brand";v="99", "Google '
                                   'Chrome";v="115", "Chromium";v="115"',
                      'Sec-Ch-Ua-Mobile': '?0',
                      'Sec-Ch-Ua-Platform': '"macOS"',
                      'Sec-Fetch-Dest': 'document',
                      'Sec-Fetch-Mode': 'navigate',
                      'Sec-Fetch-Site': 'same-site',
                      'Sec-Fetch-User': '?1',
                      'Upgrade-Insecure-Requests': '1',
                      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X '
                                    '10_15_7) AppleWebKit/537.36 (KHTML, like '
                                    'Gecko) Chrome/115.0.0.0 Safari/537.36'},
          'json': None,
          'post': {},
          'url': {}},
 'endpoint': '_flaskmultipass_authlib_mattermost',
 'id': '65b0d4ec68194780',
 'ip': '2001:db8:::::::',
 'method': 'GET',
 'referrer': None,
 'rh': 'RHSimple',
 'time': '2023-08-07T10:37:40.987138',
 'url': 'https://indico.nog.fi/multipass/authlib/mattermost?code=b5g9shgmrifs3cbuwafuruikrw9bh3p8fuwfght8b6cjka5shxwc&state=wdb7FU8ooAkpCZQe8oEjx6GMjc5teB',
 'user': None,
 'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
               'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 '
               'Safari/537.36'}
```
I've tried  Macos+Chrome and Linux+Firefox as well, with the same results. I can't find anything useful in the indico or mattermost logs that would put me on the right track to find what's wrong with my configuration. I can't really even tell who is causing the token type error, but considering I'm getting the same error from peeringdb, a public and well working service, I'm pretty sure the problem is with my indico.

**Comment by axu-trex** [comment]
After a lot of poking in the dark, I managed to get Mattermost working, and I got a different error from PeeringDB. This is my config now:

```
AUTH_PROVIDERS = {
    'mattermost': {
        'type': 'authlib',
        'title': 'mattermost.nog.fi',
        'callback_uri': '/multipass/authlib/mattermost',
        'authlib_args': {
            'client_id': 'myclient',
            'client_secret': 'mysecret',
            'client_kwargs': {
                  'response_type': 'code',
                  'token_endpoint_auth_method': 'client_secret_post',
            },
            'authorize_url': 'https://mattermost.nog.fi/oauth/authorize',
            'access_token_url': 'https://mattermost.nog.fi/oauth/access_token',
            'userinfo_endpoint': 'https://mattermost.nog.fi/api/v4/users/me',
        }
    },
    'peeringdb': {
        'type': 'authlib',
        'title': 'PeeringDB',
        'callback_uri': '/multipass/authlib/peeringdb',
        'authlib_args': {
            'client_id': 'myclient',
            'client_secret': 'mysecret',
            'client_kwargs': {
                  'response_type': 'code',
                  'scope': 'openid',
            },
            'authorize_url': 'https://auth.peeringdb.com/oauth2/authorize/',
            'access_token_url': 'https://auth.peeringdb.com/oauth2/token/',
            'userinfo_endpoint': 'https://auth.peeringdb.com/profile/v1',
        }
    }
}
```

And the error message I get for PeeringDB now looks like this:
```
2023-08-09 00:03:36,761  623cc16a5d734694  -       indico.flask - ERROR errors.py:110 -- OpenIDMixin.parse_id_token() missing 1 required positional argument: 'nonce'

Traceback (most recent call last):
  File "/opt/indico/.venv/lib/python3.11/site-packages/flask_multipass/providers/authlib.py", line 138, in _authorize_callback
    id_token = dict(token_data['userinfo'])
                    ~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'userinfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/indico/.venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.11/site-packages/indico/web/rh.py", line 337, in wrapper
    return rh.process()
           ^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.11/site-packages/indico/web/rh.py", line 285, in process
    res = self._do_process()
          ^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.11/site-packages/indico/web/rh.py", line 256, in _do_process
    rv = self._process()
         ^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.11/site-packages/indico/web/rh.py", line 326, in _process
    rv = self.func()
         ^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.11/site-packages/flask_multipass/util.py", line 119, in decorator
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.11/site-packages/flask_multipass/providers/authlib.py", line 141, in _authorize_callback
    id_token = self.authlib_client.parse_id_token(token_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OpenIDMixin.parse_id_token() missing 1 required positional argument: 'nonce'

{'data': {'get': {'code': 'Nj1LCW2Wb7J8WYYMFJmmRlyZmcTzUj',
                  'state': '1x5tLJz4lzkDWyvzIU6voPxyrTDP33'},
          'headers': {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
                      'Accept-Encoding': 'gzip, deflate, br',
                      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8',
                      'Cache-Control': 'max-age=0',
                      'Cookie': 'indico_session=71748a9a-8aca-4a88-8e11-819cfde314db',
                      'Host': 'indico.nog.fi',
                      'Referer': 'https://auth.peeringdb.com/',
                      'Sec-Ch-Ua': '"Not/A)Brand";v="99", "Google '
                                   'Chrome";v="115", "Chromium";v="115"',
                      'Sec-Ch-Ua-Mobile': '?0',
                      'Sec-Ch-Ua-Platform': '"macOS"',
                      'Sec-Fetch-Dest': 'document',
                      'Sec-Fetch-Mode': 'navigate',
                      'Sec-Fetch-Site': 'cross-site',
                      'Sec-Fetch-User': '?1',
                      'Upgrade-Insecure-Requests': '1',
                      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X '
                                    '10_15_7) AppleWebKit/537.36 (KHTML, like '
                                    'Gecko) Chrome/115.0.0.0 Safari/537.36'},
          'json': None,
          'post': {},
          'url': {}},
 'endpoint': '_flaskmultipass_authlib_peeringdb',
 'id': '623cc16a5d734694',
 'ip': '2001:db8:::::',
 'method': 'GET',
 'referrer': 'https://auth.peeringdb.com/',
 'rh': 'RHSimple',
 'time': '2023-08-09T00:03:38.508002',
 'url': 'https://indico.nog.fi/multipass/authlib/peeringdb?code=Nj1LCW2Wb7J8WYYMFJmmRlyZmcTzUj&state=1x5tLJz4lzkDWyvzIU6voPxyrTDP33',
 'user': None,
 'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
               'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 '
               'Safari/537.36'}
```

I think it would be quite useful, if DEBUG=True would log the actual dicts received during OAuth exchanges. Is 'userinfo_compliance_fix' a valid auth provider setting in Indico? I found that on some Google search result, and I think I would need something like that for the Affiliation mapping with PeeringDB...

**Comment by axu-trex** [comment]
After having looked at the code for some time, the last error looks like a real bug in the exception handling section. But that being said, I don't think I should be even going into that exception handling section under normal conditions?
