### ISSUE TITLE
server_url can't be empty

### ISSUE THREAD

**Issue by bilias** [indico/indico#5989]
**Describe the bug**
When someone tries to access statistics from Reports -> Statistics on the events management page
(https://xx.xx.xx.xx/event/5/manage/statistics/)
there is an error:

Something went wrong

    ValueError: server_url can't be empty

BASE_URL is set correctly in indico.conf

This happens on 3.2.8, but I've also received such an error with 3.2.7 and 3.2.6

There is also a mail about this to the administrator

```
2023-10-12 09:56:14,315  68348dee9ab943e3  13      indico.flask - ERROR errors.py:110 -- server_url can't be empty

Traceback (most recent call last):
  File "/opt/indico/.venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/indico/.venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/indico/.venv/lib/python3.9/site-packages/flask_pluginengine/util.py", line 190, in wrapped
    return func(*args, **kwargs)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/web/flask/util.py", line 79, in wrapper
    return obj().process()
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/web/rh.py", line 285, in process
    res = self._do_process()
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/web/rh.py", line 256, in _do_process
    rv = self._process()
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico_piwik/controllers.py", line 37, in _process
    report = ReportGeneral.get(event_id=self.event.id,
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico_piwik/reports.py", line 59, in get
    report = cls(*args, **kwargs)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico_piwik/reports.py", line 38, in __init__
    self._build_report(**report_params)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico_piwik/reports.py", line 101, in _build_report
    queries = {'visits': PiwikQueryReportEventMetricVisits(**self.params),
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico_piwik/queries/base.py", line 41, in __init__
    super().__init__()
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico_piwik/queries/base.py", line 30, in __init__
    super().__init__(query_script=PiwikPlugin.report_script)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico_piwik/queries/base.py", line 16, in __init__
    self.request = PiwikRequest(server_url=PiwikPlugin.settings.get('server_api_url'),
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico_piwik/piwik.py", line 20, in __init__
    raise ValueError("server_url can't be empty")
ValueError: server_url can't be empty

{'data': {'get': {},
          'headers': {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
                      'Accept-Encoding': 'gzip, deflate, br',
........
........
'json': None,
          'post': {},
          'url': {'event_id': 5}},
 'endpoint': 'plugin_piwik.view',
 'id': '68348dee9ab943e3',
 'ip': 'xxx.xxx.xxx.xxx',
 'method': 'GET',
 'referrer': 'https://xx.xx.xx/event/5/manage/logs/',
 'rh': 'RHStatistics',
 'time': '2023-10-12T09:56:14.325034',
 'url': 'https://xx.xx.xx/event/5/manage/statistics/',
 'user': {'email': '[user@example.com](mailto:user@example.com)',
          'id': 13,
          'name': 'First Last'},
```

**Comment by ThiefMaster** [comment]
That's because you enabled a plugin (`piwik`) but did not configure it. If you have a Piwik/Matomo instance configure it in the admin plugin settings, if not disable the pugin.

**Comment by bilias** [comment]
ok, I see.
I have Piwik server URL configured but not API details.

What if I want indico to send stats to matomo but I don't want to allow managers to see statistics?

**Comment by ThiefMaster** [comment]
not supported atm, PR appreciated though ;)
