### ISSUE TITLE
indico setup list-plugins crashes with probable circular import

### ISSUE THREAD

**Issue by EdwardMoyse** [indico/indico#6092]
**Describe the bug**
`indico setup list-plugins` crashes with the following message: `ImportError: cannot import name 'serialize_registration_form' from partially initialized module 'indico.modules.events.registration.util' (most likely due to a circular import) (/Users/emoyse/LocalDocuments/indico/src/indico/modules/events/registration/util.py)`

I am running on macOS 14.1.2 (23B92), on a MacBook Pro with M1Pro Apple silicon.

**To Reproduce**

I followed the installation instructions [here](https://docs.getindico.io/en/latest/installation/development/)

And now my indico directory looks as follows.
```
(env) emoyse@Edwards-MBP-10 indico % ls
data			indico-plugins-cern	plugins
env			maildump		src
```

However when I try `indico setup list-plugins ` in either the indico root, or in `src`, I get the following:

```
(env) emoyse@Edwards-MBP-10 src % indico setup list-plugins
Traceback (most recent call last):
  File "/Users/emoyse/LocalDocuments/indico/env/bin/indico", line 33, in <module>
    sys.exit(load_entry_point('indico', 'console_scripts', 'indico')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/src/indico/cli/util.py", line 108, in invoke
    return self._impl.invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/src/indico/cli/setup.py", line 182, in list_plugins
    import_all_models()
  File "/Users/emoyse/LocalDocuments/indico/src/indico/core/db/sqlalchemy/util/models.py", line 265, in import_all_models
    import_module(module)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/emoyse/LocalDocuments/indico/src/indico/modules/receipts/__init__.py", line 11, in <module>
    from indico.modules.events.registration.util import ActionMenuEntry
  File "/Users/emoyse/LocalDocuments/indico/src/indico/modules/events/registration/util.py", line 44, in <module>
    from indico.modules.events.registration.notifications import (notify_invitation, notify_registration_creation,
  File "/Users/emoyse/LocalDocuments/indico/src/indico/modules/events/registration/notifications.py", line 14, in <module>
    from indico.modules.events.ical import MIMECalendar, event_to_ical
  File "/Users/emoyse/LocalDocuments/indico/src/indico/modules/events/ical.py", line 22, in <module>
    from indico.modules.events.contributions.models.contributions import Contribution
  File "/Users/emoyse/LocalDocuments/indico/src/indico/modules/events/contributions/__init__.py", line 16, in <module>
    from indico.modules.events.contributions.contrib_fields import get_contrib_field_types
  File "/Users/emoyse/LocalDocuments/indico/src/indico/modules/events/contributions/contrib_fields.py", line 14, in <module>
    from indico.web.fields.choices import SingleChoiceField
  File "/Users/emoyse/LocalDocuments/indico/src/indico/web/fields/choices.py", line 13, in <module>
    from indico.web.forms.fields import IndicoRadioField, IndicoSelectMultipleCheckboxField, MultiStringField
  File "/Users/emoyse/LocalDocuments/indico/src/indico/web/forms/fields/__init__.py", line 26, in <module>
    from .principals import AccessControlListField, PrincipalField, PrincipalListField
  File "/Users/emoyse/LocalDocuments/indico/src/indico/web/forms/fields/principals.py", line 17, in <module>
    from indico.modules.events.registration.util import serialize_registration_form
ImportError: cannot import name 'serialize_registration_form' from partially initialized module 'indico.modules.events.registration.util' (most likely due to a circular import) (/Users/emoyse/LocalDocuments/indico/src/indico/modules/events/registration/util.py)
```

I will try in a container to see if this is macOS specific.

**Comment by ThiefMaster** [comment]
Ugh, this tends to happen depending on the import order which I would expect to be stable...

This is on an unmodified and up-to-date `master`?

**Comment by tomasr8** [comment]
I've actually also ran into the same error when running `update_backrefs.py`. This fixed it for me: https://github.com/indico/indico/pull/6088/commits/db18fec87a2f75ad1f6e859ee0907ab673a75c40

**Comment by EdwardMoyse** [comment]
> Ugh, this tends to happen depending on the import order which I would expect to be stable...
> 
> This is on an unmodified and up-to-date `master`?

Yep. Just installed it all from scratch.

**Comment by ThiefMaster** [comment]
don't Install plugins from pypi for a dev setup, you need the git master

**Comment by EdwardMoyse** [comment]
Just FYI I updated the OP with the information that I do not see this on AlmaLinux9

**Comment by ThiefMaster** [comment]
Can you check if the commit from @tomasr8 fixes the problem for you on mac? db18fec87a2f75ad1f6e859ee0907ab673a75c40

**Comment by EdwardMoyse** [comment]
> don't install plugins from pypi for a dev setup, you need the git master

I only installed them to see if it would fix the problem. I just did:
```
pip uninstall indico-plugins
```
but I still have :
```
ImportError: cannot import name '_app_ctx_stack' from 'flask.globals' (/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/flask/globals.py)
```
I guess I will delete it all and start from scratch, but out of interest, how did you know I had installed `indico-plugins`?

**Comment by ThiefMaster** [comment]
`pip freeze | grep indico-plugin` - you can also uninstall those packages since `indico-plugins` is just a meta-package pulling in the actual plugin packages.

And it was an educated guess because I know that this particular error happens when running an older ("stable release", 3.2.x) version of the plugins on the flask version used in Indico master (3.3)

**Comment by EdwardMoyse** [comment]
> Can you check if the commit from @tomasr8 fixes the problem for you on mac? [db18fec](https://github.com/indico/indico/commit/db18fec87a2f75ad1f6e859ee0907ab673a75c40)

With a fresh install, yes this works!
