### ISSUE TITLE
indico db prepare throws error

### ISSUE THREAD

**Issue by viveknallur** [indico/indico#6203]
**Describe the bug**
Followed all the steps to install indico on a Ubuntu jammy. Reached step 9. `indico db prepare`  results in the following error

```
Traceback (most recent call last):

  File "/opt/indico/.venv/bin/indico", line 8, in <module>
    sys.exit(cli())
  File "/opt/indico/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/indico/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/indico/.venv/lib/python3.9/site-packages/click/core.py", line 1655, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/opt/indico/.venv/lib/python3.9/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/opt/indico/.venv/lib/python3.9/site-packages/click/core.py", line 1613, in parse_args
    rest = super().parse_args(ctx, args)
  File "/opt/indico/.venv/lib/python3.9/site-packages/click/core.py", line 1374, in parse_args
    parser = self.make_parser(ctx)
  File "/opt/indico/.venv/lib/python3.9/site-packages/click/core.py", line 1288, in make_parser
    for param in self.get_params(ctx):
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/cli/util.py", line 114, in get_params
    return self._impl.get_params(ctx)
  File "/opt/indico/.venv/lib/python3.9/site-packages/werkzeug/utils.py", line 106, in __get__
    value = self.fget(obj)  # type: ignore
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/cli/util.py", line 99, in _impl
    return getattr(import_module(module), name)
  File "/opt/indico/.pyenv/versions/3.9.0/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/cli/database.py", line 21, in <module>
    from indico.core.db.sqlalchemy.migration import PluginScriptDirectory, migrate, prepare_db
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/core/db/sqlalchemy/migration.py", line 18, in <module>
    from indico.core.db.sqlalchemy.util.management import create_all_tables, get_all_tables
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/core/db/sqlalchemy/util/management.py", line 12, in <module>
    from indico.core.db.sqlalchemy.protection import ProtectionMode
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/core/db/sqlalchemy/protection.py", line 20, in <module>
    from indico.core.db.sqlalchemy.principals import EmailPrincipal, PrincipalType
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/core/db/sqlalchemy/principals.py", line 20, in <module>
    class PrincipalType(IndicoIntEnum):
  File "/opt/indico/.pyenv/versions/3.9.0/lib/python3.9/enum.py", line 215, in __new__
    enum_member = __new__(enum_class)
TypeError: object.__new__(PrincipalType) is not safe, use int.__new__()
```

**To Reproduce**
The only step where I differed is that I used the commands from `https://nginx.org/en/linux_packages.html#Ubuntu` to install nginx, instead of the command in step 1 (`echo "deb http://nginx.org/packages/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/ $(lsb_release -cs) nginx" > /etc/apt/sources.list.d/nginx.list`), since that didn't work for me

*Also*: I don't have an SMTP server (and I don't need emails from indico), so I entered `localhost` during the setup wizard

**Expected behavior**
I expected the database table(s) to be created successfully

**Comment by ThiefMaster** [comment]
3.9.0 is extremely ancient. Can you please confirm whether this error happens with a more recent Python 3.9.x version?

**Comment by viveknallur** [comment]
Thanks for letting me know. I do appreciate it. I had initially installed the latest version 3.13, but then `pip install indico` fails. So, I rolled back to the version suggested by the docs. And just to be careful, I went for 3.9.0 :-). If you could confirm that it works with 3.12, I’ll happily go to that version.

 Also, probably a good idea to add the caveat to the end of ‘step 5’ at: `https://docs.getindico.io/en/stable/installation/production/debian/nginx/`
