### ISSUE TITLE
Upgrade 3.3.1 fails

### ISSUE THREAD

**Issue by bilias** [indico/indico#6262]
I'm trying to upgrade a 3.2.9 installation to 3.3.1

I've followed the guide
https://docs.getindico.io/en/stable/installation/upgrade/#upgrade-3-to-33
and then moved to
https://docs.getindico.io/en/stable/installation/upgrade/#upgrade-3-to-3-plugins

indico db upgrade
fails. Actually most of indico commands fail:

```
Traceback (most recent call last):                                                                                                                                   
  File "/opt/indico/.venv/bin/indico", line 8, in <module>                                                                                                           
    sys.exit(cli())                                                                                                                                                  
             ^^^^^                                                                                                                                                  
  File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __cal                                                                           l__                                                                                                     
    return self.main(*args, **kwargs)                                                                                                                                
           ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                
  File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main                                                                            
    rv = self.invoke(ctx)                                                                                                                                            
         ^^^^^^^^^^^^^^^^                                                                                                                                            
  File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invok                                                                           e                                                                                               
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                          
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                           
  File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invok                                                                           e                                                                                               
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                   
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                   
  File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke                                                                           
    return __callback(*args, **kwargs)                                                                                                                               
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                               
  File "/opt/indico/.venv/lib/python3.12/site-packages/click/decorators.py", line 33, in n                                                                           ew_func                                                                                                                 
    return f(get_current_context(), *args, **kwargs)                                                                                                                 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                 
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask/cli.py", line 385, in decorat                                                                           or                                                                                                  
    app = ctx.ensure_object(ScriptInfo).load_app()                                                                                                                   
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                               
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask/cli.py", line 330, in load_ap                                                                           p                                                                                               
    app: Flask | None = self.create_app()                                                                                                                            
                        ^^^^^^^^^^^^^^^^^                                                                                                                            
  File "/opt/indico/.venv/lib/python3.12/site-packages/indico/cli/util.py", line 26, in _c                                                                           reate_app                                                                                                                       
    return make_app()                                                                                                                                                
           ^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/indico/web/flask/app.py", line 420, in make_app
    multipass.init_app(app)
  File "/opt/indico/.venv/lib/python3.12/site-packages/indico/core/auth.py", line 80, in init_app
    super().init_app(app)
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask_multipass/core.py", line 73, in init_app
    state.auth_providers = ImmutableDict(self._create_providers('AUTH', AuthProvider))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask_multipass/core.py", line 461, in _create_providers
    cls = resolve_provider_type(base, settings.pop('type'), registry)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask_multipass/util.py", line 158, in resolve_provider_type
    cls = entry_point.load()
          ^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/importlib_metadata/__init__.py", line 184, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.pyenv/versions/3.12.2/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask_multipass/providers/ldap/__init__.py", line 7, in <module>
    from .providers import LDAPAuthProvider, LDAPGroup, LDAPIdentityProvider, AuthFallbackLDAPIdentityProvider
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask_multipass/providers/ldap/providers.py", line 10, in <module>
    from ldap import INVALID_CREDENTIALS
ModuleNotFoundError: No module named 'ldap'
(.venv) [indico@griffin ~]$ indico  cleanup
Traceback (most recent call last):
  File "/opt/indico/.venv/bin/indico", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask/cli.py", line 385, in decorator
    app = ctx.ensure_object(ScriptInfo).load_app()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask/cli.py", line 330, in load_app
    app: Flask | None = self.create_app()
                        ^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/indico/cli/util.py", line 26, in _create_app
    return make_app()
           ^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/indico/web/flask/app.py", line 420, in make_app
    multipass.init_app(app)
  File "/opt/indico/.venv/lib/python3.12/site-packages/indico/core/auth.py", line 80, in init_app
    super().init_app(app)
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask_multipass/core.py", line 73, in init_app
    state.auth_providers = ImmutableDict(self._create_providers('AUTH', AuthProvider))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask_multipass/core.py", line 461, in _create_providers
    cls = resolve_provider_type(base, settings.pop('type'), registry)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask_multipass/util.py", line 158, in resolve_provider_type
    cls = entry_point.load()
          ^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/importlib_metadata/__init__.py", line 184, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.pyenv/versions/3.12.2/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask_multipass/providers/ldap/__init__.py", line 7, in <module>
    from .providers import LDAPAuthProvider, LDAPGroup, LDAPIdentityProvider, AuthFallbackLDAPIdentityProvider
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask_multipass/providers/ldap/providers.py", line 10, in <module>
    from ldap import INVALID_CREDENTIALS
ModuleNotFoundError: No module named 'ldap'
```

**Comment by ThiefMaster** [comment]
As indicated during the `indico setup upgrade-python` command, any plugins and other libraries must be reinstalled. In your case this can be solved by a simple `pip install python-ldap`.

**Comment by bilias** [comment]
After installiong python-ldap and pango (OS) upgrade continued.
Thanks for the very quick reply.
