### ISSUE TITLE
Indico uses `pkg_resources` but does not declare `setuptools` as runtime dependency

### ISSUE THREAD

**Issue by maxnoe** [indico/indico#6270]
**Describe the bug**

As title. This leads to import errors in venvs under python 3.12, as setuptools is no longer 
installed into venvs by default.

https://docs.python.org/3/whatsnew/3.12.html

**To Reproduce**

Create a new venv, install indico and run e.g.:

```
/opt/indico/.venv/bin/indico setup create-logging-config /opt/indico/etc:                                                        
1.030 Traceback (most recent call last):                                                                  
1.030   File "/opt/indico/.venv/bin/indico", line 8, in <module>                                          
1.030     sys.exit(cli())
1.030              ^^^^^
1.030   File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
1.031     return self.main(*args, **kwargs)
1.031            ^^^^^^^^^^^^^^^^^^^^^^^^^^
1.031   File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
1.031     rv = self.invoke(ctx)
1.031          ^^^^^^^^^^^^^^^^
1.031   File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 1686, in invoke
1.031     sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
1.032               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.032   File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 943, in make_context
1.032     self.parse_args(ctx, args)
1.032   File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 1644, in parse_args
1.032     rest = super().parse_args(ctx, args)
1.032            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.032   File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 1404, in parse_args
1.033     parser = self.make_parser(ctx)
1.033              ^^^^^^^^^^^^^^^^^^^^^
1.033   File "/opt/indico/.venv/lib/python3.12/site-packages/click/core.py", line 1315, in make_parser
1.033     for param in self.get_params(ctx):
1.034                  ^^^^^^^^^^^^^^^^^^^^
1.034   File "/opt/indico/.venv/lib/python3.12/site-packages/indico/cli/util.py", line 114, in get_params
1.034     return self._impl.get_params(ctx)
1.034            ^^^^^^^^^^
1.034   File "/opt/indico/.venv/lib/python3.12/site-packages/werkzeug/utils.py", line 106, in __get__
1.034     value = self.fget(obj)  # type: ignore
1.034             ^^^^^^^^^^^^^^
1.034   File "/opt/indico/.venv/lib/python3.12/site-packages/indico/cli/util.py", line 99, in _impl
1.034     return getattr(import_module(module), name)
1.034                    ^^^^^^^^^^^^^^^^^^^^^
1.034   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
1.034     return _bootstrap._gcd_import(name[level:], package, level)
1.034            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.034   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
1.034   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
1.034   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
1.034   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
1.034   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
1.034   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
1.034   File "/opt/indico/.venv/lib/python3.12/site-packages/indico/cli/setup.py", line 24, in <module>
1.034     from pkg_resources import iter_entry_points
1.034 ModuleNotFoundError: No module named 'pkg_resources'
```

**Expected behavior**

Correctly declare dependencies.

**Comment by ThiefMaster** [comment]
All our install guides install setuptools before installing indico. So you should not get this error... :)

The current version of `pip-compile` does not add `setuptools` to the requirements unless you ask it to include "unsafe" dependencies (this changes in the next major release). By then I might have switched over to the new `uv` tool though.

Anyway, TL;DR is that I'm aware of this and will fix this once there's a clean way of doing it.

**Comment by maxnoe** [comment]
> All our install guides install setuptools before installing indico. So you should not get this error... :)

Why include a manual step if packages can declare their runtime dependencies?

**Comment by ThiefMaster** [comment]
Because install behavior also slightly changes depending on whether setuptools is present or not. Not in a breaking way (I fixed that part, it only affected dev setups anyway), but still ugly. So we kind of want `setuptools` to be installed beforehand.

Anyway, like I said, I'm also very much in favor of fixing this properly. And I see you opened #6272 for which a PR would be very much appreciated! :)

**Comment by maxnoe** [comment]
Closing, since #6272 was merged
