### ISSUE TITLE
`build-wheel.py` fails with `ModuleNotFoundError: No module named 'flask_url_map_serializer'`

### ISSUE THREAD

**Issue by paulmenzel** [indico/indico#6377]
$ git log --oneline --no-decorate -1
    bf5e80e457 Highlight errors for regform bool fields (#6242)
    $ pip install -e '.[dev]' --prefix /project/initindico/indico-20240605
    $ python ./bin/maintenance/build-wheel.py -d /dev/shm indico
    building assets
    Error: building assets failed
    Traceback (most recent call last):
      File "/project/initindico/home/src/indico/bin/maintenance/dump_url_map.py", line 14, in <module>
        from flask_url_map_serializer import dump_url_map
    ModuleNotFoundError: No module named 'flask_url_map_serializer'
    Traceback (most recent call last):
      File "/project/initindico/home/src/indico/./bin/maintenance/build-assets.py", line 272, in <module>
        cli()
      File "/pkg/python-3.11.7-1/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
        return self.main(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/pkg/python-3.11.7-1/lib/python3.11/site-packages/click/core.py", line 1078, in main
        rv = self.invoke(ctx)
             ^^^^^^^^^^^^^^^^
      File "/pkg/python-3.11.7-1/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/pkg/python-3.11.7-1/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
        return ctx.invoke(self.callback, **ctx.params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/pkg/python-3.11.7-1/lib/python3.11/site-packages/click/core.py", line 783, in invoke
        return __callback(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/project/initindico/home/src/indico/./bin/maintenance/build-assets.py", line 177, in build_indico
        subprocess.check_call([sys.executable, 'bin/maintenance/dump_url_map.py', '--output', url_map_path, *force_url_map])
      File "/pkg/python-3.11.7-1/lib/python3.11/subprocess.py", line 413, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/pkg/python-3.11.7-1/bin/python', 'bin/maintenance/dump_url_map.py', '--output', '/project/initindico/home/src/indico/url_map.json', '--force']' returned non-zero exit status 1.

`pip install -e '.[dev]' flask_url_map_serializer` fixes it.

**Comment by ThiefMaster** [comment]
If you `pip install -e '.[dev]'` and have the (Python) (virtual)environment where you installed indico enabled, `flask_url_map_serializer` should be available. My guess with the error you're getting is that you are trying to run this script outside that environment.

**Comment by ThiefMaster** [comment]
It's direct dependency: `flask-url-map-serializer`

**Comment by paulmenzel** [comment]
Hmm, I guess I need to look into `pip install` more, and how `.[dev]` is supposed to work.
