### ISSUE TITLE
Unable to save contribution `Timetable inconsistent: Entry ends after its parent block`

### ISSUE THREAD

**Issue by paulmenzel** [indico/indico#6471]
Indico 3.3.2

```
2024-08-07 13:30:06,701  28a52a0aba3d4e08  2       indico.flask - ERROR errors.py:110 -- Timetable inconsistent: Entry ends after its parent block

Traceback (most recent call last):
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1094, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 686, in do_commit
    dbapi_connection.commit()
psycopg2.DatabaseError: Timetable inconsistent
DETAIL:  Entry ends after its parent block
CONTEXT:  PL/pgSQL function events.check_timetable_consistency() line 76 at RAISE


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/indico/web/rh.py", line 303, in process
    db.session.commit()
  File "<string>", line 2, in commit
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1454, in commit
    self._transaction.commit(_to_root=self.future)
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 839, in commit
    trans.commit()
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2469, in commit
    self._do_commit()
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2659, in _do_commit
    self._connection_commit_impl()
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2630, in _connection_commit_impl
    self.connection._commit_impl()
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1096, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1094, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 686, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.DatabaseError: (psycopg2.DatabaseError) Timetable inconsistent
DETAIL:  Entry ends after its parent block
CONTEXT:  PL/pgSQL function events.check_timetable_consistency() line 76 at RAISE

(Background on this error at: https://sqlalche.me/e/14/4xp6)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/indico/web/flask/util.py", line 80, in wrapper
    return obj().process()
           ^^^^^^^^^^^^^^^
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/indico/web/rh.py", line 309, in process
    handle_sqlalchemy_database_error()  # this will re-raise an exception
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/initindico/home/.venv/lib/python3.12/site-packages/indico/core/db/sqlalchemy/core.py", line 59, in handle_sqlalchemy_database_error
    raise ConstraintViolated(msg, exc.orig) from exc
indico.core.db.sqlalchemy.core.ConstraintViolated: Timetable inconsistent: Entry ends after its parent block

{'data': {'get': {'day': '2024/09/25', 'session_block_id': '4'},
          'headers': {'Accept': 'application/json, text/javascript, */*; '
                                'q=0.01',
                      'Accept-Encoding': 'gzip, deflate, br, zstd',
                      'Accept-Language': 'en-US,en;q=0.5',
                      'Content-Length': '327',
                      'Content-Type': 'application/x-www-form-urlencoded; '
                                      'charset=UTF-8',
                      'Cookie': 'indico_session=c4054f47-cbd2-4312-b5a1-463db07e2205',
                      'Host': 'init-events.molgen.mpg.de',
                      'Origin': 'https://init-events.molgen.mpg.de/',
                      'Priority': 'u=0',
                      'Referer': 'https://init-events.molgen.mpg.de/event/1/manage/timetable/',
                      'Sec-Fetch-Dest': 'empty',
                      'Sec-Fetch-Mode': 'cors',
                      'Sec-Fetch-Site': 'same-origin',
                      'Te': 'trailers',
                      'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) '
                                    'Gecko/20100101 Firefox/131.0',
                      'X-Csrf-Token': '13263da9-38bd-413e-911c-40e5c0ec10e0',
                      'X-Requested-With': 'XMLHttpRequest'},
          'json': None,
          'post': {'board_number': '',
                   'code': '',
                   'csrf_token': '13263da9-38bd-413e-911c-40e5c0ec10e0',
                   'description': '',
                   'duration': '52200',
                   'location_data': '{"address":"","inheriting":true,"venue_id":1,"venue_name":"Faßberg-Campus"}',
                   'person_link_data': '[]',
                   'references': '[]',
                   'time': '13:30',
                   'title': 'Wanderung zum Faßberg',
                   'type': '9'},
          'url': {'event_id': 1}},
 'endpoint': 'timetable.add_contribution',
 'id': '28a52a0aba3d4e08',
 'ip': '95.90.247.210',
 'method': 'POST',
 'referrer': 'https://init-events.molgen.mpg.de/event/1/manage/timetable/',
 'rh': 'RHLegacyTimetableAddContribution',
 'time': '2024-08-07T13:30:06.835863',
 'url': 'https://init-events.molgen.mpg.de/event/1/manage/timetable/add-contribution?day=2024/09/25&session_block_id=4',
 'user': {'email': '[pmenzel@molgen.mpg.de](mailto:pmenzel@molgen.mpg.de)', 'id': 2, 'name': 'Paul Menzel'},
 'user_agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 '
               'Firefox/131.0'}
```

**Comment by paulmenzel** [comment]
I logged out, so the session cookies in my paste should not matter?

**Comment by ThiefMaster** [comment]
Yes, just I removed them from the original post nonetheless ;)

**Comment by ThiefMaster** [comment]
I'm afraid without more context this report is not going to be very useful - in the end, this is a safeguard to prevent data inconsistencies like something ending after the event time or in this case after the end time of the surrounding session block (which usually gets auto-enlarged to fit a new contribution if it's otherwise too long).

However, considering we're working on an updated timetable management interface anyway for v3.4, I don't think there's anything that needs to be done in the short term here.
