### ISSUE TITLE
Room booking plugin: Location name with "-" leads to error when using HTTP API access

### ISSUE THREAD

**Issue by pbotte** [indico/indico#6527]
**Describe the bug**
"HIM-Building 1395" as a location name which was fine until one tries to access it via the HTTP API. Renaming it to "HIM" solved the problem.

**To Reproduce**
1. Rename your location to "HIM-Building 1395"
2. API access, eg. `curl "https://indico.him.uni-mainz.de/export/room/HIM/8.json...` 
3. See error:

```
2024-09-05 16:41:28,004 fc56103bece945ce indico.flask - ERROR errors.py:113 --
invalid literal for int() with base 10: ' huddle'

Traceback (most recent call last):
File "/opt/indico/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in
full_dispatch_request
rv = self.dispatch_request()
^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/indico/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in
dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type:
ignore[no-any-return]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File
"/opt/indico/.venv/lib/python3.12/site-packages/indico/web/http_api/handlers.py", line
221, in handler
res = hook(user)
^^^^^^^^^^
File
"/opt/indico/.venv/lib/python3.12/site-packages/indico/web/http_api/hooks/base.py",
line 186, in __call__
is_response, resultList, complete, extra = self._perform(user, func, extra_func)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File
"/opt/indico/.venv/lib/python3.12/site-packages/indico/web/http_api/hooks/base.py",
line 161, in _perform
self._getParams()
File "/opt/indico/.venv/lib/python3.12/site-packages/indico/modules/rb/api.py", line
61, in _getParams
self._ids = list(map(int, self._pathParams['idlist'].split('-')))
```

**Expected behavior**
"-" in location names should be allowed OR clearly written somewhere, that they are forbidden.

**Comment by ThiefMaster** [comment]
Looks like it's missing in this regex. Try this change in api.py line 50:

```patch
-RE = r'(?P<location>[\w\s]+)/(?P<idlist>\w+(?:-[\w\s]+)*)'
+RE = r'(?P<location>[\w\s-]+)/(?P<idlist>\w+(?:-[\w\s]+)*)'
```

FWIW that API is extremely legacy, you're most likely better off using the internal APIs that are also used by the React web frontend of the room booking module.

**Comment by pbotte** [comment]
This solved the problem. Thanks!

Is there any documentation on how to get the data like the react web frontend does?

**Comment by pbotte** [comment]
Some addition: I am not entirely sure that the proposed change completely fixes the problem. With the fix applied and a location name of "HIM", a URL request with "HIM-Bau" and "HIM" both returned the same (successful) result. I would expect that some error to be returned as either "HIM-Bau" or "Bau" is not found.

All in all: as @ThiefMaster pointed out, this interface is quite old and the simplest solution is to note everywhere to not include "-" into the location name.
